-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Aura max-stack data ([spellID] = maxStacks, stacking auras only).
-- A stacking aura is never 'unique already active' - client-data veto for
-- RedundancyFilter's unique-aura classification.
-- GENERATED by tools/gen_aura_stacks.py from client data build 12.1.0.68301.
-- Do not hand-edit.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterAuraStacks then return end

SpellDB.RegisterAuraStacks({
[974]=9,  -- Earth Shield
[980]=8,  -- Agony
[6360]=11,  -- Whiplash
[20243]=3,  -- Devastate
[52127]=9,  -- Water Shield
[73685]=2,  -- Unleash Life
[86678]=5,  -- Light of the Ancient Kings
[108839]=3,  -- Ice Floes
[115236]=3,  -- Void Shield
[137639]=2,  -- Storm, Earth, and Fire
[157982]=5,  -- Tranquility
[191034]=20,  -- Starfall
[191634]=4,  -- Stormkeeper
[210714]=2,  -- Icefury
[210726]=4,  -- Mark of Aluneth
[211088]=10,  -- Mark of Aluneth
[224968]=4,  -- Mark of Aluneth
[231895]=10,  -- Avenging Wrath
[260708]=18,  -- Sweeping Strikes
[316440]=3,  -- Martial Prowess
[323546]=99,  -- Ravenous Frenzy
[323654]=30,  -- Flagellation
[323764]=99,  -- Convoke the Spirits
[325013]=99,  -- Boon of the Ascended
[370537]=3,  -- Stasis
[383334]=5,  -- Inner Grace
[384027]=2,  -- Divine Resonance
[386738]=2,  -- Divine Resonance
[387638]=3,  -- Shadowboxing Treads
[389539]=15,  -- Sentinel
[391528]=99,  -- Convoke the Spirits
[400278]=3,  -- Moonless Night
[414273]=2,  -- Hand of Divinity
[472433]=2,  -- Evangelism
[1223131]=99,  -- Strom'kar's Might
[1233181]=20,  -- Tempest Wrath
[1259790]=99,  -- Unstable Affliction
[1269312]=2,  -- Phalanx
[1271387]=6,  -- Masterwork
[1271466]=6,  -- Reflection of Radiance
})
