-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- GENERATED by tools/gen_cc_breakers.py - do not edit by hand.
-- Client data build 12.1.0.69875; WoW Forever 1.60.1.70245.
--
-- MECHANIC_BREAKERS[mechanicID] = { [spellID] = itemID or 0 }
-- Sourced from EffectAura 77 (mechanic immunity), whose EffectMiscValue_0 names the
-- mechanic. itemID is non-zero when an item grants the spell (press the item, not it).
-- Filtered to spells a player can learn, plus anything an item grants.
-- FOREVER_BREAKERS: the same from the WoW Forever export, plus SpellEffect 108 (dispel
-- mechanic) - its racial breakers remove the CC rather than grant immunity.

local lib = LibStub:NewLibrary("JustAC-CCBreakers", 1)
if not lib then return end

local MECHANIC_BREAKERS = {
    [1] = {  -- charmed
        [7744]=0,  -- Will of the Forsaken
        [42292]=18834,  -- PvP Trinket (item 18834)
        [49039]=0,  -- Lichborne
        [134946]=92786,  -- Supremacy of the Alliance (item 92786)
        [134956]=92787,  -- Supremacy of the Horde (item 92787)
        [336126]=181333,  -- Gladiator's Medallion (item 181333)
    },
    [2] = {  -- disoriented
        [36480]=30313,  -- Mental Protection Field (item 30313)
    },
    [5] = {  -- fleeing
        [7744]=0,  -- Will of the Forsaken
        [18499]=0,  -- Berserker Rage
        [36481]=30314,  -- Arcane Barrier (item 30314)
        [49039]=0,  -- Lichborne
        [62137]=0,  -- Avoidance
        [232043]=142166,  -- Heroic Resolve (item 142166)
        [384100]=0,  -- Berserker Shout
    },
    [7] = {  -- rooted
        [1044]=0,  -- Blessing of Freedom
        [1953]=0,  -- Blink
        [6615]=5634,  -- Free Action (item 5634)
        [9774]=4328,  -- Freedom (item 4328)
        [24364]=20008,  -- Living Free Action (item 20008)
        [89792]=0,  -- Flee
        [115008]=0,  -- Chi Torpedo
        [172160]=116925,  -- Free Action (item 116925)
        [175817]=116276,  -- Draenic Living Action Potion (item 116276)
        [342890]=183823,  -- Unhindered Passing (item 183823)
        [361137]=187965,  -- Blink (item 187965)
        [370960]=0,  -- Emerald Communion
        [421453]=0,  -- Ultimate Penitence
        [1264446]=259092,  -- Void-Tinged Free Action Potion (item 259092)
    },
    [9] = {  -- silenced
        [36480]=30313,  -- Mental Protection Field (item 30313)
        [104773]=0,  -- Unending Resolve
        [186265]=0,  -- Aspect of the Turtle
        [215769]=0,  -- Spirit of Redemption
        [363916]=0,  -- Obsidian Scales
        [437461]=0,  -- Aspect of the Turtle
        [466524]=0,  -- Metal Sheet
    },
    [10] = {  -- asleep
        [7744]=0,  -- Will of the Forsaken
        [49039]=0,  -- Lichborne
    },
    [11] = {  -- snared
        [1044]=0,  -- Blessing of Freedom
        [6615]=5634,  -- Free Action (item 5634)
        [24364]=20008,  -- Living Free Action (item 20008)
        [26571]=21756,  -- Golden Hare (item 21756)
        [36481]=30314,  -- Arcane Barrier (item 30314)
        [115008]=0,  -- Chi Torpedo
        [172160]=116925,  -- Free Action (item 116925)
        [175817]=116276,  -- Draenic Living Action Potion (item 116276)
        [342890]=183823,  -- Unhindered Passing (item 183823)
        [370960]=0,  -- Emerald Communion
        [1264446]=259092,  -- Void-Tinged Free Action Potion (item 259092)
    },
    [12] = {  -- stunned
        [1953]=0,  -- Blink
        [6615]=5634,  -- Free Action (item 5634)
        [24364]=20008,  -- Living Free Action (item 20008)
        [36480]=30313,  -- Mental Protection Field (item 30313)
        [48792]=0,  -- Icebound Fortitude
        [59752]=0,  -- Will to Survive
        [89792]=0,  -- Flee
        [172160]=116925,  -- Free Action (item 116925)
        [175817]=116276,  -- Draenic Living Action Potion (item 116276)
        [342890]=183823,  -- Unhindered Passing (item 183823)
        [361137]=187965,  -- Blink (item 187965)
        [436358]=0,  -- Demolish
        [1264446]=259092,  -- Void-Tinged Free Action Potion (item 259092)
    },
    [13] = {  -- frozen
        [70797]=49944,  -- Belysra's Talisman (item 49944)
    },
    [14] = {  -- incapacitated
        [18499]=0,  -- Berserker Rage
        [384100]=0,  -- Berserker Shout
    },
    [17] = {  -- polymorphed
        [768]=0,  -- Cat Form
        [5487]=0,  -- Bear Form
        [24858]=0,  -- Moonkin Form
        [33891]=0,  -- Incarnation: Tree of Life
        [197625]=0,  -- Moonkin Form
        [210053]=136789,  -- Mount Form (item 136789)
    },
    [23] = {  -- turned
        [7744]=0,  -- Will of the Forsaken
        [18499]=0,  -- Berserker Rage
        [49039]=0,  -- Lichborne
        [384100]=0,  -- Berserker Shout
    },
    [24] = {  -- horrified
        [62137]=0,  -- Avoidance
    },
    [27] = {  -- dazed
        [401375]=203722,  -- Experimental Dragon Pack (item 203722)
    },
    [30] = {  -- sapped
        [18499]=0,  -- Berserker Rage
        [384100]=0,  -- Berserker Shout
    },
}

local FOREVER_BREAKERS = {
    [1] = {  -- charmed
        [7744]=0,  -- Will of the Forsaken
        [19574]=0,  -- Bestial Wrath
        [23273]=209612,  -- Immune Charm/Fear/Polymorph (item 209612)
        [23277]=209617,  -- Immune Charm/Fear/Stun (item 209617)
        [438273]=216938,  -- PvP Trinket (item 216938)
        [474386]=233728,  -- PvP Trinket (item 233728)
    },
    [2] = {  -- disoriented
        [19574]=0,  -- Bestial Wrath
    },
    [3] = {  -- disarmed
        [1178]=0,  -- Bear Form (Passive)
        [3025]=0,  -- Cat Form (Passive)
        [5421]=0,  -- Aquatic Form (Passive)
        [7219]=12639,  -- Immune to Disarm (item 12639)
        [9635]=0,  -- Dire Bear Form (Passive)
        [24905]=0,  -- Moonkin Form (Passive)
        [469348]=231042,  -- Immune to Disarm (item 231042)
        [1308917]=13213,  -- Mother's Watch (item 13213)
    },
    [5] = {  -- fleeing
        [1719]=0,  -- Recklessness
        [6346]=5713,  -- Fear Ward (item 5713)
        [7744]=0,  -- Will of the Forsaken
        [12328]=0,  -- Death Wish
        [12733]=10418,  -- Fearless (item 10418)
        [18499]=0,  -- Berserker Rage
        [19574]=0,  -- Bestial Wrath
        [22891]=18438,  -- Undo Crowd Control Rogue (item 18438)
        [23273]=209612,  -- Immune Charm/Fear/Polymorph (item 209612)
        [23274]=209618,  -- Immune Fear/Polymorph/Snare (item 209618)
        [23276]=209613,  -- Immune Fear/Polymorph/Stun (item 209613)
        [23277]=209617,  -- Immune Charm/Fear/Stun (item 209617)
        [417141]=0,  -- Berserk
        [446382]=221026,  -- Attuned to the Void (item 221026)
    },
    [7] = {  -- rooted
        [1044]=0,  -- Blessing of Freedom
        [1953]=5647,  -- Blink (item 5647)
        [5579]=209611,  -- Immune Root/Snare/Stun (item 209611)
        [6615]=5634,  -- Free Action (item 5634)
        [9774]=4328,  -- Immune Root (item 4328)
        [19574]=0,  -- Bestial Wrath
        [20589]=0,  -- Escape Artist
        [24364]=20008,  -- Living Free Action (item 20008)
        [425294]=0,  -- Dispersion
        [435895]=213349,  -- Gniodine Dispel (item 213349)
        [1291758]=273089,  -- Escape Root (item 273089)
    },
    [9] = {  -- silenced
        [437382]=215167,  -- Reinforced Willpower (item 215167)
        [1310897]=0,  -- Voice of Truth
    },
    [10] = {  -- asleep
        [7744]=0,  -- Will of the Forsaken
        [19574]=0,  -- Bestial Wrath
        [22891]=18438,  -- Undo Crowd Control Rogue (item 18438)
    },
    [11] = {  -- snared
        [1044]=0,  -- Blessing of Freedom
        [5579]=209611,  -- Immune Root/Snare/Stun (item 209611)
        [6615]=5634,  -- Free Action (item 5634)
        [19574]=0,  -- Bestial Wrath
        [20589]=0,  -- Escape Artist
        [23274]=209618,  -- Immune Fear/Polymorph/Snare (item 209618)
        [24364]=20008,  -- Living Free Action (item 20008)
        [425294]=0,  -- Dispersion
        [435895]=213349,  -- Gniodine Dispel (item 213349)
    },
    [12] = {  -- stunned
        [1953]=5647,  -- Blink (item 5647)
        [5579]=209611,  -- Immune Root/Snare/Stun (item 209611)
        [6615]=5634,  -- Free Action (item 5634)
        [19574]=0,  -- Bestial Wrath
        [23276]=209613,  -- Immune Fear/Polymorph/Stun (item 209613)
        [23277]=209617,  -- Immune Charm/Fear/Stun (item 209617)
        [24364]=20008,  -- Living Free Action (item 20008)
        [1259718]=0,  -- Will to Survive
    },
    [13] = {  -- frozen
        [19574]=0,  -- Bestial Wrath
    },
    [14] = {  -- incapacitated
        [18499]=0,  -- Berserker Rage
        [19574]=0,  -- Bestial Wrath
    },
    [17] = {  -- polymorphed
        [768]=0,  -- Cat Form
        [783]=0,  -- Travel Form
        [1066]=0,  -- Aquatic Form
        [5487]=0,  -- Bear Form
        [9634]=0,  -- Dire Bear Form
        [18805]=4381,  -- Recombobulate (item 4381)
        [19574]=0,  -- Bestial Wrath
        [22891]=18438,  -- Undo Crowd Control Rogue (item 18438)
        [23064]=18637,  -- Recombobulate (item 18637)
        [23273]=209612,  -- Immune Charm/Fear/Polymorph (item 209612)
        [23274]=209618,  -- Immune Fear/Polymorph/Snare (item 209618)
        [23276]=209613,  -- Immune Fear/Polymorph/Stun (item 209613)
        [24858]=0,  -- Moonkin Form
    },
    [24] = {  -- horrified
        [19574]=0,  -- Bestial Wrath
    },
}

local SpellDB = LibStub("JustAC-SpellDB", true)
if SpellDB and SpellDB.IsForever and SpellDB.IsForever() then MECHANIC_BREAKERS = FOREVER_BREAKERS end

--- Spells/items that free the player from `mechanic`, or nil when nothing does.
--- @param mechanic number SpellMechanic id (see CC_MECHANICS in the generator)
--- @return table|nil map of [spellID] = itemID (0 when the spell is cast directly)
function lib.GetBreakers(mechanic)
    return mechanic and MECHANIC_BREAKERS[mechanic] or nil
end
