-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- GENERATED by tools/gen_cc_breakers.py - do not edit by hand.
-- Client data build 12.1.0.69382.
--
-- MECHANIC_BREAKERS[mechanicID] = { [spellID] = itemID or 0 }
-- Sourced from EffectAura 77 (mechanic immunity), whose EffectMiscValue_0 names the
-- mechanic. itemID is non-zero when an item grants the spell (press the item, not it).
-- Filtered to spells a player can learn, plus anything an item grants.

local lib = LibStub:NewLibrary("JustAC-CCBreakers", 1)
if not lib then return end

local MECHANIC_BREAKERS = {
    [1] = {  -- charmed
        [7744]=0,  -- Will of the Forsaken
        [42292]=18834,  -- PvP Trinket (item 18834)
        [49039]=0,  -- Lichborne
        [134946]=92786,  -- Supremacy of the Alliance (item 92786)
        [134956]=92787,  -- Supremacy of the Horde (item 92787)
        [336126]=181333,  -- Gladiator's Medallion (item 181333)
    },
    [2] = {  -- disoriented
        [36480]=30313,  -- Mental Protection Field (item 30313)
    },
    [5] = {  -- fleeing
        [7744]=0,  -- Will of the Forsaken
        [18499]=0,  -- Berserker Rage
        [36481]=30314,  -- Arcane Barrier (item 30314)
        [49039]=0,  -- Lichborne
        [62137]=0,  -- Avoidance
        [232043]=142166,  -- Heroic Resolve (item 142166)
        [384100]=0,  -- Berserker Shout
    },
    [7] = {  -- rooted
        [1044]=0,  -- Blessing of Freedom
        [1953]=0,  -- Blink
        [6615]=5634,  -- Free Action (item 5634)
        [9774]=4328,  -- Freedom (item 4328)
        [24364]=20008,  -- Living Free Action (item 20008)
        [89792]=0,  -- Flee
        [115008]=0,  -- Chi Torpedo
        [172160]=116925,  -- Free Action (item 116925)
        [175817]=116276,  -- Draenic Living Action Potion (item 116276)
        [342890]=183823,  -- Unhindered Passing (item 183823)
        [361137]=187965,  -- Blink (item 187965)
        [370960]=0,  -- Emerald Communion
        [421453]=0,  -- Ultimate Penitence
        [1264446]=259092,  -- Void-Tinged Free Action Potion (item 259092)
    },
    [9] = {  -- silenced
        [36480]=30313,  -- Mental Protection Field (item 30313)
        [104773]=0,  -- Unending Resolve
        [186265]=0,  -- Aspect of the Turtle
        [215769]=0,  -- Spirit of Redemption
        [363916]=0,  -- Obsidian Scales
        [437461]=0,  -- Aspect of the Turtle
        [466524]=0,  -- Metal Sheet
    },
    [10] = {  -- asleep
        [7744]=0,  -- Will of the Forsaken
        [49039]=0,  -- Lichborne
    },
    [11] = {  -- snared
        [1044]=0,  -- Blessing of Freedom
        [6615]=5634,  -- Free Action (item 5634)
        [24364]=20008,  -- Living Free Action (item 20008)
        [26571]=21756,  -- Golden Hare (item 21756)
        [36481]=30314,  -- Arcane Barrier (item 30314)
        [115008]=0,  -- Chi Torpedo
        [172160]=116925,  -- Free Action (item 116925)
        [175817]=116276,  -- Draenic Living Action Potion (item 116276)
        [342890]=183823,  -- Unhindered Passing (item 183823)
        [370960]=0,  -- Emerald Communion
        [1264446]=259092,  -- Void-Tinged Free Action Potion (item 259092)
    },
    [12] = {  -- stunned
        [1953]=0,  -- Blink
        [6615]=5634,  -- Free Action (item 5634)
        [24364]=20008,  -- Living Free Action (item 20008)
        [36480]=30313,  -- Mental Protection Field (item 30313)
        [48792]=0,  -- Icebound Fortitude
        [59752]=0,  -- Will to Survive
        [89792]=0,  -- Flee
        [172160]=116925,  -- Free Action (item 116925)
        [175817]=116276,  -- Draenic Living Action Potion (item 116276)
        [342890]=183823,  -- Unhindered Passing (item 183823)
        [361137]=187965,  -- Blink (item 187965)
        [436358]=0,  -- Demolish
        [1264446]=259092,  -- Void-Tinged Free Action Potion (item 259092)
    },
    [13] = {  -- frozen
        [70797]=49944,  -- Belysra's Talisman (item 49944)
    },
    [14] = {  -- incapacitated
        [18499]=0,  -- Berserker Rage
        [384100]=0,  -- Berserker Shout
    },
    [17] = {  -- polymorphed
        [768]=0,  -- Cat Form
        [5487]=0,  -- Bear Form
        [24858]=0,  -- Moonkin Form
        [33891]=0,  -- Incarnation: Tree of Life
        [197625]=0,  -- Moonkin Form
        [210053]=136789,  -- Mount Form (item 136789)
    },
    [23] = {  -- turned
        [7744]=0,  -- Will of the Forsaken
        [18499]=0,  -- Berserker Rage
        [49039]=0,  -- Lichborne
        [384100]=0,  -- Berserker Shout
    },
    [24] = {  -- horrified
        [62137]=0,  -- Avoidance
    },
    [27] = {  -- dazed
        [401375]=203722,  -- Experimental Dragon Pack (item 203722)
    },
    [30] = {  -- sapped
        [18499]=0,  -- Berserker Rage
        [384100]=0,  -- Berserker Shout
    },
}

--- Spells/items that free the player from `mechanic`, or nil when nothing does.
--- @param mechanic number SpellMechanic id (see CC_MECHANICS in the generator)
--- @return table|nil map of [spellID] = itemID (0 when the spell is cast directly)
function lib.GetBreakers(mechanic)
    return mechanic and MECHANIC_BREAKERS[mechanic] or nil
end

lib.MECHANIC_BREAKERS = MECHANIC_BREAKERS
