-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: WoW Forever consumables - pre-pull buffs (flasks + elixirs, scrolls, Well Fed food,
-- weapon stones / oils), eating auras, out-of-combat recovery (food, drink, bandages) and
-- healing potions.
--
-- GENERATED by tools/gen_forever_consumables.py from the Forever client data - do not
-- hand-edit. Retail's Data/PrecombatBuffs.lua and Data/HealingItems.lua skip on Forever;
-- this file skips on retail.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not (SpellDB and SpellDB.IsForever and SpellDB.IsForever()) then return end

SpellDB.RegisterPrecombatBuffs({
    flask = {
        { id = 13513, buff = 17629, stat = "armor" },  -- Flask of Chromatic Resistance
        { id = 274273, buff = 1293740, stat = "stamina" },  -- Flask of Natural Accuracy
        { id = 274274, buff = 1293741, stat = "stamina" },  -- Flask of Natural Aggression
        { id = 274275, buff = 1293742, stat = "stamina" },  -- Flask of Natural Precision
        { id = 274276, buff = 1293743, stat = "stamina" },  -- Flask of Natural Swiftness
        { id = 13512, buff = 17628, stat = "spellpower" },  -- Flask of Supreme Power
        { id = 13510, buff = 17626, stat = "stamina" },  -- Flask of the Titans
        { id = 13454, buff = 17539, stat = "spellpower" },  -- Greater Arcane Elixir
        { id = 13452, buff = 17538, stat = "agility" },  -- Elixir of the Mongoose
        { id = 13453, buff = 17537, stat = "strength" },  -- Elixir of Brute Force
        { id = 250328, buff = 1250918, stat = "agility" },  -- Elixir of Cunning
        { id = 250350, buff = 1250985, stat = "strength" },  -- Elixir of Ferocity
        { id = 250335, buff = 1250931, stat = "stamina" },  -- Elixir of Greater Fortitude
        { id = 250347, buff = 1250979, stat = "spirit" },  -- Elixir of Greater Spirit
        { id = 250343, buff = 1250972, stat = "spellpower" },  -- Elixir of Nature Power
        { id = 250338, buff = 1250941, stat = "spirit" },  -- Elixir of Sages
        { id = 250351, buff = 1250986, stat = "strength" },  -- Elixir of the Grizzly
        { id = 250337, buff = 1250940, stat = "intellect" },  -- Elixir of the Owl
        { id = 250329, buff = 1250920, stat = "stamina" },  -- Elixir of the Phalanx
        { id = 250348, buff = 1250981, stat = "spirit" },  -- Elixir of the Whale
        { id = 250333, buff = 1250926, stat = "healing" },  -- Greater Cleric's Elixir
        { id = 13445, buff = 11348, stat = "armor" },  -- Elixir of Greater Defense
        { id = 21546, buff = 1310077, stat = "spellpower" },  -- Elixir of Holy Power
        { id = 9264, buff = 11474, stat = "spellpower" },  -- Elixir of Shadow Power
        { id = 12820, buff = 17038, stat = "attackpower" },  -- Winterfall Firewater
        { id = 9187, buff = 11334, stat = "agility" },  -- Elixir of Greater Agility
        { id = 9206, buff = 11405, stat = "strength" },  -- Elixir of Greater Strength
        { id = 9088, buff = 11371, stat = "armor" },  -- Gift of Arthas
        { id = 9155, buff = 11390, stat = "spellpower" },  -- Arcane Elixir
        { id = 9179, buff = 11396, stat = "intellect" },  -- Elixir of Greater Intellect
        { id = 250332, buff = 1250925, stat = "healing" },  -- Cleric's Elixir
        { id = 246948, buff = 17038, stat = "attackpower" },  -- Distilled Firewater
        { id = 250334, buff = 1250928, stat = "stamina" },  -- Elixir of Fortitude
        { id = 250354, buff = 1250989, stat = "intellect" },  -- Elixir of Intellect
        { id = 250346, buff = 1250978, stat = "spirit" },  -- Elixir of Spirit
        { id = 250349, buff = 1250984, stat = "strength" },  -- Elixir of Strength
        { id = 13447, buff = 17535, stat = "intellect" },  -- Elixir of the Sages
        { id = 8951, buff = 11349, stat = "armor" },  -- Elixir of Defense
        { id = 17708, buff = 21920, stat = "spellpower" },  -- Elixir of Frost Power
        { id = 217398, buff = 439959, stat = "spellpower" },  -- Lesser Arcane Elixir
        { id = 8949, buff = 11328, stat = "agility" },  -- Elixir of Agility
        { id = 3825, buff = 3593, stat = "stamina" },  -- Elixir of Lesser Fortitude
        { id = 3391, buff = 3164, stat = "strength" },  -- Elixir of Ogre Strength
        { id = 6373, buff = 7844, stat = "spellpower" },  -- Elixir of Fire Power
        { id = 3390, buff = 3160, stat = "agility" },  -- Elixir of Lesser Agility
        { id = 3389, buff = 3220, stat = "armor" },  -- Elixir of Lesser Defense
        { id = 250353, buff = 1250988, stat = "intellect" },  -- Elixir of Lesser Intellect
        { id = 250345, buff = 1250976, stat = "spirit" },  -- Elixir of Lesser Spirit
        { id = 250342, buff = 1250971, stat = "spellpower" },  -- Lesser Arcane Elixir
        { id = 250331, buff = 1250924, stat = "healing" },  -- Lesser Cleric's Elixir
        { id = 3383, buff = 3166, stat = "intellect" },  -- Elixir of Wisdom
        { id = 2457, buff = 2374, stat = "agility" },  -- Elixir of Minor Agility
        { id = 2458, buff = 2378, stat = "stamina" },  -- Elixir of Minor Fortitude
        { id = 5997, buff = 673, stat = "armor" },  -- Elixir of Minor Defense
        { id = 247755, buff = 1245249, stat = "spellpower" },  -- Elixir of Minor Force
        { id = 250344, buff = 1250974, stat = "spirit" },  -- Elixir of Minor Spirit
        { id = 2454, buff = 2367, stat = "strength" },  -- Elixir of Minor Strength
        { id = 247754, buff = 1245244, stat = "spellpower" },  -- Minor Arcane Elixir
        { id = 250330, buff = 1250922, stat = "healing" },  -- Minor Cleric's Elixir
    },
    scroll = {
        { id = 10309, buff = 12174, stat = "agility" },  -- Scroll of Agility IV
        { id = 10310, buff = 12179, stat = "strength" },  -- Scroll of Strength IV
        { id = 10308, buff = 12176, stat = "intellect" },  -- Scroll of Intellect IV
        { id = 10307, buff = 12178, stat = "stamina" },  -- Scroll of Stamina IV
        { id = 10305, buff = 12175, stat = "armor" },  -- Scroll of Protection IV
        { id = 10306, buff = 12177, stat = "spirit" },  -- Scroll of Spirit IV
        { id = 4425, buff = 8117, stat = "agility" },  -- Scroll of Agility III
        { id = 4426, buff = 8120, stat = "strength" },  -- Scroll of Strength III
        { id = 4419, buff = 8098, stat = "intellect" },  -- Scroll of Intellect III
        { id = 4422, buff = 8101, stat = "stamina" },  -- Scroll of Stamina III
        { id = 277493, buff = 1302303, stat = "intellect" },  -- Scroll of Cat Familiar
        { id = 4421, buff = 8095, stat = "armor" },  -- Scroll of Protection III
        { id = 4424, buff = 8114, stat = "spirit" },  -- Scroll of Spirit III
        { id = 1477, buff = 8116, stat = "agility" },  -- Scroll of Agility II
        { id = 2289, buff = 8119, stat = "strength" },  -- Scroll of Strength II
        { id = 2290, buff = 8097, stat = "intellect" },  -- Scroll of Intellect II
        { id = 1711, buff = 8100, stat = "stamina" },  -- Scroll of Stamina II
        { id = 277483, buff = 1302285, stat = "intellect" },  -- Scroll of Frog Familiar
        { id = 1478, buff = 8094, stat = "armor" },  -- Scroll of Protection II
        { id = 1712, buff = 8113, stat = "spirit" },  -- Scroll of Spirit II
        { id = 3012, buff = 8115, stat = "agility" },  -- Scroll of Agility
        { id = 954, buff = 8118, stat = "strength" },  -- Scroll of Strength
        { id = 955, buff = 8096, stat = "intellect" },  -- Scroll of Intellect
        { id = 275069, buff = 1296202, stat = "intellect" },  -- Scroll of Rat Familiar
        { id = 1180, buff = 8099, stat = "stamina" },  -- Scroll of Stamina
        { id = 3013, buff = 8091, stat = "armor" },  -- Scroll of Protection
        { id = 1181, buff = 8112, stat = "spirit" },  -- Scroll of Spirit
    },
    food = {
        { id = 238638, buff = 1225779, stat = "agility" },  -- Filet o' Flank
        { id = 13935, buff = 1249520, stat = "spellpower" },  -- Baked Salmon
        { id = 250067, buff = 1248421, stat = "intellect" },  -- Bat Hachee
        { id = 250070, buff = 1248422, stat = "strength" },  -- Bear Bruscitti
        { id = 13810, buff = 18125, stat = "strength" },  -- Blessed Sunfruit
        { id = 21023, buff = 25661, stat = "stamina" },  -- Dirge's Kickin' Chimaerok Chops
        { id = 250069, buff = 1248420, stat = "agility" },  -- Flank au Poivre
        { id = 13933, buff = 1249520, stat = "spellpower" },  -- Lobster Stew
        { id = 13934, buff = 1249519, stat = "attackpower" },  -- Mightfish Steak
        { id = 250075, buff = 1248421, stat = "intellect" },  -- Prehistoric Pulled Raptor
        { id = 249870, buff = 1249927, stat = "healing" },  -- Sage's Tea
        { id = 21217, buff = 1249520, stat = "spellpower" },  -- Sagefish Delight
        { id = 250068, buff = 1248406, stat = "stamina" },  -- Savory Turtle Stew
        { id = 20452, buff = 1248422, stat = "strength" },  -- Smoked Desert Dumplings
        { id = 250066, buff = 1248421, stat = "intellect" },  -- Soaring Pamplona
        { id = 8957, buff = 1249521, stat = "intellect" },  -- Spinefin Halibut
        { id = 250071, buff = 1248422, stat = "strength" },  -- Steaming Stag Steak
        { id = 250072, buff = 1248420, stat = "agility" },  -- Swiftstrike Steak
        { id = 249876, buff = 1249926, stat = "spirit" },  -- Wicked Smoothie
        { id = 16971, buff = 19710, stat = "stamina" },  -- Clamlette Surprise
        { id = 13927, buff = 1249519, stat = "attackpower" },  -- Cooked Glossy Mightfish
        { id = 13930, buff = 1249521, stat = "intellect" },  -- Filet of Redgill
        { id = 12212, buff = 1248420, stat = "agility" },  -- Jungle Stew
        { id = 12218, buff = 1248406, stat = "stamina" },  -- Monster Omelet
        { id = 13931, buff = 1249520, stat = "spellpower" },  -- Nightfin Soup
        { id = 13932, buff = 1249519, stat = "attackpower" },  -- Poached Sunscale Salmon
        { id = 250076, buff = 1248421, stat = "intellect" },  -- Raptor Rouladen
        { id = 18254, buff = 1248421, stat = "intellect" },  -- Runn Tum Tuber Surprise
        { id = 250065, buff = 1248422, stat = "strength" },  -- Savory Stag Sliders
        { id = 249875, buff = 1249926, stat = "spirit" },  -- Spicy Smoothie
        { id = 17222, buff = 1248406, stat = "stamina" },  -- Spider Sausage
        { id = 6887, buff = 1249520, stat = "spellpower" },  -- Spotted Yellowtail
        { id = 249869, buff = 1249927, stat = "healing" },  -- Sunny Tea
        { id = 18045, buff = 1248420, stat = "agility" },  -- Tender Wolf Steak
        { id = 4457, buff = 1248421, stat = "intellect" },  -- Barbecued Buzzard Wing
        { id = 250074, buff = 1248422, stat = "strength" },  -- Bear Brisket
        { id = 274971, buff = 1249520, stat = "spellpower" },  -- Briny Seafood Stew
        { id = 249874, buff = 1249926, stat = "spirit" },  -- Calcified Smoothie
        { id = 6038, buff = 1248406, stat = "stamina" },  -- Giant Clam Scorcho
        { id = 250078, buff = 1248406, stat = "stamina" },  -- Giant Scrambled Eggs
        { id = 20074, buff = 1248420, stat = "agility" },  -- Heavy Crocolisk Stew
        { id = 12215, buff = 1248406, stat = "stamina" },  -- Heavy Kodo Stew
        { id = 13851, buff = 1248420, stat = "agility" },  -- Hot Wolf Ribs
        { id = 8364, buff = 1249519, stat = "attackpower" },  -- Mithril Head Trout
        { id = 274976, buff = 1248422, stat = "strength" },  -- Plain Ol' Paletusk
        { id = 250073, buff = 1248421, stat = "intellect" },  -- Raging Raptor Ribs
        { id = 4594, buff = 1249521, stat = "intellect" },  -- Rockscale Cod
        { id = 12216, buff = 1248421, stat = "intellect" },  -- Spiced Chili Crab
        { id = 3728, buff = 1248420, stat = "agility" },  -- Tasty Lion Steak
        { id = 249868, buff = 1249927, stat = "healing" },  -- Triage Tea
        { id = 4593, buff = 1249521, stat = "intellect" },  -- Bristle Whisker Catfish
        { id = 3664, buff = 1248420, stat = "agility" },  -- Crocolisk Gumbo
        { id = 3665, buff = 1248406, stat = "stamina" },  -- Curiously Tasty Omelet
        { id = 5527, buff = 19708, stat = "stamina" },  -- Goblin Deviled Clams
        { id = 3666, buff = 1248406, stat = "stamina" },  -- Gooey Spider Cake
        { id = 3727, buff = 1248420, stat = "agility" },  -- Hot Lion Chops
        { id = 5480, buff = 1248422, stat = "strength" },  -- Lean Venison
        { id = 12209, buff = 1248420, stat = "agility" },  -- Lean Wolf Steak
        { id = 249873, buff = 1249926, stat = "spirit" },  -- Mrrggl Smrrthle
        { id = 12214, buff = 1248406, stat = "stamina" },  -- Mystery Stew
        { id = 12210, buff = 1248421, stat = "intellect" },  -- Roast Raptor
        { id = 249867, buff = 1249927, stat = "healing" },  -- Root Tea
        { id = 1017, buff = 1248420, stat = "agility" },  -- Seasoned Wolf Kabob
        { id = 3729, buff = 1248406, stat = "stamina" },  -- Soothing Turtle Bisque
        { id = 2685, buff = 1248422, stat = "strength" },  -- Succulent Pork Ribs
        { id = 21072, buff = 1249520, stat = "spellpower" },  -- Smoked Sagefish
        { id = 3726, buff = 1248422, stat = "strength" },  -- Big Bear Steak
        { id = 3220, buff = 1248422, stat = "strength" },  -- Blood Sausage
        { id = 250080, buff = 1248406, stat = "stamina" },  -- Breakfast Omelette
        { id = 12213, buff = 1248406, stat = "stamina" },  -- Carrion Surprise
        { id = 2684, buff = 1248420, stat = "agility" },  -- Coyote Steak
        { id = 2683, buff = 1248421, stat = "intellect" },  -- Crab Cake
        { id = 5479, buff = 1248406, stat = "stamina" },  -- Crispy Lizard Tail
        { id = 3662, buff = 1248420, stat = "agility" },  -- Crocolisk Steak
        { id = 2687, buff = 1248422, stat = "strength" },  -- Dry Pork Ribs
        { id = 268912, buff = 1248406, stat = "stamina" },  -- Expiring Crab Cake
        { id = 268913, buff = 1248406, stat = "stamina" },  -- Expiring Crocolisk Steak
        { id = 5476, buff = 1249521, stat = "intellect" },  -- Fillet of Frenzy
        { id = 724, buff = 1248422, stat = "strength" },  -- Goretusk Liver Pie
        { id = 6316, buff = 1249521, stat = "intellect" },  -- Loch Frenzy Delight
        { id = 4592, buff = 1249519, stat = "attackpower" },  -- Longjaw Mud Snapper
        { id = 263512, buff = 1248421, stat = "intellect" },  -- Pincer Bites
        { id = 5095, buff = 1249520, stat = "spellpower" },  -- Rainbow Fin Albacore
        { id = 1082, buff = 1248421, stat = "intellect" },  -- Redridge Goulash
        { id = 249866, buff = 1249927, stat = "healing" },  -- Royal Tea
        { id = 263509, buff = 1248406, stat = "stamina" },  -- Skywall Souffle
        { id = 249872, buff = 1249926, stat = "spirit" },  -- Slimy Smoothie
        { id = 250077, buff = 1248421, stat = "intellect" },  -- Twice-Spiced Raptor Slice
        { id = 2888, buff = 1248422, stat = "strength" },  -- Beer Basted Boar Ribs
        { id = 6290, buff = 1249519, stat = "attackpower" },  -- Brilliant Smallfish
        { id = 2682, buff = 1248421, stat = "intellect" },  -- Cooked Crab Claw
        { id = 12224, buff = 1248421, stat = "intellect" },  -- Crispy Bat Wing
        { id = 17198, buff = 19705, stat = "stamina" },  -- Egg Nog
        { id = 17197, buff = 19705, stat = "stamina" },  -- Gingerbread Cookie
        { id = 6888, buff = 1248406, stat = "stamina" },  -- Herb Baked Egg
        { id = 5472, buff = 1248406, stat = "stamina" },  -- Kaldorei Spider Kabob
        { id = 3663, buff = 1248406, stat = "stamina" },  -- Murloc Fin Soup
        { id = 2681, buff = 1248422, stat = "strength" },  -- Roasted Boar Meat
        { id = 5474, buff = 1248406, stat = "stamina" },  -- Roasted Kodo Meat
        { id = 787, buff = 1249519, stat = "attackpower" },  -- Slitherskin Mackerel
        { id = 6890, buff = 1248422, stat = "strength" },  -- Smoked Bear Meat
        { id = 2680, buff = 1248420, stat = "agility" },  -- Spiced Wolf Meat
        { id = 5477, buff = 1248421, stat = "intellect" },  -- Strider Stew
        { id = 250079, buff = 1248421, stat = "intellect" },  -- Tasty Raptor Bites
        { id = 11584, buff = 19705, stat = "stamina" },  -- Cactus Apple Surprise
        { id = 7807, buff = 19705, stat = "stamina" },  -- Candy Bar
        { id = 7808, buff = 19705, stat = "stamina" },  -- Chocolate Square
        { id = 7806, buff = 19705, stat = "stamina" },  -- Lollipop
        { id = 249865, buff = 1249927, stat = "healing" },  -- Peace Tea
        { id = 249871, buff = 1249926, stat = "spirit" },  -- Venomous Smoothie
        { id = 21151, buff = 25804, stat = "stamina" },  -- Rumsey Rum Black Label
        { id = 21114, buff = 25722, stat = "stamina" },  -- Rumsey Rum Dark
        { id = 20709, buff = 25037, stat = "stamina" },  -- Rumsey Rum Light
        { id = 5265, buff = 5909, stat = "spirit" },  -- Watered-down Beer
    },
    weaponEnchant = {
        { id = 217347, buff = 439465, stat = "physical", wmask = 173555 },  -- Atrophic Poison
        { id = 18262, buff = 22756, stat = "physical", wmask = 42483 },  -- Elemental Sharpening Stone
        { id = 217346, buff = 439464, stat = "physical", wmask = 173555 },  -- Numbing Poison
        { id = 234444, buff = 1214171, stat = "physical", wmask = 173555 },  -- Occult Poison II
        { id = 217345, buff = 439462, stat = "physical", wmask = 173555 },  -- Sebacious Poison
        { id = 23123, buff = 28898, stat = "caster" },  -- Blessed Wizard Oil
        { id = 20748, buff = 25123, stat = "caster" },  -- Brilliant Mana Oil
        { id = 20749, buff = 25122, stat = "caster" },  -- Brilliant Wizard Oil
        { id = 23122, buff = 28891, stat = "physical", wmask = 1097203 },  -- Consecrated Sharpening Stone
        { id = 226374, buff = 458821, stat = "physical", wmask = 173555 },  -- Occult Poison I
        { id = 20750, buff = 25121, stat = "caster" },  -- Wizard Oil
        { id = 12404, buff = 16138, stat = "physical", wmask = 33219 },  -- Dense Sharpening Stone
        { id = 12643, buff = 16622, stat = "physical", wmask = 9264 },  -- Dense Weightstone
        { id = 3829, buff = 3595, stat = "caster", wmask = 173555 },  -- Frost Oil
        { id = 7964, buff = 9900, stat = "physical", wmask = 33219 },  -- Solid Sharpening Stone
        { id = 7965, buff = 9903, stat = "physical", wmask = 9264 },  -- Solid Weightstone
        { id = 3824, buff = 3594, stat = "caster", wmask = 173555 },  -- Shadow Oil
        { id = 6532, buff = 8090, stat = "physical", wmask = 1048576 },  -- Bright Baubles
        { id = 7307, buff = 9092, stat = "physical", wmask = 1048576 },  -- Flesh Eating Worm
        { id = 20745, buff = 25118, stat = "caster" },  -- Minor Mana Oil
        { id = 2871, buff = 2830, stat = "physical", wmask = 33219 },  -- Heavy Sharpening Stone
        { id = 3241, buff = 3114, stat = "physical", wmask = 9264 },  -- Heavy Weightstone
        { id = 6811, buff = 8532, stat = "physical", wmask = 1048576 },  -- Aquadynamic Fish Lens
        { id = 6530, buff = 8088, stat = "physical", wmask = 1048576 },  -- Nightcrawlers
        { id = 202316, buff = 398608, stat = "physical", wmask = 173555 },  -- Runecarving Test - Crippling Poison
        { id = 2863, buff = 2829, stat = "physical", wmask = 33219 },  -- Coarse Sharpening Stone
        { id = 3240, buff = 3113, stat = "physical", wmask = 9264 },  -- Coarse Weightstone
        { id = 20744, buff = 25117, stat = "caster" },  -- Minor Wizard Oil
        { id = 268880, buff = 8087, stat = "physical", wmask = 1048576 },  -- "Secret" Bait
        { id = 6529, buff = 8087, stat = "physical", wmask = 1048576 },  -- Shiny Bauble
        { id = 2862, buff = 2828, stat = "physical", wmask = 33219 },  -- Rough Sharpening Stone
        { id = 3239, buff = 3112, stat = "physical", wmask = 9264 },  -- Rough Weightstone
    },
})
SpellDB.RegisterEatingAuras({
    430, 431, 432, 433, 434, 435, 833, 1127, 1129, 1131, 1133, 1135,
    1137, 2639, 5004, 5006, 5007, 6410, 7737, 10256, 18124, 21149, 22734, 24005,
    24869, 25660, 25695, 25696, 25990, 26260, 26261, 26401, 26402, 29008, 29055, 29073,
    468767, 1225771, 1269354, 1312719,
})
-- Recovery: amount = health / mana one use restores; best owned and usable wins.
SpellDB.RegisterRecoveryItems({
    food = {
        { id = 19301, amount = 22050, level = 51 },  -- Alterac Manna Biscuit
        { id = 262433, amount = 22050, level = 0 },  -- Ketharas' Hyjal Stew
        { id = 22895, amount = 15900, level = 55 },  -- Conjured Cinnamon Roll
        { id = 21023, amount = 12750, level = 45, wellfed = true },  -- Dirge's Kickin' Chimaerok Chops
        { id = 20031, amount = 12750, level = 55 },  -- Essence Mango
        { id = 238638, amount = 12750, level = 55, wellfed = true },  -- Filet o' Flank
        { id = 8932, amount = 10740, level = 45 },  -- Alterac Swiss
        { id = 13935, amount = 10740, level = 45, wellfed = true },  -- Baked Salmon
        { id = 250067, amount = 10740, level = 45, wellfed = true },  -- Bat Hachee
        { id = 250070, amount = 10740, level = 45, wellfed = true },  -- Bear Bruscitti
        { id = 21031, amount = 10740, level = 45 },  -- Cabbage Kimchi
        { id = 278122, amount = 10740, level = 45 },  -- Carrot Salad
        { id = 250081, amount = 10740, level = 45 },  -- Clam Linguine
        { id = 8076, amount = 10740, level = 45 },  -- Conjured Sweet Roll
        { id = 19225, amount = 10740, level = 45 },  -- Deep Fried Candybar
        { id = 8953, amount = 10740, level = 45 },  -- Deep Fried Plantains
        { id = 8948, amount = 10740, level = 45 },  -- Dried King Bolete
        { id = 13724, amount = 10740, level = 45 },  -- Enriched Manna Biscuit
        { id = 250069, amount = 10740, level = 45, wellfed = true },  -- Flank au Poivre
        { id = 23160, amount = 10740, level = 45 },  -- Friendship Bread
        { id = 13928, amount = 10740, level = 35 },  -- Grilled Squid
        { id = 11444, amount = 10740, level = 45 },  -- Grim Guzzler Boar
        { id = 8950, amount = 10740, level = 45 },  -- Homemade Cherry Pie
        { id = 13929, amount = 10740, level = 35 },  -- Hot Smoked Bass
        { id = 13933, amount = 10740, level = 45, wellfed = true },  -- Lobster Stew
        { id = 13934, amount = 10740, level = 45, wellfed = true },  -- Mightfish Steak
        { id = 11415, amount = 10740, level = 45 },  -- Mixed Berries
        { id = 13932, amount = 10740, level = 35, wellfed = true },  -- Poached Sunscale Salmon
        { id = 250075, amount = 10740, level = 45, wellfed = true },  -- Prehistoric Pulled Raptor
        { id = 21033, amount = 10740, level = 45 },  -- Radish Kimchi
        { id = 8952, amount = 10740, level = 45 },  -- Roasted Quail
        { id = 260627, amount = 10740, level = 45 },  -- Savory Shen'dralar Steak
        { id = 250068, amount = 10740, level = 45, wellfed = true },  -- Savory Turtle Stew
        { id = 16171, amount = 10740, level = 45 },  -- Shinsollo
        { id = 20452, amount = 10740, level = 45, wellfed = true },  -- Smoked Desert Dumplings
        { id = 250066, amount = 10740, level = 45, wellfed = true },  -- Soaring Pamplona
        { id = 250071, amount = 10740, level = 45, wellfed = true },  -- Steaming Stag Steak
        { id = 260628, amount = 10740, level = 45 },  -- Stuffed Pumpkin
        { id = 267341, amount = 10740, level = 55 },  -- Sweetpaw Jam
        { id = 250072, amount = 10740, level = 45, wellfed = true },  -- Swiftstrike Steak
        { id = 12763, amount = 10740, level = 45 },  -- Un'Goro Etherfruit
        { id = 22324, amount = 10740, level = 45 },  -- Winter Kimchi
        { id = 13810, amount = 9666, level = 45, wellfed = true },  -- Blessed Sunfruit
        { id = 18635, amount = 6960, level = 35 },  -- Bellara's Nutterbar
        { id = 13546, amount = 6960, level = 25 },  -- Bloodbelly Fish
        { id = 16971, amount = 6960, level = 40, wellfed = true },  -- Clamlette Surprise
        { id = 8075, amount = 6960, level = 35 },  -- Conjured Sourdough
        { id = 13927, amount = 6960, level = 35, wellfed = true },  -- Cooked Glossy Mightfish
        { id = 19306, amount = 6960, level = 35 },  -- Crunchy Frog
        { id = 4599, amount = 6960, level = 35 },  -- Cured Ham Steak
        { id = 21030, amount = 6960, level = 35 },  -- Darnassus Kimchi Pie
        { id = 13930, amount = 6960, level = 35, wellfed = true },  -- Filet of Redgill
        { id = 3927, amount = 6960, level = 35 },  -- Fine Aged Cheddar
        { id = 260625, amount = 6960, level = 35 },  -- Garnished Rice Cake
        { id = 9681, amount = 6960, level = 35 },  -- Grilled King Crawler Legs
        { id = 16168, amount = 6960, level = 35 },  -- Heaven Peach
        { id = 249796, amount = 6960, level = 45 },  -- Hyjal Berries
        { id = 12212, amount = 6960, level = 35, wellfed = true },  -- Jungle Stew
        { id = 13893, amount = 6960, level = 45 },  -- Large Raw Mightfish
        { id = 12218, amount = 6960, level = 35, wellfed = true },  -- Monster Omelet
        { id = 4602, amount = 6960, level = 35 },  -- Moon Harvest Pumpkin
        { id = 13931, amount = 6960, level = 35, wellfed = true },  -- Nightfin Soup
        { id = 286152, amount = 6960, level = 35 },  -- Plated Armorfish
        { id = 260624, amount = 6960, level = 35 },  -- Pristine Peach
        { id = 250076, amount = 6960, level = 35, wellfed = true },  -- Raptor Rouladen
        { id = 4608, amount = 6960, level = 35 },  -- Raw Black Truffle
        { id = 18255, amount = 6960, level = 45 },  -- Runn Tum Tuber
        { id = 18254, amount = 6960, level = 35, wellfed = true },  -- Runn Tum Tuber Surprise
        { id = 250065, amount = 6960, level = 35, wellfed = true },  -- Savory Stag Sliders
        { id = 4601, amount = 6960, level = 35 },  -- Soft Banana Bread
        { id = 17408, amount = 6960, level = 35 },  -- Spicy Beefstick
        { id = 17222, amount = 6960, level = 35, wellfed = true },  -- Spider Sausage
        { id = 8957, amount = 6960, level = 45, wellfed = true },  -- Spinefin Halibut
        { id = 6887, amount = 6960, level = 35, wellfed = true },  -- Spotted Yellowtail
        { id = 21552, amount = 6960, level = 35 },  -- Striped Yellowtail
        { id = 18045, amount = 6960, level = 35, wellfed = true },  -- Tender Wolf Steak
        { id = 16766, amount = 6960, level = 35 },  -- Undermine Clam Chowder
        { id = 4457, amount = 4374, level = 25, wellfed = true },  -- Barbecued Buzzard Wing
        { id = 250074, amount = 4374, level = 25, wellfed = true },  -- Bear Brisket
        { id = 274971, amount = 4374, level = 25, wellfed = true },  -- Briny Seafood Stew
        { id = 260623, amount = 4374, level = 25 },  -- Candied Fruit Sampler
        { id = 1487, amount = 4374, level = 25 },  -- Conjured Pumpernickel
        { id = 4607, amount = 4374, level = 25 },  -- Delicious Cave Mold
        { id = 6807, amount = 4374, level = 0 },  -- Frog Leg Stew
        { id = 278120, amount = 4374, level = 25 },  -- Fruit Platter
        { id = 6038, amount = 4374, level = 25, wellfed = true },  -- Giant Clam Scorcho
        { id = 250078, amount = 4374, level = 25, wellfed = true },  -- Giant Scrambled Eggs
        { id = 4539, amount = 4374, level = 25 },  -- Goldenbark Apple
        { id = 17407, amount = 4374, level = 25 },  -- Graccu's Homemade Meat Pie
        { id = 20074, amount = 4374, level = 25, wellfed = true },  -- Heavy Crocolisk Stew
        { id = 12215, amount = 4374, level = 25, wellfed = true },  -- Heavy Kodo Stew
        { id = 13851, amount = 4374, level = 25, wellfed = true },  -- Hot Wolf Ribs
        { id = 8364, amount = 4374, level = 25, wellfed = true },  -- Mithril Head Trout
        { id = 18632, amount = 4374, level = 25 },  -- Moonbrook Riot Taffy
        { id = 4544, amount = 4374, level = 25 },  -- Mulgore Spice Bread
        { id = 274976, amount = 4374, level = 25, wellfed = true },  -- Plain Ol' Paletusk
        { id = 250073, amount = 4374, level = 25, wellfed = true },  -- Raging Raptor Ribs
        { id = 13755, amount = 4374, level = 35 },  -- Raw Winter Squid
        { id = 19224, amount = 4374, level = 25 },  -- Red Hot Wings
        { id = 278118, amount = 4374, level = 25 },  -- Rich Broth
        { id = 4594, amount = 4374, level = 25, wellfed = true },  -- Rockscale Cod
        { id = 12216, amount = 4374, level = 25, wellfed = true },  -- Spiced Chili Crab
        { id = 1707, amount = 4374, level = 25 },  -- Stormwind Brie
        { id = 3728, amount = 4374, level = 25, wellfed = true },  -- Tasty Lion Steak
        { id = 8543, amount = 4374, level = 25 },  -- Underwater Mushroom Cap
        { id = 3771, amount = 4374, level = 25 },  -- Wild Hog Shank
        { id = 16169, amount = 4374, level = 25 },  -- Wild Ricecake
        { id = 1119, amount = 2760, level = 0 },  -- Bottled Spirits
        { id = 4593, amount = 2760, level = 15, wellfed = true },  -- Bristle Whisker Catfish
        { id = 1114, amount = 2760, level = 15 },  -- Conjured Rye
        { id = 3664, amount = 2760, level = 15, wellfed = true },  -- Crocolisk Gumbo
        { id = 3665, amount = 2760, level = 15, wellfed = true },  -- Curiously Tasty Omelet
        { id = 5478, amount = 2760, level = 15 },  -- Dig Rat Stew
        { id = 422, amount = 2760, level = 15 },  -- Dwarven Mild
        { id = 5527, amount = 2760, level = 15, wellfed = true },  -- Goblin Deviled Clams
        { id = 3666, amount = 2760, level = 15, wellfed = true },  -- Gooey Spider Cake
        { id = 3727, amount = 2760, level = 15, wellfed = true },  -- Hot Lion Chops
        { id = 5480, amount = 2760, level = 15, wellfed = true },  -- Lean Venison
        { id = 12209, amount = 2760, level = 15, wellfed = true },  -- Lean Wolf Steak
        { id = 248613, amount = 2760, level = 15 },  -- Lightning in a Bottle
        { id = 4592, amount = 2760, level = 5, wellfed = true },  -- Longjaw Mud Snapper
        { id = 4542, amount = 2760, level = 15 },  -- Moist Cornbread
        { id = 3770, amount = 2760, level = 15 },  -- Mutton Chop
        { id = 12214, amount = 2760, level = 15, wellfed = true },  -- Mystery Stew
        { id = 19305, amount = 2760, level = 15 },  -- Pickled Kodo Foot
        { id = 12210, amount = 2760, level = 15, wellfed = true },  -- Roast Raptor
        { id = 21217, amount = 2760, level = 30, wellfed = true },  -- Sagefish Delight
        { id = 1017, amount = 2760, level = 15, wellfed = true },  -- Seasoned Wolf Kabob
        { id = 278121, amount = 2760, level = 15 },  -- Smoked Sausage
        { id = 4538, amount = 2760, level = 15 },  -- Snapvine Watermelon
        { id = 3729, amount = 2760, level = 15, wellfed = true },  -- Soothing Turtle Bisque
        { id = 4606, amount = 2760, level = 15 },  -- Spongy Morel
        { id = 16170, amount = 2760, level = 15 },  -- Steamed Mandu
        { id = 2685, amount = 2760, level = 15, wellfed = true },  -- Succulent Pork Ribs
        { id = 7228, amount = 2760, level = 15 },  -- Tigule's Strawberry Ice Cream
        { id = 5473, amount = 1470, level = 1 },  -- Scorpid Surprise
        { id = 3448, amount = 1470, level = 0 },  -- Senggin Root
        { id = 3726, amount = 1218, level = 5, wellfed = true },  -- Big Bear Steak
        { id = 3220, amount = 1218, level = 5, wellfed = true },  -- Blood Sausage
        { id = 250080, amount = 1218, level = 5, wellfed = true },  -- Breakfast Omelette
        { id = 12213, amount = 1218, level = 5, wellfed = true },  -- Carrion Surprise
        { id = 5526, amount = 1218, level = 5 },  -- Clam Chowder
        { id = 1113, amount = 1218, level = 5 },  -- Conjured Bread
        { id = 2684, amount = 1218, level = 5, wellfed = true },  -- Coyote Steak
        { id = 2683, amount = 1218, level = 5, wellfed = true },  -- Crab Cake
        { id = 5479, amount = 1218, level = 5, wellfed = true },  -- Crispy Lizard Tail
        { id = 3662, amount = 1218, level = 5, wellfed = true },  -- Crocolisk Steak
        { id = 414, amount = 1218, level = 5 },  -- Dalaran Sharp
        { id = 12238, amount = 1218, level = 5 },  -- Darkshore Grouper
        { id = 17119, amount = 1218, level = 5 },  -- Deeprun Rat Kabob
        { id = 2687, amount = 1218, level = 5, wellfed = true },  -- Dry Pork Ribs
        { id = 268912, amount = 1218, level = 5, wellfed = true },  -- Expiring Crab Cake
        { id = 268913, amount = 1218, level = 5, wellfed = true },  -- Expiring Crocolisk Steak
        { id = 5476, amount = 1218, level = 5, wellfed = true },  -- Fillet of Frenzy
        { id = 5066, amount = 1218, level = 5 },  -- Fissure Plant
        { id = 4541, amount = 1218, level = 5 },  -- Freshly Baked Bread
        { id = 724, amount = 1218, level = 5, wellfed = true },  -- Goretusk Liver Pie
        { id = 252026, amount = 1218, level = 5 },  -- Gustberry Pie
        { id = 278117, amount = 1218, level = 5 },  -- Hard Boiled Eggs
        { id = 2287, amount = 1218, level = 5 },  -- Haunch of Meat
        { id = 252029, amount = 1218, level = 5 },  -- Hippogryph Flank
        { id = 17406, amount = 1218, level = 5 },  -- Holiday Cheesewheel
        { id = 252030, amount = 1218, level = 5 },  -- Pungent Skycheddar
        { id = 252032, amount = 1218, level = 5 },  -- Red Delicious Stormapple
        { id = 4605, amount = 1218, level = 5 },  -- Red-speckled Mushroom
        { id = 1082, amount = 1218, level = 5, wellfed = true },  -- Redridge Goulash
        { id = 1326, amount = 1218, level = 0 },  -- Sauteed Sunfish
        { id = 787, amount = 1218, level = 1, wellfed = true },  -- Slitherskin Mackerel
        { id = 21072, amount = 1218, level = 10, wellfed = true },  -- Smoked Sagefish
        { id = 19304, amount = 1218, level = 5 },  -- Spiced Beef Jerky
        { id = 18633, amount = 1218, level = 5 },  -- Styleen's Sour Suckerpop
        { id = 4537, amount = 1218, level = 5 },  -- Tel'Abim Banana
        { id = 250077, amount = 1218, level = 5, wellfed = true },  -- Twice-Spiced Raptor Slice
        { id = 16167, amount = 1218, level = 5 },  -- Versicolor Treat
        { id = 733, amount = 1218, level = 5 },  -- Westfall Stew
        { id = 16166, amount = 306, level = 1 },  -- Bean Soup
        { id = 2888, amount = 306, level = 1, wellfed = true },  -- Beer Basted Boar Ribs
        { id = 5525, amount = 306, level = 1 },  -- Boiled Clams
        { id = 278119, amount = 306, level = 1 },  -- Bread with Butter
        { id = 6290, amount = 306, level = 1, wellfed = true },  -- Brilliant Smallfish
        { id = 11584, amount = 306, level = 0, wellfed = true },  -- Cactus Apple Surprise
        { id = 7807, amount = 306, level = 1, wellfed = true },  -- Candy Bar
        { id = 17344, amount = 306, level = 1 },  -- Candy Cane
        { id = 2679, amount = 306, level = 1 },  -- Charred Wolf Meat
        { id = 7808, amount = 306, level = 1, wellfed = true },  -- Chocolate Square
        { id = 5349, amount = 306, level = 1 },  -- Conjured Muffin
        { id = 2682, amount = 306, level = 1, wellfed = true },  -- Cooked Crab Claw
        { id = 12224, amount = 306, level = 1, wellfed = true },  -- Crispy Bat Wing
        { id = 19223, amount = 306, level = 1 },  -- Darkmoon Dog
        { id = 2070, amount = 306, level = 1 },  -- Darnassian Bleu
        { id = 17198, amount = 306, level = 1, wellfed = true },  -- Egg Nog
        { id = 4604, amount = 306, level = 1 },  -- Forest Mushroom Cap
        { id = 252028, amount = 306, level = 1 },  -- Fresh Gustberry Bread
        { id = 252022, amount = 306, level = 1 },  -- Galestrider Jerky
        { id = 267474, amount = 306, level = 1 },  -- Galeswept Forestshroom
        { id = 17197, amount = 306, level = 1, wellfed = true },  -- Gingerbread Cookie
        { id = 961, amount = 306, level = 0 },  -- Healing Herb
        { id = 6888, amount = 306, level = 1, wellfed = true },  -- Herb Baked Egg
        { id = 5472, amount = 306, level = 1, wellfed = true },  -- Kaldorei Spider Kabob
        { id = 7097, amount = 306, level = 1 },  -- Leg Meat
        { id = 6316, amount = 306, level = 5, wellfed = true },  -- Loch Frenzy Delight
        { id = 7806, amount = 306, level = 1, wellfed = true },  -- Lollipop
        { id = 3663, amount = 306, level = 1, wellfed = true },  -- Murloc Fin Soup
        { id = 263512, amount = 306, level = 5, wellfed = true },  -- Pincer Bites
        { id = 5095, amount = 306, level = 5, wellfed = true },  -- Rainbow Fin Albacore
        { id = 5057, amount = 306, level = 1 },  -- Ripe Watermelon
        { id = 2681, amount = 306, level = 1, wellfed = true },  -- Roasted Boar Meat
        { id = 5474, amount = 306, level = 1, wellfed = true },  -- Roasted Kodo Meat
        { id = 4536, amount = 306, level = 1 },  -- Shiny Red Apple
        { id = 263509, amount = 306, level = 5, wellfed = true },  -- Skywall Souffle
        { id = 4656, amount = 306, level = 1 },  -- Small Pumpkin
        { id = 6890, amount = 306, level = 1, wellfed = true },  -- Smoked Bear Meat
        { id = 2680, amount = 306, level = 1, wellfed = true },  -- Spiced Wolf Meat
        { id = 5477, amount = 306, level = 1, wellfed = true },  -- Strider Stew
        { id = 250079, amount = 306, level = 1, wellfed = true },  -- Tasty Raptor Bites
        { id = 4540, amount = 306, level = 1 },  -- Tough Hunk of Bread
        { id = 117, amount = 306, level = 1 },  -- Tough Jerky
        { id = 278569, amount = 306, level = 1 },  -- Yesterday's Leftovers
        { id = 252023, amount = 306, level = 1 },  -- Zaalanarr Sharp
        { id = 278265, amount = 150, level = 1 },  -- Nutritious Slime Sludge
        { id = 6299, amount = 150, level = 1 },  -- Sickly Looking Fish
        { id = 11109, amount = 150, level = 1 },  -- Special Chicken Feed
    },
    drink = {
        { id = 231778, amount = 25500, level = 55 },  -- Mountain Spring Water
        { id = 19301, amount = 22050, level = 51 },  -- Alterac Manna Biscuit
        { id = 13724, amount = 22050, level = 45 },  -- Enriched Manna Biscuit
        { id = 20031, amount = 22050, level = 55 },  -- Essence Mango
        { id = 262433, amount = 22050, level = 0 },  -- Ketharas' Hyjal Stew
        { id = 8079, amount = 21000, level = 55 },  -- Conjured Crystal Water
        { id = 18300, amount = 21000, level = 55 },  -- Hyjal Nectar
        { id = 8078, amount = 14670, level = 45 },  -- Conjured Sparkling Water
        { id = 8766, amount = 14670, level = 45 },  -- Morning Glory Dew
        { id = 249870, amount = 14670, level = 45, wellfed = true },  -- Sage's Tea
        { id = 249876, amount = 14670, level = 45, wellfed = true },  -- Wicked Smoothie
        { id = 19300, amount = 9960, level = 35 },  -- Bottled Winterspring Water
        { id = 8077, amount = 9960, level = 35 },  -- Conjured Mineral Water
        { id = 1645, amount = 9960, level = 35 },  -- Moonberry Juice
        { id = 249875, amount = 9960, level = 35, wellfed = true },  -- Spicy Smoothie
        { id = 249869, amount = 9960, level = 35, wellfed = true },  -- Sunny Tea
        { id = 249874, amount = 6723, level = 25, wellfed = true },  -- Calcified Smoothie
        { id = 3772, amount = 6723, level = 25 },  -- Conjured Spring Water
        { id = 4791, amount = 6723, level = 25 },  -- Enchanted Water
        { id = 10841, amount = 6723, level = 25 },  -- Goldthorn Tea
        { id = 1708, amount = 6723, level = 25 },  -- Sweet Nectar
        { id = 249868, amount = 6723, level = 25, wellfed = true },  -- Triage Tea
        { id = 9451, amount = 4176, level = 15 },  -- Bubbling Water
        { id = 2136, amount = 4176, level = 15 },  -- Conjured Purified Water
        { id = 19299, amount = 4176, level = 15 },  -- Fizzy Faire Drink
        { id = 1205, amount = 4176, level = 15 },  -- Melon Juice
        { id = 249873, amount = 4176, level = 15, wellfed = true },  -- Mrrggl Smrrthle
        { id = 249867, amount = 4176, level = 15, wellfed = true },  -- Root Tea
        { id = 17404, amount = 2184, level = 5 },  -- Blended Bean Brew
        { id = 2288, amount = 2184, level = 5 },  -- Conjured Fresh Water
        { id = 252027, amount = 2184, level = 5 },  -- Gustberry Juice
        { id = 1179, amount = 2184, level = 5 },  -- Ice Cold Milk
        { id = 249866, amount = 2184, level = 5, wellfed = true },  -- Royal Tea
        { id = 249872, amount = 2184, level = 5, wellfed = true },  -- Slimy Smoothie
        { id = 3448, amount = 1470, level = 0 },  -- Senggin Root
        { id = 5350, amount = 756, level = 1 },  -- Conjured Water
        { id = 252031, amount = 756, level = 1 },  -- Crisp Spring Water
        { id = 249865, amount = 756, level = 1, wellfed = true },  -- Peace Tea
        { id = 159, amount = 756, level = 1 },  -- Refreshing Spring Water
        { id = 249871, amount = 756, level = 1, wellfed = true },  -- Venomous Smoothie
        { id = 1401, amount = 300, level = 4 },  -- Green Tea Leaf
    },
    bandage = {
        { id = 23684, amount = 2500, level = 0 },  -- Crystal Infused Bandage
        { id = 19307, amount = 2000, level = 0 },  -- Alterac Heavy Runecloth Bandage
        { id = 20066, amount = 2000, level = 45 },  -- Arathi Basin Runecloth Bandage
        { id = 272058, amount = 2000, level = 45 },  -- Darkspear Islands Runecloth Bandage
        { id = 20234, amount = 2000, level = 45 },  -- Defiler's Runecloth Bandage
        { id = 14530, amount = 2000, level = 0 },  -- Heavy Runecloth Bandage
        { id = 20243, amount = 2000, level = 45 },  -- Highlander's Runecloth Bandage
        { id = 19066, amount = 2000, level = 45 },  -- Warsong Gulch Runecloth Bandage
        { id = 14529, amount = 1360, level = 0 },  -- Runecloth Bandage
        { id = 20065, amount = 1104, level = 35 },  -- Arathi Basin Mageweave Bandage
        { id = 272057, amount = 1104, level = 35 },  -- Darkspear Islands Mageweave Bandage
        { id = 20232, amount = 1104, level = 35 },  -- Defiler's Mageweave Bandage
        { id = 8545, amount = 1104, level = 0 },  -- Heavy Mageweave Bandage
        { id = 20237, amount = 1104, level = 35 },  -- Highlander's Mageweave Bandage
        { id = 19067, amount = 1104, level = 35 },  -- Warsong Gulch Mageweave Bandage
        { id = 8544, amount = 800, level = 0 },  -- Mageweave Bandage
        { id = 20067, amount = 640, level = 25 },  -- Arathi Basin Silk Bandage
        { id = 272056, amount = 640, level = 25 },  -- Darkspear Islands Silk Bandage
        { id = 20235, amount = 640, level = 25 },  -- Defiler's Silk Bandage
        { id = 6451, amount = 640, level = 0 },  -- Heavy Silk Bandage
        { id = 20244, amount = 640, level = 25 },  -- Highlander's Silk Bandage
        { id = 19068, amount = 640, level = 25 },  -- Warsong Gulch Silk Bandage
        { id = 6450, amount = 400, level = 0 },  -- Silk Bandage
        { id = 3531, amount = 301, level = 0 },  -- Heavy Wool Bandage
        { id = 3530, amount = 161, level = 0 },  -- Wool Bandage
        { id = 2581, amount = 114, level = 0 },  -- Heavy Linen Bandage
        { id = 1251, amount = 66, level = 0 },  -- Linen Bandage
    },
})
SpellDB.RegisterHealingItems({
    241650,  -- Major Discolored Healing Potion
    18253,  -- Major Rejuvenation Potion
    282011,  -- Restored Healing Potion
    15723,  -- Tea with Sugar
    9421,  -- Major Healthstone
    19012,  -- Major Healthstone
    19013,  -- Major Healthstone
    17348,  -- Major Healing Draught
    13446,  -- Major Healing Potion
    223913,  -- Major Healing Potion
    11952,  -- Night Dragon's Breath
    23579,  -- The McWeaksauce Classic
    14894,  -- Lily Root
    5510,  -- Greater Healthstone
    19010,  -- Greater Healthstone
    19011,  -- Greater Healthstone
    18839,  -- Combat Healing Potion
    247242,  -- Superior Discolored Healing Potion
    17349,  -- Superior Healing Draught
    3928,  -- Superior Healing Potion
    274935,  -- Tessa's Tonic
    9144,  -- Wildvine Potion
    5509,  -- Healthstone
    19008,  -- Healthstone
    19009,  -- Healthstone
    216619,  -- Student Fodder
    247241,  -- Greater Discolored Healing Potion
    1710,  -- Greater Healing Potion
    223914,  -- Greater Healing Potion
    247240,  -- Discolored Healing Potion
    929,  -- Healing Potion
    5511,  -- Lesser Healthstone
    19006,  -- Lesser Healthstone
    19007,  -- Lesser Healthstone
    268883,  -- Perishable Healing Potion
    4596,  -- Minor Discolored Healing Potion
    2456,  -- Minor Rejuvenation Potion
    5205,  -- Sprouted Frond
    247239,  -- Lesser Discolored Healing Potion
    858,  -- Lesser Healing Potion
    268882,  -- Perishable Lesser Healing Potion
    5512,  -- Minor Healthstone
    19004,  -- Minor Healthstone
    19005,  -- Minor Healthstone
    118,  -- Minor Healing Potion
    268881,  -- Perishable Minor Healing Potion
    255663,  -- Windstone
})
