-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
--
-- JustAC: WoW Forever entries for the curated default lists. GENERATED by
-- tools/gen_forever_defaults.py (curated by ability name there) - do not edit by hand.
-- Applies only on the Forever client: "<CLASS>_F" keys are added (plus the class key for
-- tables read by class), so retail's lists are untouched. Ids are rank 1; every rank
-- resolves at runtime (BlizzardAPI.GetDisplaySpellID, SpellDB.StaticLookup).

local SpellDB = LibStub("JustAC-SpellDB", true)
if not (SpellDB and SpellDB.IsForever and SpellDB.IsForever()) then return end

local DEFENSIVE = {
    WARRIOR = {12975, 871, 402927},
    PALADIN = {642, 498, 1022, 633, 19750, 635},
    HUNTER = {19263, 5384},
    ROGUE = {5277, 1856},
    PRIEST = {17, 13908, 139, 2061},
    SHAMAN = {8004, 331},
    MAGE = {11958, 11426, 1463},
    WARLOCK = {6789, 6229, 689},
    DRUID = {22812, 22842, 774, 8936, 5185},
}
local PET_HEAL = {
    HUNTER = {136},
    WARLOCK = {755},
}
local PET_REZ = {
    HUNTER = {982, 883},
    WARLOCK = {688, 697, 712, 691},
}
local GROUP_HELP = {
    SHAMAN = {5394},
}
local GROUP_HEAL = {
    PRIEST = {596},
    SHAMAN = {1064},
    DRUID = {740},
}
local EMERGENCY = {
    DRUID = {740},
}
local GAP_CLOSER = {
    WARRIOR = {100, 20252},
    ROGUE = {2983},
    DRUID = {1238122},
}
local BURST = {
    WARRIOR = {1719, 12328},
    ROGUE = {13750, 13877, 14177},
    MAGE = {12042, 11129, 12043},
    HUNTER = {3045, 19574},
    PRIEST = {10060},
}
local TOPOFF = {
    PRIEST = {139, 2050},
    PALADIN = {19750, 635},
    DRUID = {774, 8936},
    SHAMAN = {8004, 331},
}
local MAINTAINED = {
    PRIEST = { { group = {1243}, default = 1243, raidWide = true, auraIDs = {1243, 1244, 1245, 2791, 10937, 10938} }, { group = {588}, default = 588, auraIDs = {588, 7128, 602, 1006, 10951, 10952} } },
    MAGE = { { group = {1459}, default = 1459, raidWide = true, auraIDs = {1459, 1460, 1461, 10156, 10157} }, { group = {168, 7302, 6117}, default = 168, auraIDs = {168, 7300, 7301, 7302, 7320, 10219, 10220, 6117, 22782, 22783} } },
    DRUID = { { group = {1126}, default = 1126, raidWide = true, auraIDs = {1126, 5232, 6756, 5234, 8907, 9884, 9885} } },
    WARLOCK = { { group = {687, 706}, default = 687, auraIDs = {687, 696, 706, 1086, 11733, 11734, 11735} } },
    SHAMAN = { { group = {324, 408510}, default = 324, auraIDs = {324, 26364, 325, 26365, 905, 26366, 945, 26367, 8134, 26369, 10431, 26370, 10432, 26363, 408510} } },
    PALADIN = { { group = {465, 7294, 19746}, default = 465, auraIDs = {465, 10290, 643, 10291, 1032, 10292, 10293, 7294, 10298, 10299, 10300, 10301, 19746} } },
    HUNTER = { { group = {13165, 13163}, default = 13165, auraIDs = {13165, 14318, 14319, 14320, 14321, 14322, 25296, 13163} } },
}
local IMBUES = {8232, 8024, 8017}
local IMBUE_CASTS = {8232, 8235, 10486, 16362, 8024, 8027, 8030, 16339, 16341, 16342, 8017, 8018, 8019, 10399, 16314, 16315, 16316, 8033, 8038, 10456, 16355, 16356}
local INTERRUPTS = {
    [72] = { kind = "interrupt", reach = "ranged", pri = 1 },  -- Shield Bash
    [8042] = { kind = "interrupt", reach = "ranged", pri = 1 },  -- Earth Shock
    [1238122] = { kind = "interrupt", reach = "ranged", pri = 2 },  -- Feral Charge
    [5211] = { kind = "cc", mech = 12, reach = "ranged", pri = 3 },  -- Bash
    [19503] = { kind = "cc", mech = 2, reach = "ranged", pri = 3 },  -- Scatter Shot
    [19577] = { kind = "cc", mech = 12, reach = "ranged", pri = 3 },  -- Intimidation
    [118] = { kind = "cc", mech = 17, reach = "ranged", pri = 4 },  -- Polymorph
    [5782] = { kind = "cc", mech = 5, reach = "ranged", pri = 5 },  -- Fear
    [6789] = { kind = "cc", mech = 24, reach = "ranged", pri = 4 },  -- Death Coil
}
local SOOTHE_REMOVE = {2908}
local RANGE = {
    [772] = 5,  -- Rend (warrior)
    [1715] = 5,  -- Hamstring (warrior)
    [7386] = 5,  -- Sunder Armor (warrior)
    [100] = 25,  -- Charge (warrior)
    [1752] = 5,  -- Sinister Strike (rogue)
    [1766] = 5,  -- Kick (rogue)
    [3044] = 35,  -- Arcane Shot (hunter)
    [2974] = 5,  -- Wing Clip (hunter)
    [116] = 30,  -- Frostbolt (mage)
    [2136] = 20,  -- Fire Blast (mage)
    [686] = 30,  -- Shadow Bolt (warlock)
    [172] = 30,  -- Corruption (warlock)
    [585] = 30,  -- Smite (priest)
    [589] = 30,  -- Shadow Word: Pain (priest)
    [5176] = 30,  -- Wrath (druid)
    [8921] = 30,  -- Moonfire (druid)
    [1082] = 5,  -- Claw (druid)
    [403] = 30,  -- Lightning Bolt (shaman)
    [8042] = 20,  -- Earth Shock (shaman)
    [20271] = 10,  -- Judgement (paladin)
    [679] = 5,  -- Holy Strike (paladin)
}
local TIERS = {
    [642] = 1,  -- Divine Shield
    [498] = 1,  -- Divine Protection
    [1022] = 1,  -- Blessing of Protection
    [11958] = 1,  -- Ice Block
    [633] = 2,  -- Lay on Hands
    [13908] = 2,  -- Desperate Prayer
    [402927] = 2,  -- Victory Rush
    [871] = 4,  -- Shield Wall
    [12975] = 4,  -- Last Stand
    [5277] = 4,  -- Evasion
    [19263] = 4,  -- Deterrence
}
local CATEGORIES = { defensive = { [17] = true, [498] = true, [642] = true, [871] = true, [1022] = true, [1463] = true, [1856] = true, [5277] = true, [5384] = true, [6229] = true, [6789] = true, [7744] = true, [11426] = true, [11958] = true, [12975] = true, [19263] = true, [20589] = true, [20594] = true, [22812] = true, [1259718] = true, [1299026] = true }, healing = { [136] = true, [139] = true, [331] = true, [596] = true, [633] = true, [635] = true, [689] = true, [740] = true, [755] = true, [774] = true, [1064] = true, [2061] = true, [5185] = true, [5394] = true, [8004] = true, [8936] = true, [13908] = true, [19750] = true, [22842] = true, [402927] = true }, cc = { [118] = true, [5211] = true, [5782] = true, [6789] = true, [19503] = true, [19577] = true, [20549] = true } }
local CHANNELED = {
    [10] = true,  -- Blizzard
    [126] = true,  -- Eye of Kilrogg
    [136] = true,  -- Mend Pet
    [605] = true,  -- Mind Control
    [689] = true,  -- Drain Life
    [698] = true,  -- Ritual of Summoning
    [699] = true,  -- Drain Life
    [709] = true,  -- Drain Life
    [740] = true,  -- Tranquility
    [755] = true,  -- Health Funnel
    [1002] = true,  -- Eyes of the Beast
    [1120] = true,  -- Drain Soul
    [1510] = true,  -- Volley
    [1515] = true,  -- Tame Beast
    [1949] = true,  -- Hellfire
    [2096] = true,  -- Mind Vision
    [3111] = true,  -- Mend Pet
    [3661] = true,  -- Mend Pet
    [3662] = true,  -- Mend Pet
    [3698] = true,  -- Health Funnel
    [3699] = true,  -- Health Funnel
    [3700] = true,  -- Health Funnel
    [5138] = true,  -- Drain Mana
    [5143] = true,  -- Arcane Missiles
    [5144] = true,  -- Arcane Missiles
    [5145] = true,  -- Arcane Missiles
    [5740] = true,  -- Rain of Fire
    [6141] = true,  -- Blizzard
    [6196] = true,  -- Far Sight
    [6197] = true,  -- Eagle Eye
    [6219] = true,  -- Rain of Fire
    [6226] = true,  -- Drain Mana
    [7651] = true,  -- Drain Life
    [8288] = true,  -- Drain Soul
    [8289] = true,  -- Drain Soul
    [8416] = true,  -- Arcane Missiles
    [8417] = true,  -- Arcane Missiles
    [8427] = true,  -- Blizzard
    [8918] = true,  -- Tranquility
    [9862] = true,  -- Tranquility
    [9863] = true,  -- Tranquility
    [10185] = true,  -- Blizzard
    [10186] = true,  -- Blizzard
    [10187] = true,  -- Blizzard
    [10211] = true,  -- Arcane Missiles
    [10212] = true,  -- Arcane Missiles
    [10797] = true,  -- Starshards
    [10909] = true,  -- Mind Vision
    [10911] = true,  -- Mind Control
    [10912] = true,  -- Mind Control
    [11675] = true,  -- Drain Soul
    [11677] = true,  -- Rain of Fire
    [11678] = true,  -- Rain of Fire
    [11683] = true,  -- Hellfire
    [11684] = true,  -- Hellfire
    [11693] = true,  -- Health Funnel
    [11694] = true,  -- Health Funnel
    [11695] = true,  -- Health Funnel
    [11699] = true,  -- Drain Life
    [11700] = true,  -- Drain Life
    [11703] = true,  -- Drain Mana
    [11704] = true,  -- Drain Mana
    [12051] = true,  -- Evocation
    [13542] = true,  -- Mend Pet
    [13543] = true,  -- Mend Pet
    [13544] = true,  -- Mend Pet
    [14294] = true,  -- Volley
    [14295] = true,  -- Volley
    [15407] = true,  -- Mind Flay
    [16914] = true,  -- Hurricane
    [17311] = true,  -- Mind Flay
    [17312] = true,  -- Mind Flay
    [17313] = true,  -- Mind Flay
    [17314] = true,  -- Mind Flay
    [17401] = true,  -- Hurricane
    [17402] = true,  -- Hurricane
    [18540] = true,  -- Ritual of Doom
    [18807] = true,  -- Mind Flay
    [19296] = true,  -- Starshards
    [19299] = true,  -- Starshards
    [19302] = true,  -- Starshards
    [19303] = true,  -- Starshards
    [19304] = true,  -- Starshards
    [19305] = true,  -- Starshards
    [25345] = true,  -- Arcane Missiles
    [63644] = true,  -- Activate Secondary Spec
    [63645] = true,  -- Activate Primary Spec
    [402174] = true,  -- Penance
    [437169] = true,  -- Portal of Summoning
    [1240720] = true,  -- Penance
    [1240721] = true,  -- Penance
    [1260270] = true,  -- Rapid Regeneration
    [1316697] = true,  -- Wrack
    [1316995] = true,  -- Penance
}
local FRONTAL_DOTS = {
    [133] = true,  -- Fireball (90% upfront)
    [143] = true,  -- Fireball (92% upfront)
    [145] = true,  -- Fireball (90% upfront)
    [348] = true,  -- Immolate (35% upfront)
    [707] = true,  -- Immolate (36% upfront)
    [1094] = true,  -- Immolate (35% upfront)
    [1822] = true,  -- Rake (32% upfront)
    [1823] = true,  -- Rake (33% upfront)
    [1824] = true,  -- Rake (37% upfront)
    [2941] = true,  -- Immolate (37% upfront)
    [3140] = true,  -- Fireball (86% upfront)
    [8050] = true,  -- Flame Shock (42% upfront)
    [8052] = true,  -- Flame Shock (51% upfront)
    [8053] = true,  -- Flame Shock (43% upfront)
    [8400] = true,  -- Fireball (87% upfront)
    [8401] = true,  -- Fireball (86% upfront)
    [8402] = true,  -- Fireball (89% upfront)
    [8921] = true,  -- Moonfire (40% upfront)
    [8924] = true,  -- Moonfire (35% upfront)
    [8925] = true,  -- Moonfire (38% upfront)
    [8926] = true,  -- Moonfire (38% upfront)
    [8927] = true,  -- Moonfire (38% upfront)
    [8928] = true,  -- Moonfire (39% upfront)
    [8929] = true,  -- Moonfire (37% upfront)
    [9833] = true,  -- Moonfire (37% upfront)
    [9834] = true,  -- Moonfire (36% upfront)
    [9835] = true,  -- Moonfire (36% upfront)
    [9904] = true,  -- Rake (37% upfront)
    [10148] = true,  -- Fireball (88% upfront)
    [10149] = true,  -- Fireball (88% upfront)
    [10150] = true,  -- Fireball (89% upfront)
    [10151] = true,  -- Fireball (89% upfront)
    [10447] = true,  -- Flame Shock (49% upfront)
    [10448] = true,  -- Flame Shock (48% upfront)
    [11366] = true,  -- Pyroblast (71% upfront)
    [11665] = true,  -- Immolate (37% upfront)
    [11667] = true,  -- Immolate (36% upfront)
    [11668] = true,  -- Immolate (36% upfront)
    [12505] = true,  -- Pyroblast (71% upfront)
    [12522] = true,  -- Pyroblast (72% upfront)
    [12523] = true,  -- Pyroblast (71% upfront)
    [12524] = true,  -- Pyroblast (71% upfront)
    [12525] = true,  -- Pyroblast (72% upfront)
    [12526] = true,  -- Pyroblast (72% upfront)
    [14914] = true,  -- Holy Fire (74% upfront)
    [15261] = true,  -- Holy Fire (73% upfront)
    [15262] = true,  -- Holy Fire (72% upfront)
    [15263] = true,  -- Holy Fire (73% upfront)
    [15264] = true,  -- Holy Fire (72% upfront)
    [15265] = true,  -- Holy Fire (62% upfront)
    [15266] = true,  -- Holy Fire (74% upfront)
    [15267] = true,  -- Holy Fire (73% upfront)
    [18809] = true,  -- Pyroblast (73% upfront)
    [25306] = true,  -- Fireball (89% upfront)
    [25309] = true,  -- Immolate (36% upfront)
    [29228] = true,  -- Flame Shock (49% upfront)
    [401502] = true,  -- Frostfire Bolt (79% upfront)
    [1237312] = true,  -- Frostfire Bolt (82% upfront)
    [1237313] = true,  -- Frostfire Bolt (84% upfront)
}
local NEXT_SWING = {
    [78] = true,  -- Heroic Strike (warrior)
    [284] = true,  -- Heroic Strike (warrior)
    [285] = true,  -- Heroic Strike (warrior)
    [845] = true,  -- Cleave (warrior)
    [1608] = true,  -- Heroic Strike (warrior)
    [7369] = true,  -- Cleave (warrior)
    [11564] = true,  -- Heroic Strike (warrior)
    [11565] = true,  -- Heroic Strike (warrior)
    [11566] = true,  -- Heroic Strike (warrior)
    [11567] = true,  -- Heroic Strike (warrior)
    [11608] = true,  -- Cleave (warrior)
    [11609] = true,  -- Cleave (warrior)
    [20569] = true,  -- Cleave (warrior)
    [25286] = true,  -- Heroic Strike (warrior)
    [2973] = true,  -- Raptor Strike (hunter)
    [14260] = true,  -- Raptor Strike (hunter)
    [14261] = true,  -- Raptor Strike (hunter)
    [14262] = true,  -- Raptor Strike (hunter)
    [14263] = true,  -- Raptor Strike (hunter)
    [14264] = true,  -- Raptor Strike (hunter)
    [14265] = true,  -- Raptor Strike (hunter)
    [14266] = true,  -- Raptor Strike (hunter)
    [6807] = true,  -- Maul (druid)
    [6808] = true,  -- Maul (druid)
    [6809] = true,  -- Maul (druid)
    [8972] = true,  -- Maul (druid)
    [9745] = true,  -- Maul (druid)
    [9880] = true,  -- Maul (druid)
    [9881] = true,  -- Maul (druid)
}
local SHORT_BUFFS = {
    10,  -- Blizzard (8s)
    126,  -- Eye of Kilrogg (45s)
    130,  -- Slow Fall (30s)
    498,  -- Divine Protection (6s)
    543,  -- Fire Ward (30s)
    586,  -- Fade (10s)
    605,  -- Mind Control (60s)
    642,  -- Divine Shield (10s)
    755,  -- Health Funnel (10s)
    871,  -- Shield Wall (12s)
    1002,  -- Eyes of the Beast (120s)
    1463,  -- Mana Shield (60s)
    1510,  -- Volley (6s)
    1515,  -- Tame Beast (20s)
    1706,  -- Levitate (120s)
    1719,  -- Recklessness (15s)
    1850,  -- Dash (15s)
    1949,  -- Hellfire (15s)
    1953,  -- Blink (1s)
    2096,  -- Mind Vision (60s)
    2120,  -- Flamestrike (8s)
    2565,  -- Shield Block (7s)
    2651,  -- Elune's Grace (15s)
    2983,  -- Sprint (15s)
    3045,  -- Rapid Fire (15s)
    5143,  -- Arcane Missiles (3s)
    5171,  -- Slice and Dice (6s)
    5229,  -- Enrage (10s)
    5277,  -- Evasion (15s)
    5384,  -- Feign Death (360s)
    5740,  -- Rain of Fire (8s)
    6143,  -- Frost Ward (30s)
    6196,  -- Far Sight (60s)
    6197,  -- Eagle Eye (60s)
    6229,  -- Shadow Ward (30s)
    6495,  -- Sentry Totem (300s)
    6673,  -- Battle Shout (180s)
    7267,  -- Grovel (3s)
    11426,  -- Ice Barrier (60s)
    11958,  -- Ice Block (10s)
    12042,  -- Arcane Power (15s)
    12051,  -- Evocation (8s)
    12292,  -- Sweeping Strikes (20s)
    12328,  -- Death Wish (30s)
    12536,  -- Clearcasting (15s)
    13750,  -- Adrenaline Rush (15s)
    13877,  -- Blade Flurry (15s)
    13896,  -- Feedback (15s)
    14183,  -- Premeditation (20s)
    14278,  -- Ghostly Strike (7s)
    16689,  -- Nature's Grasp (45s)
    16914,  -- Hurricane (10s)
    18288,  -- Amplify Curse (30s)
    18499,  -- Berserker Rage (10s)
    18708,  -- Fel Domination (15s)
    19263,  -- Deterrence (10s)
    20154,  -- Seal of Righteousness (30s)
    20164,  -- Seal of Justice (30s)
    20165,  -- Seal of Light (30s)
    20166,  -- Seal of Wisdom (30s)
    20230,  -- Retaliation (15s)
    20375,  -- Seal of Command (30s)
    20554,  -- Berserking (10s)
    20589,  -- Escape Artist (3s)
    20925,  -- Holy Shield (10s)
    21082,  -- Seal of the Crusader (30s)
    22812,  -- Barkskin (15s)
    22842,  -- Frenzied Regeneration (10s)
    23881,  -- Bloodthirst (10s)
    26332,  -- Summon Mouth Tentacle (3.8s)
    26573,  -- Consecration (8s)
    27828,  -- Focused Casting (6s)
    417141,  -- Berserk (15s)
    425336,  -- Rage of the Farseer (25s)
    438040,  -- Redirect (15s)
    461607,  -- Divine Steed (3s)
    1259812,  -- Eureka! (15s)
    1259813,  -- Eureka! (15s)
    1259817,  -- Eureka! (15s)
    1259821,  -- Eureka! (15s)
    1259823,  -- Eureka! (15s)
    1260270,  -- Rapid Regeneration (6s)
    1277324,  -- Dark Sacrifice (15s)
    1310687,  -- Sniper Shot (10s)
    1310703,  -- Venom (6s)
    1311015,  -- Templar's Bulwark (8s)
    1311649,  -- Seal of Fury (30s)
    1317257,  -- Strider Kick (3s)
}
local DOTS = {
    [772] = 9,  -- Rend
    [1160] = 45,  -- Demoralizing Shout
    [6190] = 45,  -- Demoralizing Shout
    [6546] = 12,  -- Rend
    [6547] = 15,  -- Rend
    [6548] = 18,  -- Rend
    [11554] = 45,  -- Demoralizing Shout
    [11555] = 45,  -- Demoralizing Shout
    [11556] = 45,  -- Demoralizing Shout
    [11572] = 21,  -- Rend
    [11573] = 21,  -- Rend
    [11574] = 21,  -- Rend
    [1130] = 120,  -- Hunter's Mark
    [1978] = 15,  -- Serpent Sting
    [3674] = 30,  -- Black Arrow
    [13549] = 15,  -- Serpent Sting
    [13550] = 15,  -- Serpent Sting
    [13551] = 15,  -- Serpent Sting
    [13552] = 15,  -- Serpent Sting
    [13553] = 15,  -- Serpent Sting
    [13554] = 15,  -- Serpent Sting
    [13555] = 15,  -- Serpent Sting
    [13797] = 15,  -- Immolation Trap Effect
    [14296] = 30,  -- Black Arrow
    [14298] = 15,  -- Immolation Trap Effect
    [14299] = 15,  -- Immolation Trap Effect
    [14300] = 15,  -- Immolation Trap Effect
    [14301] = 15,  -- Immolation Trap Effect
    [14323] = 120,  -- Hunter's Mark
    [14324] = 120,  -- Hunter's Mark
    [14325] = 120,  -- Hunter's Mark
    [24118] = 21,  -- Lacerate
    [24119] = 21,  -- Lacerate
    [24120] = 21,  -- Lacerate
    [25295] = 15,  -- Serpent Sting
    [1299332] = 21,  -- Lacerate
    [703] = 18,  -- Garrote
    [1943] = 6,  -- Rupture
    [8631] = 18,  -- Garrote
    [8632] = 18,  -- Garrote
    [8633] = 18,  -- Garrote
    [8639] = 6,  -- Rupture
    [8640] = 6,  -- Rupture
    [11273] = 6,  -- Rupture
    [11274] = 6,  -- Rupture
    [11275] = 6,  -- Rupture
    [11289] = 18,  -- Garrote
    [11290] = 18,  -- Garrote
    [589] = 18,  -- Shadow Word: Pain
    [594] = 18,  -- Shadow Word: Pain
    [970] = 18,  -- Shadow Word: Pain
    [992] = 18,  -- Shadow Word: Pain
    [2767] = 18,  -- Shadow Word: Pain
    [10797] = 6,  -- Starshards
    [10892] = 18,  -- Shadow Word: Pain
    [10893] = 18,  -- Shadow Word: Pain
    [10894] = 18,  -- Shadow Word: Pain
    [15407] = 3,  -- Mind Flay
    [17311] = 3,  -- Mind Flay
    [17312] = 3,  -- Mind Flay
    [17313] = 3,  -- Mind Flay
    [17314] = 3,  -- Mind Flay
    [18807] = 3,  -- Mind Flay
    [19296] = 6,  -- Starshards
    [19299] = 6,  -- Starshards
    [19302] = 6,  -- Starshards
    [19303] = 6,  -- Starshards
    [19304] = 6,  -- Starshards
    [19305] = 6,  -- Starshards
    [8050] = 12,  -- Flame Shock
    [8053] = 12,  -- Flame Shock
    [10447] = 12,  -- Flame Shock
    [10448] = 12,  -- Flame Shock
    [29228] = 12,  -- Flame Shock
    [172] = 12,  -- Corruption
    [348] = 15,  -- Immolate
    [603] = 60,  -- Bane of Doom
    [707] = 15,  -- Immolate
    [980] = 24,  -- Bane of Agony
    [1014] = 24,  -- Bane of Agony
    [1094] = 15,  -- Immolate
    [1120] = 15,  -- Drain Soul
    [2941] = 15,  -- Immolate
    [6217] = 24,  -- Bane of Agony
    [6222] = 15,  -- Corruption
    [6223] = 18,  -- Corruption
    [7648] = 18,  -- Corruption
    [8288] = 15,  -- Drain Soul
    [8289] = 15,  -- Drain Soul
    [11665] = 15,  -- Immolate
    [11667] = 15,  -- Immolate
    [11668] = 15,  -- Immolate
    [11671] = 18,  -- Corruption
    [11672] = 18,  -- Corruption
    [11675] = 15,  -- Drain Soul
    [11711] = 24,  -- Bane of Agony
    [11712] = 24,  -- Bane of Agony
    [11713] = 24,  -- Bane of Agony
    [25309] = 15,  -- Immolate
    [25311] = 18,  -- Corruption
    [440892] = 300,  -- Curse of the Elements
    [1311676] = 300,  -- Curse of the Elements
    [1311677] = 300,  -- Curse of the Elements
    [1311680] = 300,  -- Curse of the Elements
    [1316697] = 6,  -- Wrack
    [99] = 30,  -- Demoralizing Roar
    [339] = 12,  -- Entangling Roots
    [770] = 40,  -- Faerie Fire
    [778] = 40,  -- Faerie Fire
    [1062] = 15,  -- Entangling Roots
    [1079] = 12,  -- Rip
    [1735] = 30,  -- Demoralizing Roar
    [1822] = 9,  -- Rake
    [1823] = 9,  -- Rake
    [1824] = 9,  -- Rake
    [5195] = 18,  -- Entangling Roots
    [5196] = 21,  -- Entangling Roots
    [5570] = 12,  -- Insect Swarm
    [8921] = 9,  -- Moonfire
    [8924] = 12,  -- Moonfire
    [8925] = 12,  -- Moonfire
    [8926] = 12,  -- Moonfire
    [8927] = 12,  -- Moonfire
    [8928] = 12,  -- Moonfire
    [8929] = 12,  -- Moonfire
    [9490] = 30,  -- Demoralizing Roar
    [9492] = 12,  -- Rip
    [9493] = 12,  -- Rip
    [9747] = 30,  -- Demoralizing Roar
    [9749] = 40,  -- Faerie Fire
    [9752] = 12,  -- Rip
    [9833] = 12,  -- Moonfire
    [9834] = 12,  -- Moonfire
    [9835] = 12,  -- Moonfire
    [9852] = 24,  -- Entangling Roots
    [9853] = 27,  -- Entangling Roots
    [9894] = 12,  -- Rip
    [9896] = 12,  -- Rip
    [9898] = 30,  -- Demoralizing Roar
    [9904] = 9,  -- Rake
    [9907] = 40,  -- Faerie Fire
    [24974] = 12,  -- Insect Swarm
    [24975] = 12,  -- Insect Swarm
    [24976] = 12,  -- Insect Swarm
    [24977] = 12,  -- Insect Swarm
    [414644] = 15,  -- Lacerate
    [1235826] = 15,  -- Lacerate
    [1235827] = 15,  -- Lacerate
}

--- Forever entries under <CLASS>_F (the spec key there); byClass also replaces the
--- class key, for tables some readers index by class.
local function Put(tbl, lists, byClass)
    if not tbl then return end
    for class, list in pairs(lists) do
        tbl[class .. "_F"] = list
        if byClass then tbl[class] = list end
    end
end
Put(SpellDB.CLASS_DEFENSIVE_DEFAULTS, DEFENSIVE)
Put(SpellDB.CLASS_PETHEAL_DEFAULTS, PET_HEAL, true)
Put(SpellDB.CLASS_PET_REZ_DEFAULTS, PET_REZ, true)
Put(SpellDB.CLASS_GROUP_HELP_DEFAULTS, GROUP_HELP)
Put(SpellDB.CLASS_GROUPHEAL_DEFAULTS, GROUP_HEAL)
Put(SpellDB.HEAL_EMERGENCY_LADDER, EMERGENCY)
Put(SpellDB.CLASS_GAPCLOSER_DEFAULTS, GAP_CLOSER)
Put(SpellDB.CLASS_BURST_TRIGGER_DEFAULTS, BURST)
Put(SpellDB.CLASS_TOPOFF_HEALS, TOPOFF, true)
-- Replaced whole: retail's groups (rogue poisons, Battle Shout) name retail ids or
-- retail behaviour.
wipe(SpellDB.CLASS_MAINTAINED_BUFFS)
for class, groups in pairs(MAINTAINED) do SpellDB.CLASS_MAINTAINED_BUFFS[class] = groups end
for _, id in ipairs(SHORT_BUFFS) do
    SpellDB.RAID_BUFF_SPELLS[id], SpellDB.UNIQUE_AURA_SPELLS[id] = nil, nil
end
if SpellDB.IndexMaintainedBuffs then SpellDB.IndexMaintainedBuffs() end
-- In place: RedundancyFilter holds a reference to the enchant set.
for _, id in ipairs(IMBUE_CASTS) do SpellDB.WEAPON_ENCHANT_SPELLS[id] = true end
SpellDB.WEAPON_IMBUE_SPELLS = IMBUES
SpellDB.RegisterInterruptAbilities(INTERRUPTS)
if SpellDB.RegisterSootheAbilities then
    local remove = {}
    for _, id in ipairs(SOOTHE_REMOVE) do remove[id] = false end
    SpellDB.RegisterSootheAbilities(remove)
end
SpellDB.RegisterRangeReferences(RANGE)
if SpellDB.RegisterDefenseTiers then SpellDB.RegisterDefenseTiers(TIERS) end
SpellDB.RegisterCategories(CATEGORIES)
SpellDB.RegisterChanneledSpells(CHANNELED)
-- Replaces retail's DoT list: its ids and durations are retail's.
SpellDB.RegisterTargetDots(DOTS)
for id in pairs(FRONTAL_DOTS) do SpellDB.FRONTAL_DOTS[id] = true end
for id in pairs(NEXT_SWING) do SpellDB.NEXT_SWING_SPELLS[id] = true end
