-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
--
-- JustAC: WoW Forever priority lists, per class and talent tree, with secret-safe
-- gates. GENERATED by tools/gen_forever_rotations.py - do not edit by hand.
--
-- Orderings and conditions derive from the wowsims rotation files of
-- github.com/ElliotWood/Forever (commit 6d6ea809a51cc845a8d50e9bfe608d8e63d59b43), vendored in tools/forever-apl-src/,
-- used under its license:
--
--   MIT License
--
--   Copyright (c) 2022 wowsims team
--
--   Permission is hereby granted, free of charge, to any person obtaining a copy
--   of this software and associated documentation files (the "Software"), to deal
--   in the Software without restriction, including without limitation the rights
--   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
--   copies of the Software, and to permit persons to whom the Software is
--   furnished to do so, subject to the following conditions:
--
--   The above copyright notice and this permission notice shall be included in all
--   copies or substantial portions of the Software.
--
--   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
--   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
--   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
--   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
--   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
--   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
--   SOFTWARE.
--
-- Trees marked pin: are JustAC hand pins (tools/simc-apl-forever/).
-- Keys: <CLASS>_F -> tree -> st / cleave / aoe (omitted = same as the next wider tier).
-- Ids are rank 1; rankChains lists every rank so the runtime can show the highest known.

local RotationImport = LibStub("JustAC-RotationImport", true)
if not RotationImport or not RotationImport.RegisterForever then return end

RotationImport.RegisterForever({
  ["DRUID_F"] = {
    default = "feral",
    balance = {  -- druid_balance__default
      st = {
        {id=29166,gates={{t="any",g={{t="power",res="mana",op="<=",n=30,ispct=true},{t="starved"}}}},w=true},  -- Innervate
        {id=8921,gates={{t="dot",id=8921}}},  -- Moonfire
        {id=5570,gates={{t="dot",id=5570}}},  -- Insect Swarm
        {id=2912,gates={}},  -- Starfire
      },
    },
    feral = {  -- druid_feralcat__default
      st = {
        {id=1822,gates={{t="dot",id=1822}}},  -- Rake
        {id=1322605,gates={{t="known",id=1322605},{t="power",res="energy",op="<=",n=60}}},  -- Shifting Power
        {id=6785,gates={{t="buff",id=5215}}},  -- Ravage
        {id=770,gates={{t="dot",id=770}}},  -- Faerie Fire
        {id=1079,gates={{t="resource",res="combo_points",op=">=",n=5},{t="dot",id=1079}}},  -- Rip
        {id=22568,gates={{t="resource",res="combo_points",op="=",n=5},{t="buff",id=16870,dur=15,neg=true}}},  -- Ferocious Bite
        {id=5221,gates={}},  -- Shred
        {id=1082,gates={}},  -- Claw
        {id=768,gates={{t="buff",id=768,neg=true}}},  -- Cat Form
      },
    },
    feral_bear = {  -- druid_feralbear__default
      st = {
        {id=770,gates={{t="dot",id=770}}},  -- Faerie Fire
        {id=99,gates={{t="dot",id=99}}},  -- Demoralizing Roar
        {id=407995,gates={}},  -- Primal Bite
        {id=414644,gates={{t="any",g={{t="stack",id=414644,op="<",n=5,tgt=true},{t="dot",id=414644}}}}},  -- Lacerate
        {id=6807,gates={{t="power",res="rage",op=">=",n=25}}},  -- Maul
        {id=414644,gates={}},  -- Lacerate
      },
      aoe = {
        {id=779,gates={}},  -- Swipe
        {id=770,gates={{t="dot",id=770}}},  -- Faerie Fire
        {id=99,gates={{t="dot",id=99}}},  -- Demoralizing Roar
        {id=407995,gates={}},  -- Primal Bite
        {id=414644,gates={{t="any",g={{t="stack",id=414644,op="<",n=5,tgt=true},{t="dot",id=414644}}}}},  -- Lacerate
        {id=6807,gates={{t="power",res="rage",op=">=",n=25}}},  -- Maul
        {id=414644,gates={}},  -- Lacerate
      },
    },
    restoration = {  -- pin:druid_restoration
      st = {
        {id=8921,gates={{t="dot",id=8921}}},  -- Moonfire
        {id=5176,gates={}},  -- Wrath
      },
    },
  },
  ["HUNTER_F"] = {
    default = "beast_mastery",
    beast_mastery = {  -- hunter_dps__bm
      st = {
        {id=1978,gates={{t="dot",id=1978},{t="power",res="mana",op=">=",n=30,ispct=true}}},  -- Serpent Sting
        {id=75,gates={}},  -- Auto Shot
        {id=1130,gates={{t="dot",id=1130}}},  -- Hunter's Mark
        {id=2973,gates={}},  -- Raptor Strike
        {id=1495,gates={}},  -- Mongoose Bite
        {id=3045,gates={{t="swing",op="<",n=0.1,ranged=true},{t="cd",id=19434}}},  -- Rapid Fire
        {id=19434,gates={{t="swing",op=">",n=1,ranged=true}}},  -- Aimed Shot
        {id=2643,gates={{t="swing",op=">",n=0.5,ranged=true}}},  -- Multi-Shot
        {id=1293241,gates={{t="swing",op=">",n=1,ranged=true}}},  -- Summon Hawk
      },
    },
    marksmanship = {  -- hunter_dps__mm
      st = {
        {id=1978,gates={{t="dot",id=1978},{t="cd",id=19434,neg=true},{t="cd",id=2643,neg=true},{t="power",res="mana",op=">=",n=30,ispct=true}}},  -- Serpent Sting
        {id=75,gates={}},  -- Auto Shot
        {id=1130,gates={{t="dot",id=1130}}},  -- Hunter's Mark
        {id=2973,gates={}},  -- Raptor Strike
        {id=1495,gates={}},  -- Mongoose Bite
        {id=3045,gates={{t="swing",op="<",n=0.1,ranged=true},{t="cd",id=19434}}},  -- Rapid Fire
        {id=19434,gates={{t="swing",op=">",n=1,ranged=true}}},  -- Aimed Shot
        {id=2643,gates={{t="swing",op=">",n=0.5,ranged=true}}},  -- Multi-Shot
        {id=1310687,gates={{t="swing",op=">",n=1,ranged=true},{t="cd",id=19434,neg=true},{t="cd",id=2643,neg=true}}},  -- Sniper Shot
        {id=3044,gates={{t="swing",op=">",n=0.5,ranged=true},{t="power",res="mana",op=">=",n=30,ispct=true},{t="cd",id=19434,neg=true}}},  -- Arcane Shot
      },
    },
    survival = {  -- hunter_dps__sv
      st = {
        {id=1978,gates={{t="dot",id=1978},{t="power",res="mana",op=">=",n=30,ispct=true}}},  -- Serpent Sting
        {id=75,gates={}},  -- Auto Shot
        {id=1130,gates={{t="dot",id=1130}}},  -- Hunter's Mark
        {id=2973,gates={}},  -- Raptor Strike
        {id=1495,gates={}},  -- Mongoose Bite
        {id=3045,gates={{t="swing",op="<",n=0.1,ranged=true},{t="cd",id=19434}}},  -- Rapid Fire
        {id=19434,gates={{t="swing",op=">",n=1,ranged=true}}},  -- Aimed Shot
        {id=2643,gates={{t="swing",op=">",n=0.5,ranged=true}}},  -- Multi-Shot
        {id=3044,gates={{t="swing",op=">",n=0.5,ranged=true},{t="power",res="mana",op=">=",n=30,ispct=true}}},  -- Arcane Shot
      },
    },
  },
  ["MAGE_F"] = {
    default = "frost",
    arcane = {  -- mage_dps__arcane
      st = {
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=15,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=2136,gates={{t="stack",id=400573,op=">=",n=2}}},  -- Fire Blast
        {id=5143,gates={{t="buff",id=44404}}},  -- Arcane Missiles
        {id=116,gates={{t="any",g={{t="stack",id=400573,op=">=",n=3},{t="power",res="mana",op="<",n=40,ispct=true}}}}},  -- Frostbolt
        {id=400574,gates={}},  -- Arcane Blast
        {id=116,gates={}},  -- Frostbolt
      },
      cleave = {
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=15,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=2136,gates={{t="stack",id=400573,op=">=",n=2}}},  -- Fire Blast
        {id=5143,gates={{t="buff",id=44404}}},  -- Arcane Missiles
        {id=116,gates={{t="any",g={{t="stack",id=400573,op=">=",n=3},{t="power",res="mana",op="<",n=40,ispct=true}}}}},  -- Frostbolt
        {id=400574,gates={}},  -- Arcane Blast
        {id=116,gates={}},  -- Frostbolt
      },
      aoe = {
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=15,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=1449,gates={{t="near",n=10}}},  -- Arcane Explosion
        {id=10,gates={}},  -- Blizzard
        {id=2136,gates={{t="stack",id=400573,op=">=",n=2}}},  -- Fire Blast
        {id=5143,gates={{t="buff",id=44404}}},  -- Arcane Missiles
        {id=116,gates={{t="any",g={{t="stack",id=400573,op=">=",n=3},{t="power",res="mana",op="<",n=40,ispct=true}}}}},  -- Frostbolt
        {id=400574,gates={}},  -- Arcane Blast
        {id=116,gates={}},  -- Frostbolt
      },
    },
    fire = {  -- mage_dps__fire
      st = {
        {id=11129,gates={{t="stack",id=22959,op=">=",n=5}}},  -- Combustion
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=20,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=11366,gates={{t="stack",id=400625,op="=",n=3}}},  -- Pyroblast
        {id=11366,gates={{t="stack",id=400625,op=">=",n=2},{t="buff",id=400625,dur=20,neg=true}},delegated=true},  -- Pyroblast
        {id=2136,gates={{t="any",g={{t="buff",id=12536,dur=15},{t="power",res="mana",op=">=",n=10,ispct=true}}}}},  -- Fire Blast
        {id=2948,gates={{t="any",g={{t="stack",id=22959,op="<",n=5},{t="buff",id=22959,dur=30,neg=true}}}},delegated=true},  -- Scorch
        {id=133,gates={{t="power",res="mana",op=">=",n=10,ispct=true}}},  -- Fireball
        {id=2948,gates={}},  -- Scorch
      },
      cleave = {
        {id=11129,gates={{t="stack",id=22959,op=">=",n=5}}},  -- Combustion
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=20,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=11366,gates={{t="stack",id=400625,op="=",n=3}}},  -- Pyroblast
        {id=11366,gates={{t="stack",id=400625,op=">=",n=2},{t="buff",id=400625,dur=20,neg=true}},delegated=true},  -- Pyroblast
        {id=2136,gates={{t="any",g={{t="buff",id=12536,dur=15},{t="power",res="mana",op=">=",n=10,ispct=true}}}}},  -- Fire Blast
        {id=2948,gates={{t="any",g={{t="stack",id=22959,op="<",n=5},{t="buff",id=22959,dur=30,neg=true}}}},delegated=true},  -- Scorch
        {id=133,gates={{t="power",res="mana",op=">=",n=10,ispct=true}}},  -- Fireball
        {id=2948,gates={}},  -- Scorch
      },
      aoe = {
        {id=11129,gates={{t="stack",id=22959,op=">=",n=5}}},  -- Combustion
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=20,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=11366,gates={{t="stack",id=400625,op="=",n=3}}},  -- Pyroblast
        {id=11366,gates={{t="stack",id=400625,op=">=",n=2},{t="buff",id=400625,dur=20,neg=true}},delegated=true},  -- Pyroblast
        {id=11113,gates={{t="near",n=10}}},  -- Blast Wave
        {id=2136,gates={{t="any",g={{t="buff",id=12536,dur=15},{t="power",res="mana",op=">=",n=10,ispct=true}}}}},  -- Fire Blast
        {id=2948,gates={{t="any",g={{t="stack",id=22959,op="<",n=5},{t="buff",id=22959,dur=30,neg=true}}}},delegated=true},  -- Scorch
        {id=2120,gates={}},  -- Flamestrike
        {id=133,gates={{t="power",res="mana",op=">=",n=10,ispct=true}}},  -- Fireball
        {id=2948,gates={}},  -- Scorch
      },
    },
    frost = {  -- mage_dps__frost
      st = {
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=20,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=1312002,gates={{t="buff",id=400669,dur=15}}},  -- Ice Lance
        {id=116,gates={}},  -- Frostbolt
      },
      cleave = {
        {id=120,gates={}},  -- Cone of Cold
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=20,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=1312002,gates={{t="buff",id=400669,dur=15}}},  -- Ice Lance
        {id=116,gates={}},  -- Frostbolt
      },
      aoe = {
        {id=120,gates={}},  -- Cone of Cold
        {id=12051,gates={{t="any",g={{t="power",res="mana",op="<",n=20,ispct=true},{t="starved"}}}},w=true},  -- Evocation
        {id=10,gates={}},  -- Blizzard
        {id=1312002,gates={{t="buff",id=400669,dur=15}}},  -- Ice Lance
        {id=116,gates={}},  -- Frostbolt
        {id=122,gates={}},  -- Frost Nova
      },
    },
  },
  ["PALADIN_F"] = {
    default = "retribution",
    holy = {  -- pin:paladin_holy
      st = {
        {id=20271,gates={}},  -- Judgement
        {id=679,gates={}},  -- Holy Strike
        {id=879,gates={}},  -- Exorcism
        {id=1311606,gates={}},  -- Holy Shock
      },
      aoe = {
        {id=20271,gates={}},  -- Judgement
        {id=679,gates={}},  -- Holy Strike
        {id=879,gates={}},  -- Exorcism
        {id=1311606,gates={}},  -- Holy Shock
        {id=26573,gates={}},  -- Consecration
      },
    },
    protection = {  -- paladin_protection__default
      st = {
        {id=20154,gates={{t="buff",id=20154,dur=30,neg=true}}},  -- Seal of Righteousness
        {id=20271,gates={}},  -- Judgement
        {id=26573,gates={}},  -- Consecration
        {id=679,gates={}},  -- Holy Strike
        {id=20925,gates={{t="buff",id=20128,dur=10}}},  -- Holy Shield
      },
    },
    retribution = {  -- paladin_retribution__default
      st = {
        {id=20375,gates={{t="buff",id=20375,dur=30,neg=true}}},  -- Seal of Command
        {id=20271,gates={}},  -- Judgement
        {id=20154,gates={{t="power",res="mana",op=">=",n=15,ispct=true},{t="swing",op="<",n=0.4},{t="buff",id=20375,dur=30}}},  -- Seal of Righteousness
        {id=20375,gates={{t="power",res="mana",op=">=",n=15,ispct=true},{t="swing",op="<",n=0.4},{t="buff",id=20154,dur=30}}},  -- Seal of Command
        {id=20154,gates={{t="buff",id=20375,dur=30,neg=true},{t="buff",id=20154,dur=30,neg=true}}},  -- Seal of Righteousness
        {id=24275,gates={}},  -- Hammer of Wrath
        {id=679,gates={}},  -- Holy Strike
        {id=26573,gates={{t="power",res="mana",op=">=",n=70,ispct=true}}},  -- Consecration
      },
    },
  },
  ["PRIEST_F"] = {
    default = "shadow",
    discipline = {  -- priest_dps__smite
      st = {
        {id=14914,gates={{t="dot",id=14914}}},  -- Holy Fire
        {id=14751,gates={}},  -- Inner Focus
        {id=585,gates={}},  -- Smite
        {id=402174,gates={}},  -- Penance
        {id=589,gates={{t="dot",id=589},{t="power",res="mana",op=">=",n=30,ispct=true}}},  -- Shadow Word: Pain
        {id=585,gates={{t="power",res="mana",op=">=",n=20,ispct=true}}},  -- Smite
      },
      aoe = {
        {id=15237,gates={}},  -- Holy Nova
        {id=14914,gates={{t="dot",id=14914}}},  -- Holy Fire
        {id=14751,gates={}},  -- Inner Focus
        {id=585,gates={}},  -- Smite
        {id=402174,gates={}},  -- Penance
        {id=589,gates={{t="dot",id=589},{t="power",res="mana",op=">=",n=30,ispct=true}}},  -- Shadow Word: Pain
        {id=585,gates={{t="power",res="mana",op=">=",n=20,ispct=true}}},  -- Smite
      },
    },
    holy = {  -- priest_dps__smite
      st = {
        {id=14914,gates={{t="dot",id=14914}}},  -- Holy Fire
        {id=14751,gates={}},  -- Inner Focus
        {id=585,gates={}},  -- Smite
        {id=402174,gates={}},  -- Penance
        {id=589,gates={{t="dot",id=589},{t="power",res="mana",op=">=",n=30,ispct=true}}},  -- Shadow Word: Pain
        {id=585,gates={{t="power",res="mana",op=">=",n=20,ispct=true}}},  -- Smite
      },
      aoe = {
        {id=15237,gates={}},  -- Holy Nova
        {id=14914,gates={{t="dot",id=14914}}},  -- Holy Fire
        {id=14751,gates={}},  -- Inner Focus
        {id=585,gates={}},  -- Smite
        {id=402174,gates={}},  -- Penance
        {id=589,gates={{t="dot",id=589},{t="power",res="mana",op=">=",n=30,ispct=true}}},  -- Shadow Word: Pain
        {id=585,gates={{t="power",res="mana",op=">=",n=20,ispct=true}}},  -- Smite
      },
    },
    shadow = {  -- priest_dps__shadow
      st = {
        {id=589,gates={{t="dot",id=589}}},  -- Shadow Word: Pain
        {id=14751,gates={}},  -- Inner Focus
        {id=2944,gates={}},  -- Devouring Plague
        {id=8092,gates={}},  -- Mind Blast
        {id=1309595,gates={}},  -- Shadow Word: Death
        {id=15407,gates={}},  -- Mind Flay
      },
      aoe = {
        {id=15237,gates={}},  -- Holy Nova
        {id=589,gates={{t="dot",id=589}}},  -- Shadow Word: Pain
        {id=14751,gates={}},  -- Inner Focus
        {id=2944,gates={}},  -- Devouring Plague
        {id=8092,gates={}},  -- Mind Blast
        {id=1309595,gates={}},  -- Shadow Word: Death
        {id=15407,gates={}},  -- Mind Flay
      },
    },
  },
  ["ROGUE_F"] = {
    default = "combat",
    assassination = {  -- rogue_dps__forever_mutilate
      st = {
        {id=1833,gates={{t="stealth"}}},  -- Cheap Shot
        {id=703,gates={{t="stealth"},{t="dot",id=703}}},  -- Garrote
        {id=5171,gates={{t="any",g={{t="all",g={{t="resource",res="combo_points",op=">=",n=1},{t="buff",id=5171,dur=6,neg=true}}},{t="all",g={{t="resource",res="combo_points",op=">=",n=5},{t="buff",id=5171,dur=6,neg=true}}}}}}},  -- Slice and Dice
        {id=14177,gates={{t="buff",id=5171,dur=6}}},  -- Cold Blood
        {id=2098,gates={{t="resource",res="combo_points",op=">=",n=4},{t="any",g={{t="buff",id=5171,dur=6},{t="power",res="energy",op=">=",n=79}}}}},  -- Eviscerate
        {id=1310707,gates={}},  -- Mutilate
      },
    },
    combat = {  -- rogue_dps__combat_sinister_strike
      st = {
        {id=1833,gates={{t="stealth"}}},  -- Cheap Shot
        {id=703,gates={{t="stealth"},{t="dot",id=703}}},  -- Garrote
        {id=5171,gates={{t="any",g={{t="all",g={{t="resource",res="combo_points",op=">=",n=1},{t="buff",id=5171,dur=6,neg=true}}},{t="all",g={{t="resource",res="combo_points",op=">=",n=5},{t="buff",id=5171,dur=6,neg=true}}}}}}},  -- Slice and Dice
        {id=13750,gates={{t="power",res="energy",op="<",n=59},{t="tick",op="<",n=1}}},  -- Adrenaline Rush
        {id=2098,gates={{t="resource",res="combo_points",op=">=",n=5},{t="any",g={{t="buff",id=5171,dur=6},{t="power",res="energy",op=">=",n=79}}}}},  -- Eviscerate
        {id=1752,gates={}},  -- Sinister Strike
      },
    },
    subtlety = {  -- rogue_dps__forever_hemorrhage
      st = {
        {id=1833,gates={{t="stealth"}}},  -- Cheap Shot
        {id=703,gates={{t="stealth"},{t="dot",id=703}}},  -- Garrote
        {id=5171,gates={{t="any",g={{t="all",g={{t="resource",res="combo_points",op=">=",n=1},{t="buff",id=5171,dur=6,neg=true}}},{t="all",g={{t="resource",res="combo_points",op=">=",n=5},{t="buff",id=5171,dur=6,neg=true}}}}}}},  -- Slice and Dice
        {id=1856,gates={{t="power",res="energy",op=">=",n=60},{t="resource",res="combo_points",op="<=",n=1},{t="buff",id=5171,dur=6}}},  -- Vanish
        {id=14183,gates={}},  -- Premeditation
        {id=8676,gates={}},  -- Ambush
        {id=1943,gates={{t="resource",res="combo_points",op=">=",n=3},{t="dot",id=1943}}},  -- Rupture
        {id=2098,gates={{t="resource",res="combo_points",op=">=",n=4},{t="any",g={{t="buff",id=5171,dur=6},{t="power",res="energy",op=">=",n=79}}}}},  -- Eviscerate
        {id=16511,gates={}},  -- Hemorrhage
      },
    },
  },
  ["SHAMAN_F"] = {
    default = "enhancement",
    elemental = {  -- shaman_elemental__forever
      st = {
        {id=3599,gates={{t="dot",id=3599}}},  -- Searing Totem
        {id=8050,gates={{t="dot",id=8050}}},  -- Flame Shock
        {id=408490,gates={}},  -- Lava Burst
        {id=421,gates={}},  -- Chain Lightning
        {id=403,gates={}},  -- Lightning Bolt
      },
      aoe = {
        {id=8190,gates={{t="dot",id=8190}}},  -- Magma Totem
        {id=8050,gates={{t="dot",id=8050}}},  -- Flame Shock
        {id=408490,gates={}},  -- Lava Burst
        {id=421,gates={}},  -- Chain Lightning
        {id=403,gates={}},  -- Lightning Bolt
      },
    },
    enhancement = {  -- shaman_enhancement__forever
      st = {
        {id=8075,gates={{t="buff",id=8075,dur=300,neg=true}}},  -- Strength of Earth Totem
        {id=8835,gates={{t="buff",id=8835,dur=300,neg=true}}},  -- Grace of Air Totem
        {id=3599,gates={{t="buff",id=3599,dur=30,neg=true}}},  -- Searing Totem
        {id=17364,gates={}},  -- Stormstrike
        {id=403,gates={{t="stack",id=408505,op=">=",n=5}}},  -- Lightning Bolt
        {id=8042,gates={}},  -- Earth Shock
      },
    },
    restoration = {  -- pin:shaman_restoration
      st = {
        {id=403,gates={}},  -- Lightning Bolt
      },
      cleave = {
        {id=403,gates={}},  -- Lightning Bolt
      },
      aoe = {
        {id=408341,gates={}},  -- Fire Nova
        {id=403,gates={}},  -- Lightning Bolt
      },
    },
  },
  ["WARLOCK_F"] = {
    default = "affliction",
    affliction = {  -- warlock_dps__affliction
      st = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=18288,gates={}},  -- Amplify Curse
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=18265,gates={{t="dot",id=18265}}},  -- Siphon Life
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=686,gates={}},  -- Shadow Bolt
      },
      cleave = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=18288,gates={}},  -- Amplify Curse
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=18265,gates={{t="dot",id=18265}}},  -- Siphon Life
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=686,gates={}},  -- Shadow Bolt
      },
      aoe = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=1949,gates={{t="near",n=10},{t="health",op=">",pct=50}},w=true},  -- Hellfire
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=18288,gates={}},  -- Amplify Curse
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=18265,gates={{t="dot",id=18265}}},  -- Siphon Life
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=5740,gates={}},  -- Rain of Fire
        {id=686,gates={}},  -- Shadow Bolt
      },
    },
    demonology = {  -- warlock_dps__demonic_pact
      st = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=686,gates={}},  -- Shadow Bolt
      },
      cleave = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=686,gates={}},  -- Shadow Bolt
      },
      aoe = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=1949,gates={{t="near",n=10},{t="health",op=">",pct=50}},w=true},  -- Hellfire
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=5740,gates={}},  -- Rain of Fire
        {id=686,gates={}},  -- Shadow Bolt
      },
    },
    destruction = {  -- warlock_dps__destruction
      st = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=1293817,gates={}},  -- Conflagrate
        {id=17877,gates={}},  -- Shadowburn
        {id=686,gates={}},  -- Shadow Bolt
      },
      cleave = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=1293817,gates={}},  -- Conflagrate
        {id=17877,gates={}},  -- Shadowburn
        {id=686,gates={}},  -- Shadow Bolt
      },
      aoe = {
        {id=1454,gates={{t="any",g={{t="power",res="mana",op="<",n=10,ispct=true},{t="starved"}}},{t="health",op=">",pct=50}},w=true},  -- Life Tap
        {id=1949,gates={{t="near",n=10},{t="health",op=">",pct=50}},w=true},  -- Hellfire
        {id=440892,gates={{t="dot",id=440892}}},  -- Curse of the Elements
        {id=603,gates={}},  -- Bane of Doom
        {id=980,gates={{t="known",id=603,neg=true},{t="dot",id=980}}},  -- Bane of Agony
        {id=172,gates={{t="dot",id=172}}},  -- Corruption
        {id=348,gates={{t="dot",id=348}}},  -- Immolate
        {id=1293817,gates={}},  -- Conflagrate
        {id=5740,gates={}},  -- Rain of Fire
        {id=17877,gates={}},  -- Shadowburn
        {id=686,gates={}},  -- Shadow Bolt
      },
    },
  },
  ["WARRIOR_F"] = {
    default = "arms",
    arms = {  -- warrior_dps__dps_battle
      st = {
        {id=6673,gates={{t="buff",id=6673,dur=180,neg=true}}},  -- Battle Shout
        {id=7386,gates={{t="stack",id=7386,op="<",n=1,tgt=true}}},  -- Sunder Armor
        {id=12328,gates={}},  -- Death Wish
        {id=5308,gates={{t="execute",op="<",pct=20}}},  -- Execute
        {id=7384,gates={}},  -- Overpower
        {id=12294,gates={}},  -- Mortal Strike
        {id=1310222,gates={}},  -- Spearing Strike
        {id=23881,gates={}},  -- Bloodthirst
        {id=772,gates={{t="dot",id=772}}},  -- Rend
        {id=1680,gates={{t="cd",id=23881,neg=true}}},  -- Whirlwind
        {id=1240193,gates={},delegated=true},  -- Slam
        {id=78,gates={{t="power",res="rage",op=">=",n=40}}},  -- Heroic Strike
        {id=1715,gates={{t="cd",id=23881,neg=true},{t="cd",id=1680,neg=true},{t="power",res="rage",op=">",n=80}}},  -- Hamstring
        {id=2687,gates={{t="power",res="rage",op="<",n=90},{t="health",op=">",pct=50}},w=true},  -- Bloodrage
        {id=2457,gates={{t="buff",id=2457,neg=true}}},  -- Battle Stance
      },
      aoe = {
        {id=6673,gates={{t="buff",id=6673,dur=180,neg=true}}},  -- Battle Shout
        {id=6343,gates={}},  -- Thunder Clap
        {id=1160,gates={{t="dot",id=1160}}},  -- Demoralizing Shout
        {id=7386,gates={{t="stack",id=7386,op="<",n=1,tgt=true}}},  -- Sunder Armor
        {id=12328,gates={}},  -- Death Wish
        {id=1680,gates={}},  -- Whirlwind
        {id=5308,gates={{t="execute",op="<",pct=20}}},  -- Execute
        {id=7384,gates={}},  -- Overpower
        {id=12294,gates={}},  -- Mortal Strike
        {id=1310222,gates={}},  -- Spearing Strike
        {id=23881,gates={}},  -- Bloodthirst
        {id=772,gates={{t="dot",id=772}}},  -- Rend
        {id=1680,gates={{t="cd",id=23881,neg=true}}},  -- Whirlwind
        {id=1240193,gates={},delegated=true},  -- Slam
        {id=845,gates={{t="power",res="rage",op=">=",n=40}}},  -- Cleave
        {id=1715,gates={{t="cd",id=23881,neg=true},{t="cd",id=1680,neg=true},{t="power",res="rage",op=">",n=80}}},  -- Hamstring
        {id=2687,gates={{t="power",res="rage",op="<",n=90},{t="health",op=">",pct=50}},w=true},  -- Bloodrage
        {id=2457,gates={{t="buff",id=2457,neg=true}}},  -- Battle Stance
      },
    },
    fury = {  -- warrior_dps__dps_reck
      st = {
        {id=6673,gates={{t="buff",id=6673,dur=180,neg=true}}},  -- Battle Shout
        {id=7386,gates={{t="stack",id=7386,op="<",n=1,tgt=true}}},  -- Sunder Armor
        {id=12328,gates={}},  -- Death Wish
        {id=5308,gates={{t="execute",op="<",pct=20}}},  -- Execute
        {id=12294,gates={}},  -- Mortal Strike
        {id=1310222,gates={}},  -- Spearing Strike
        {id=23881,gates={}},  -- Bloodthirst
        {id=1680,gates={{t="cd",id=23881,neg=true}}},  -- Whirlwind
        {id=1240193,gates={},delegated=true},  -- Slam
        {id=78,gates={{t="power",res="rage",op=">=",n=40}}},  -- Heroic Strike
        {id=1715,gates={{t="cd",id=23881,neg=true},{t="cd",id=1680,neg=true},{t="power",res="rage",op=">",n=80}}},  -- Hamstring
        {id=2687,gates={{t="power",res="rage",op="<",n=90},{t="health",op=">",pct=50}},w=true},  -- Bloodrage
        {id=2458,gates={{t="buff",id=2458,neg=true}}},  -- Berserker Stance
      },
      aoe = {
        {id=6673,gates={{t="buff",id=6673,dur=180,neg=true}}},  -- Battle Shout
        {id=6343,gates={}},  -- Thunder Clap
        {id=1160,gates={{t="dot",id=1160}}},  -- Demoralizing Shout
        {id=7386,gates={{t="stack",id=7386,op="<",n=1,tgt=true}}},  -- Sunder Armor
        {id=12328,gates={}},  -- Death Wish
        {id=1680,gates={}},  -- Whirlwind
        {id=5308,gates={{t="execute",op="<",pct=20}}},  -- Execute
        {id=12294,gates={}},  -- Mortal Strike
        {id=1310222,gates={}},  -- Spearing Strike
        {id=23881,gates={}},  -- Bloodthirst
        {id=1680,gates={{t="cd",id=23881,neg=true}}},  -- Whirlwind
        {id=1240193,gates={},delegated=true},  -- Slam
        {id=845,gates={{t="power",res="rage",op=">=",n=40}}},  -- Cleave
        {id=1715,gates={{t="cd",id=23881,neg=true},{t="cd",id=1680,neg=true},{t="power",res="rage",op=">",n=80}}},  -- Hamstring
        {id=2687,gates={{t="power",res="rage",op="<",n=90},{t="health",op=">",pct=50}},w=true},  -- Bloodrage
        {id=2458,gates={{t="buff",id=2458,neg=true}}},  -- Berserker Stance
      },
    },
    protection = {  -- warrior_protection__protection
      st = {
        {id=6673,gates={{t="buff",id=6673,dur=180,neg=true}}},  -- Battle Shout
        {id=71,gates={}},  -- Defensive Stance
        {id=23922,gates={}},  -- Shield Slam
        {id=6572,gates={}},  -- Revenge
        {id=6343,gates={}},  -- Thunder Clap
        {id=7386,gates={{t="stack",id=7386,op="<",n=5,tgt=true}}},  -- Sunder Armor
        {id=78,gates={{t="power",res="rage",op=">=",n=45}}},  -- Heroic Strike
        {id=7386,gates={}},  -- Sunder Armor
      },
      aoe = {
        {id=6673,gates={{t="buff",id=6673,dur=180,neg=true}}},  -- Battle Shout
        {id=1160,gates={{t="dot",id=1160}}},  -- Demoralizing Shout
        {id=71,gates={}},  -- Defensive Stance
        {id=23922,gates={}},  -- Shield Slam
        {id=6572,gates={}},  -- Revenge
        {id=6343,gates={}},  -- Thunder Clap
        {id=7386,gates={{t="stack",id=7386,op="<",n=5,tgt=true}}},  -- Sunder Armor
        {id=78,gates={{t="power",res="rage",op=">=",n=45}}},  -- Heroic Strike
        {id=7386,gates={}},  -- Sunder Armor
      },
    },
  },
}, {
  [10] = {10,6141,8427,10185,10186,10187},
  [17] = {17,592,600,3747,6065,6066,10898,10899,10900,10901},
  [53] = {53,2589,2590,2591,8721,11279,11280,11281,25300},
  [67] = {67,9452},
  [72] = {72,1671,1672},
  [78] = {78,284,285,1608,11564,11565,11566,11567,25286},
  [99] = {99,1735,9490,9747,9898},
  [100] = {100,6178,11578},
  [116] = {116,205,837,7322,8406,8407,8408,10179,10180,10181,25304},
  [118] = {118,12824,12825,12826,28271,28272},
  [120] = {120,8492,10159,10160,10161},
  [122] = {122,865,6131,10230},
  [132] = {132,2970,11743},
  [133] = {133,143,145,3140,8400,8401,8402,10148,10149,10150,10151,25306},
  [136] = {136,3111,3661,3662,13542,13543,13544},
  [139] = {139,6074,6075,6076,6077,6078,10927,10928,10929,25315},
  [168] = {168,7300,7301},
  [172] = {172,6222,6223,7648,11671,11672,25311},
  [324] = {324,26364,325,26365,905,26366,945,26367,8134,26369,10431,26370,10432,26363},
  [331] = {331,332,547,913,939,959,8005,10395,10396,25357},
  [339] = {339,1062,5195,5196,9852,9853},
  [348] = {348,707,1094,2941,11665,11667,11668,25309},
  [370] = {370,8012},
  [403] = {403,529,548,915,943,6041,10391,10392,15207,15208},
  [408] = {408,8643},
  [421] = {421,930,2860,10605},
  [453] = {453,8192,10953},
  [465] = {465,10290,643,10291,1032,10292,10293},
  [467] = {467,782,1075,8914,9756,9910},
  [468] = {468,16083},
  [471] = {471,16082},
  [498] = {498,5573},
  [527] = {527,988},
  [543] = {543,8457,8458,10223,10225},
  [579] = {579,16080},
  [585] = {585,591,598,984,1004,6060,10933,10934},
  [586] = {586,9578,9579,9592,10941,10942},
  [587] = {587,597,990,6129,10144,10145,28612},
  [588] = {588,7128,602,1006,10951,10952},
  [589] = {589,594,970,992,2767,10892,10893,10894},
  [596] = {596,996,10960,10961,25316},
  [604] = {604,8450,8451,10173,10174},
  [605] = {605,10911,10912},
  [633] = {633,2800,10310},
  [635] = {635,639,647,1026,1042,3472,10328,10329,25292},
  [642] = {642,1020},
  [679] = {679,678,1866,680,2495,5569,10332,10333},
  [686] = {686,695,705,1088,1106,7641,11659,11660,11661,25307},
  [687] = {687,696},
  [689] = {689,699,709,7651,11699,11700},
  [693] = {693,20752,20755,20756,20757},
  [694] = {694,7400,7402,20559,20560},
  [702] = {702,1108,6205,7646,11707,11708},
  [703] = {703,8631,8632,8633,11289,11290},
  [704] = {704,7658,7659,11717},
  [706] = {706,1086,11733,11734,11735},
  [710] = {710,18647},
  [724] = {724,27870,27871},
  [740] = {740,8918,9862,9863},
  [755] = {755,3698,3699,3700,11693,11694,11695},
  [770] = {770,778,9749,9907},
  [772] = {772,6546,6547,6548,11572,11573,11574},
  [774] = {774,1058,1430,2090,2091,3627,8910,9839,9840,9841,25299},
  [779] = {779,780,769,9754,9908},
  [781] = {781,14272,14273},
  [845] = {845,7369,11608,11609,20569},
  [853] = {853,5588,5589,10308},
  [879] = {879,5614,5615,10312,10313,10314},
  [976] = {976,10957,10958},
  [980] = {980,1014,6217,11711,11712,11713},
  [1008] = {1008,8455,10169,10170},
  [1022] = {1022,5599,10278},
  [1064] = {1064,10622,10623},
  [1079] = {1079,9492,9493,9752,9894,9896},
  [1082] = {1082,3029,5201,9849,9850},
  [1098] = {1098,11725,11726},
  [1120] = {1120,8288,8289,11675},
  [1126] = {1126,5232,6756,5234,8907,9884,9885},
  [1130] = {1130,14323,14324,14325},
  [1160] = {1160,6190,11554,11555,11556},
  [1243] = {1243,1244,1245,2791,10937,10938},
  [1449] = {1449,8437,8438,8439,10201,10202},
  [1454] = {1454,1455,1456,11687,11688,11689},
  [1459] = {1459,1460,1461,10156,10157},
  [1463] = {1463,8494,8495,10191,10192,10193},
  [1495] = {1495,14269,14270,14271},
  [1499] = {1499,14310,14311},
  [1510] = {1510,14294,14295},
  [1513] = {1513,14326,14327},
  [1515] = {1515,13481,13535},
  [1714] = {1714,11719},
  [1715] = {1715,7372,7373},
  [1742] = {1742,1747,1748,1749,1750,1751,1753,1754,1755,1756,16697,16698},
  [1752] = {1752,1757,1758,1759,1760,8621,11293,11294},
  [1766] = {1766,1767,1768,1769},
  [1776] = {1776,1777,8629,11285,11286},
  [1784] = {1784,1785,1786,1787},
  [1822] = {1822,1823,1824,9904},
  [1850] = {1850,9821},
  [1853] = {1853,14922,14923,14924,14925,14926,14927,2649,14916,14917,14918,14919,14920,14921},
  [1856] = {1856,1857},
  [1943] = {1943,8639,8640,11273,11274,11275},
  [1949] = {1949,11683,11684},
  [1966] = {1966,6768,8637,11303,25302},
  [1978] = {1978,13549,13550,13551,13552,13553,13554,13555,25295},
  [2006] = {2006,2010,10880,10881,20770},
  [2008] = {2008,20609,20610,20776,20777},
  [2050] = {2050,2052,2053},
  [2054] = {2054,2055,6063,6064},
  [2060] = {2060,10963,10964,10965,25314},
  [2061] = {2061,9472,9473,9474,10915,10916,10917},
  [2096] = {2096,10909},
  [2098] = {2098,6760,6761,6762,8623,8624,11299,11300,31016},
  [2120] = {2120,2121,8422,8423,10215,10216},
  [2136] = {2136,2137,2138,8412,8413,10197,10199},
  [2362] = {2362,17727,17728},
  [2382] = {2382,9125},
  [2637] = {2637,18657,18658},
  [2652] = {2652,2943,19249,19261,19251,19262,19252,19264,19253,19265,19254,19266},
  [2812] = {2812,10318},
  [2878] = {2878,5627,10326},
  [2908] = {2908,8955,9901},
  [2912] = {2912,8949,8950,8951,9875,9876,25298},
  [2944] = {2944,19276,19277,19278,19279,19280},
  [2948] = {2948,8444,8445,8446,10205,10206,10207},
  [2973] = {2973,14260,14261,14262,14263,14264,14265,14266},
  [2974] = {2974,14267,14268},
  [2975] = {2975,2976,2977,2980,2981,2982,3666,3667},
  [2983] = {2983,8696,11305},
  [3034] = {3034,14279,14280},
  [3044] = {3044,14281,14282,14283,14284,14285,14286,14287},
  [3365] = {3365,6247,6477,6478,21651},
  [3599] = {3599,6363,6364,6365,10437,10438},
  [3674] = {3674,14296},
  [4187] = {4187,4188,4189,4190,4191,4192,4193,4194,4195,4196,4197,4198,4199,4200,4201,4202,5041,5042,5048,5049},
  [5138] = {5138,6226,11703,11704},
  [5143] = {5143,5144,5145,8416,8417,10211,10212,25345},
  [5171] = {5171,6774},
  [5176] = {5176,5177,5178,5179,5180,6780,8905,9912},
  [5185] = {5185,5186,5187,5188,5189,6778,8903,9758,9888,9889,25297},
  [5211] = {5211,6798,8983},
  [5215] = {5215,6783,9913},
  [5221] = {5221,6800,8992,9829,9830},
  [5308] = {5308,20658,20660,20661,20662},
  [5394] = {5394,6375,6377,10462,10463},
  [5484] = {5484,17928},
  [5570] = {5570,24974,24975,24976,24977},
  [5675] = {5675,10495,10496,10497},
  [5676] = {5676,17919,17920,17921,17922,17923},
  [5730] = {5730,6390,6391,6392,10427,10428},
  [5740] = {5740,6219,11677,11678},
  [5782] = {5782,6213,6215},
  [6117] = {6117,22782,22783},
  [6143] = {6143,8461,8462,10177,28609},
  [6201] = {6201,6202,5699,11729,11730},
  [6229] = {6229,11739,11740,28610},
  [6233] = {6233,6246,21652},
  [6281] = {6281,6282,6283,6286,6280},
  [6311] = {6311,6314,6315,6316,6317},
  [6328] = {6328,6331,6332,6333,6334},
  [6343] = {6343,8198,8204,8205,11580,11581},
  [6353] = {6353,17924},
  [6366] = {6366,17951,17952,17953},
  [6443] = {6443,6444,6445,6446,6447},
  [6552] = {6552,6554},
  [6572] = {6572,6574,7379,11600,11601,25288},
  [6673] = {6673,5242,6192,11549,11550,11551,25289},
  [6770] = {6770,2070,11297},
  [6785] = {6785,6787,9866,9867},
  [6789] = {6789,17925,17926},
  [6807] = {6807,6808,6809,8972,9745,9880,9881},
  [6896] = {6896,17461},
  [6940] = {6940,20729},
  [7001] = {7001,27873,27874},
  [7294] = {7294,10298,10299,10300,10301},
  [7302] = {7302,7320,10219,10220},
  [7328] = {7328,10322,10324,20772,20773},
  [7370] = {7370,26184,26185,26186,26202,28343},
  [7384] = {7384,7887,11584,11585},
  [7386] = {7386,7405,8380,11596,11597},
  [8004] = {8004,8008,8010,10466,10467,10468},
  [8017] = {8017,8018,8019,10399,16314,16315,16316},
  [8024] = {8024,8027,8030,16339,16341,16342},
  [8033] = {8033,8038,10456,16355,16356},
  [8042] = {8042,8044,8045,8046,10412,10413,10414},
  [8050] = {8050,8052,8053,10447,10448,29228},
  [8056] = {8056,8058,10472,10473},
  [8071] = {8071,8154,8155,10406,10407,10408},
  [8075] = {8075,8160,8161,10442,25361},
  [8092] = {8092,8102,8103,8104,8105,8106,10945,10946,10947},
  [8122] = {8122,8124,10888,10890},
  [8129] = {8129,8131,10874,10875,10876},
  [8181] = {8181,10478,10479},
  [8184] = {8184,10537,10538},
  [8190] = {8190,10585,10586,10587},
  [8227] = {8227,8249,10526,16387},
  [8232] = {8232,8235,10486,16362},
  [8512] = {8512,10613,10614},
  [8647] = {8647,8649,8650,11197,11198},
  [8676] = {8676,8724,8725,11267,11268,11269},
  [8835] = {8835,10627,25359},
  [8921] = {8921,8924,8925,8926,8927,8928,8929,9833,9834,9835},
  [8936] = {8936,8938,8939,8940,8941,9750,9856,9857,9858},
  [8998] = {8998,9000,9892},
  [9005] = {9005,9823,9827},
  [9035] = {9035,19281,19282,19283,19284,19285},
  [9484] = {9484,9485,10955},
  [10595] = {10595,10600,10601},
  [10795] = {10795,17450,436289},
  [10797] = {10797,19296,19299,19302,19303,19304,19305},
  [11071] = {11071,12494},
  [11103] = {11103,12355},
  [11113] = {11113,13018,13019,13020,13021},
  [11366] = {11366,12505,12522,12523,12524,12525,12526,18809},
  [11426] = {11426,13031,13032,13033},
  [12281] = {12281,12284,12700},
  [12288] = {12288,12707,12708},
  [12290] = {12290,12963},
  [12294] = {12294,21551,21552,21553},
  [12302] = {12302,12765},
  [12307] = {12307,12944,12945},
  [12318] = {12318,12857,12858,12860,12861},
  [12322] = {12322,12964},
  [12324] = {12324,12876,12877,12878,12879},
  [12327] = {12327,12886},
  [13161] = {13161,1299445,1299446,1299447},
  [13165] = {13165,14318,14319,14320,14321,14322,25296},
  [13707] = {13707,13966,13967,13968,13969},
  [13709] = {13709,13706,13960},
  [13795] = {13795,14302,14303,14304,14305},
  [13797] = {13797,14298,14299,14300,14301},
  [13812] = {13812,14314,14315},
  [13813] = {13813,14316,14317},
  [13819] = {13819,1279399},
  [13896] = {13896,19271,19273,19274,19275},
  [13908] = {13908,19236,19238,19240,19241,19242,19243},
  [13976] = {13976,13977},
  [14076] = {14076,14094,14095},
  [14749] = {14749,14767},
  [14752] = {14752,14818,14819,27841},
  [14914] = {14914,15262,15263,15264,15265,15266,15267,15261},
  [15107] = {15107,15111,15112},
  [15237] = {15237,23455,15430,23458,15431,23459,27799,27803,27800,27804,27801,27805},
  [15268] = {15268,15323,15324,15325,15326},
  [15407] = {15407,17311,17312,17313,17314,18807},
  [15780] = {15780,17453},
  [16060] = {16060,436329,463006},
  [16180] = {16180,16196,16198},
  [16190] = {16190,17354,17359},
  [16253] = {16253,16298,16299,16300,16301},
  [16259] = {16259,16295},
  [16579] = {16579,16580,16581,16582},
  [16689] = {16689,16810,16811,16812,16813,17329},
  [16836] = {16836,16839,16840},
  [16858] = {16858,16859,16860,16861,16862},
  [16902] = {16902,16903,16904,16905,16906},
  [16914] = {16914,17401,17402},
  [17050] = {17050,17051,17053,17054,17055},
  [17079] = {17079,17082},
  [17254] = {17254,17262,17263,17264,17265,17266,17267,17268},
  [17458] = {17458,463005},
  [17815] = {17815,17833,17834,17835,17836},
  [17877] = {17877,18867,18868,18869,18870,18871},
  [18126] = {18126,18127},
  [18128] = {18128,18129},
  [18137] = {18137,28377,19308,28378,19309,28379,19310,28380,19311,28381,19312,28382},
  [18179] = {18179,18180,18181},
  [18265] = {18265,18879,18880,18881},
  [18310] = {18310,18311,18312,18313},
  [18544] = {18544,18547,18548,18549,18550},
  [18692] = {18692,18693},
  [18767] = {18767,18768},
  [18774] = {18774,18775},
  [18821] = {18821,18822,18823,18824,18825},
  [19151] = {19151,19152,19153},
  [19184] = {19184,19185},
  [19286] = {19286,19287},
  [19306] = {19306,1242634,20909,20910},
  [19381] = {19381,19382,19383,19384,19385},
  [19434] = {19434,20900,20901,20902,20903,20904},
  [19557] = {19557,19558},
  [19577] = {19577,24394},
  [19578] = {19578,24529,1310725},
  [19740] = {19740,19834,19835,19836,19837,19838,25291},
  [19742] = {19742,19850,19852,19853,19854,25290},
  [19750] = {19750,19939,19940,19941,19942,19943},
  [19870] = {19870,19871},
  [19876] = {19876,19895,19896},
  [19888] = {19888,19897,19898},
  [19891] = {19891,19899,19900},
  [19977] = {19977,19978,19979},
  [20042] = {20042,20045,20046,20047,20048},
  [20043] = {20043,20190},
  [20091] = {20091,20092},
  [20148] = {20148,20149,20150},
  [20154] = {20154,21084,20287,20288,20289,20290,20291,20292,20293},
  [20165] = {20165,20347,20348,20349},
  [20166] = {20166,20356,20357},
  [20244] = {20244,20245},
  [20249] = {20249,20250,20251},
  [20252] = {20252,20616,20617},
  [20335] = {20335,20336,20337},
  [20359] = {20359,20360,20361},
  [20375] = {20375,20915,20918,20919,20920},
  [20484] = {20484,20739,20742,20747,20748},
  [20608] = {20608,21169},
  [20736] = {20736,14274,15629,15630,15631,15632},
  [20925] = {20925,20927,20928},
  [21082] = {21082,20162,20305,20306,20307,20308},
  [21562] = {21562,21564},
  [21849] = {21849,21850},
  [22568] = {22568,22827,22828,22829,31018},
  [22842] = {22842,22845},
  [23100] = {23100,23111,23112},
  [23146] = {23146,23149,23150},
  [23163] = {23163,23166,23167},
  [23759] = {23759,23760,23761,23762,23785},
  [23881] = {23881,23892,23893,23894},
  [23922] = {23922,23923,23924,23925},
  [23992] = {23992,24439,24440,24441,24444,24445,24463,24464},
  [24118] = {24118,24119,24120,1299332},
  [24275] = {24275,24274,24239},
  [24294] = {24294,24295},
  [24406] = {24406,19572},
  [24424] = {24424,24580,24581,24582},
  [24446] = {24446,24447,24448,24449,24475,24476,24477,24478},
  [24451] = {24451,24454,24455},
  [24488] = {24488,24490,24505,24506,24507,24514,24515,24516},
  [24492] = {24492,24494,24502,24503,24504,24511,24512,24513},
  [24493] = {24493,24495,24497,24500,24501,24508,24509,24510},
  [24545] = {24545,24547,24549,24550,24551,24552,24553,24554,24555,24556,24557,24558,24559,24560,24561,24562,24629,24630,24631,24632},
  [24584] = {24584,24588,24589,24641},
  [24599] = {24599,24607,24608,24609},
  [24845] = {24845,25013,25014,25015,25016,25017},
  [25675] = {25675,25858,25859,434508},
  [25782] = {25782,25916},
  [25863] = {25863,26655},
  [25894] = {25894,25918},
  [26094] = {26094,26189,26190,1264456},
  [26573] = {26573,20116,20922,20923,20924},
  [27811] = {27811,27813},
  [29074] = {29074,29077},
  [29082] = {29082,29084,29086,29087,29088},
  [29189] = {29189,29191},
  [29192] = {29192,29193},
  [29441] = {29441,29442},
  [30160] = {30160,30165},
  [370637] = {370637,381598},
  [400574] = {400574,1239696,1239697,1239699,1239700},
  [401502] = {401502,1237312,1237313},
  [401859] = {401859,1240826,1240827},
  [401937] = {401937,1240770,1240771,1240772,1240773,1240774},
  [402174] = {402174,1240720,1240721,1316995},
  [407995] = {407995,1238069,1238070,1238073},
  [408120] = {408120,1238214,1238215},
  [408341] = {408341,408342,408343,408344,408345},
  [408490] = {408490,1238299,1238300},
  [408521] = {408521,1239242,1239243},
  [412758] = {412758,1293812,1293813},
  [414644] = {414644,1235826,1235827},
  [436288] = {436288,463007},
  [437138] = {437138,1237948,1237949,1237950,1237951},
  [440892] = {440892,1311676,1311677,1311680},
  [444680] = {444680,444682},
  [461607] = {461607,1237632},
  [468766] = {468766,5504,5505,5506,6127,10138,10139,10140},
  [473848] = {473848,473853,473855},
  [473858] = {473858,473859,473860},
  [473869] = {473869,473870,473871},
  [473874] = {473874,473875,473877},
  [473882] = {473882,473886,473887},
  [1217142] = {1217142,1217143,1217144},
  [1217146] = {1217146,1217147,1217148},
  [1217150] = {1217150,1217151,1217152},
  [1217154] = {1217154,1217155,1217156},
  [1240193] = {1240193,1464,8820,11604,11605},
  [1264727] = {1264727,1264729,1264730,1264731,1264732},
  [1264745] = {1264745,1264749,1264750,1264751,1264752},
  [1264937] = {1264937,1264939,1264970,1264971,1264972},
  [1265043] = {1265043,1265045,1265046,1265047,1265048},
  [1265059] = {1265059,1265060,1265061,1265062,1265064},
  [1265831] = {1265831,1265833,1265834,1265835,1265836},
  [1265887] = {1265887,1265888,1265890,1265891,1265892},
  [1265907] = {1265907,1265908,1265909,1265911,1265913},
  [1277324] = {1277324,1277325,1277326,1277327,1277328},
  [1277331] = {1277331,1277332,1277333,1277334,1277335},
  [1277370] = {1277370,1277371,1277372,1277374,1277376,1277377,1277378},
  [1277462] = {1277462,1277634,1277638,1277639,1277640},
  [1293241] = {1293241,1293525,1293526,1293527},
  [1293817] = {1293817,1293818,17962,18930,18931,18932},
  [1296017] = {1296017,1309965,1309973,1310029,1310030},
  [1299346] = {1299346,1299348,19506,20905,20906},
  [1309595] = {1309595,1309633,1309635,1309636},
  [1310687] = {1310687,1310785,1310786},
  [1310707] = {1310707,399956,1241582,1241584},
  [1310911] = {1310911,1311590,1311595},
  [1311606] = {1311606,20473,20929,20930},
  [1311649] = {1311649,1311656,20163,20419,20421,20422,20423},
  [1312002] = {1312002,400640,1240044,1240045,1240046,1240047},
}, {
  ["DRUID_F"] = {99,339,768,770,779,1079,1082,1822,1850,2912,5176,5221,5229,5487,5570,6603,6785,6807,7267,8921,9005,9634,16689,16914,20554,20572,22568,22812,22842,24858,29166,407995,414644,417141,1259799,1259812,1259813,1259817,1259821,1259823,1322605},
  ["HUNTER_F"] = {75,1002,1130,1495,1499,1510,1515,1543,1978,2643,2764,2973,2974,2975,3044,3045,3674,5384,6197,6603,7267,13795,13797,13809,13812,13813,17254,19263,19306,19434,19503,19574,20554,20572,24118,24424,24584,24845,26094,444680,1221404,1259799,1259812,1259813,1259817,1259821,1259823,1264727,1264745,1264937,1265043,1265059,1265831,1265887,1293241,1310687,1317257},
  ["MAGE_F"] = {10,116,120,122,130,133,543,1449,1463,1953,2120,2136,2948,5019,5143,6143,6603,7267,11113,11129,11366,11426,11958,12042,12043,12051,12536,20554,20572,24530,400574,401502,1259799,1259812,1259813,1259817,1259821,1259823,1312002},
  ["PALADIN_F"] = {498,642,679,879,2812,6603,7267,20154,20164,20165,20166,20271,20375,20554,20572,20925,21082,24275,26332,26573,407632,461607,1259799,1259812,1259813,1259817,1259821,1259823,1311015,1311606,1311649},
  ["PRIEST_F"] = {585,586,589,605,1706,2096,2651,2652,2944,5019,6603,7267,8092,10060,10797,13896,14751,14914,15237,15407,15473,18137,20554,20572,27828,401977,402174,1259799,1259812,1259813,1259817,1259821,1259823,1277324,1277331,1309595},
  ["ROGUE_F"] = {53,703,1752,1766,1776,1784,1833,1856,1943,2098,2480,2764,2983,5171,5277,6603,7267,7918,7919,8676,13750,13877,14177,14183,14251,14278,16511,20554,20572,438040,1259799,1259812,1259813,1259817,1259821,1259823,1310703,1310707},
  ["SHAMAN_F"] = {324,403,421,2484,3599,5394,5675,5730,6196,6495,6603,7267,8042,8050,8056,8071,8075,8143,8166,8170,8177,8181,8184,8190,8227,8512,8835,10595,15107,16190,17364,20554,20572,408341,408490,425336,437009,1259799,1259812,1259813,1259817,1259821,1259823},
  ["WARLOCK_F"] = {126,172,348,603,686,689,755,980,1120,1122,1454,1949,5019,5676,5740,6229,6353,6603,6789,7267,17877,18265,18288,18662,18708,20554,20572,412758,440892,1259799,1259812,1259813,1259817,1259821,1259823,1293817,1316697},
  ["WARRIOR_F"] = {71,72,78,694,772,845,871,1160,1680,1715,1719,2457,2458,2480,2565,2687,2764,5308,6343,6552,6572,6603,6673,7267,7384,7386,7918,7919,12292,12294,12328,18499,20230,20252,20554,20572,23881,23922,402927,1240193,1259799,1259812,1259813,1259817,1259821,1259823,1310222},
})
