-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Health-restoring consumables (potions, healthstones, health+mana pots).
--
-- GENERATED by tools/gen_healing_items.py from wago.tools DB2 dumps - discovered by EFFECT
-- (on-use spell restores health: direct, % of max health, or periodic), so oddly-named pots
-- and healthstones are all caught. Do not hand-edit; re-run each major patch after refreshing
-- Documentation/wow_spell_csv/. Order is newest-first, but ranking is done at runtime by
-- SpellDB.GetBestHealingItem (reads the tooltip's restored amount), so the list can be broad:
-- the owns-gate hides what you don't carry and weak pots never win the pick.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterHealingItems then return end

SpellDB.RegisterHealingItems({
    -- ── Midnight / current ──
    241298,  -- Amani Extract
    271884,  -- Concentrated Silvermoon Health Potion
    245918,  -- Fleeting Silvermoon Health Potion
    241306,  -- Refreshing Serum
    241304,  -- Silvermoon Health Potion
    241299,  -- Amani Extract
    271883,  -- Concentrated Silvermoon Health Potion
    245919,  -- Fleeting Silvermoon Health Potion
    241307,  -- Refreshing Serum
    241305,  -- Silvermoon Health Potion
    -- ── Dragonflight / TWW ──
    244849,  -- Fleeting Invigorating Healing Potion
    244839,  -- Invigorating Healing Potion
    244838,  -- Invigorating Healing Potion
    244835,  -- Invigorating Healing Potion
    211880,  -- Algari Healing Potion
    211879,  -- Algari Healing Potion
    211878,  -- Algari Healing Potion
    212244,  -- Cavedweller's Delight
    212944,  -- Fleeting Algari Healing Potion
    212950,  -- Fleeting Cavedweller's Delight
    212243,  -- Cavedweller's Delight
    212943,  -- Fleeting Algari Healing Potion
    212949,  -- Fleeting Cavedweller's Delight
    212242,  -- Cavedweller's Delight
    212942,  -- Fleeting Algari Healing Potion
    212948,  -- Fleeting Cavedweller's Delight
    221907,  -- Prototype: Tinker: Heartseeking Health Injector
    228417,  -- Emergency Healthstone
    -- ── Shadowlands ──
    207023,  -- Dreamwalker's Healing Potion
    207041,  -- Potion of Withering Dreams
    191371,  -- Potion of Withering Vitality
    191380,  -- Refreshing Healing Potion
    207022,  -- Dreamwalker's Healing Potion
    207040,  -- Potion of Withering Dreams
    191370,  -- Potion of Withering Vitality
    191379,  -- Refreshing Healing Potion
    207021,  -- Dreamwalker's Healing Potion
    207039,  -- Potion of Withering Dreams
    191369,  -- Potion of Withering Vitality
    191378,  -- Refreshing Healing Potion
    203461,  -- Chronologically Reallocated Rations
    -- ── Battle for Azeroth ──
    187802,  -- Cosmic Healing Potion
    180317,  -- Soulful Healing Potion
    171267,  -- Spiritual Healing Potion
    171269,  -- Spiritual Rejuvenation Potion
    175241,  -- Expedition Healing Potion
    177278,  -- Phial of Serenity
    187533,  -- Greater Phial of Serenity
    182188,  -- Lesser Phial of Serenity
    202088,  -- Powerful Flask of Renewal
    176409,  -- Rejuvenating Siphoned Essence
    -- ── Legion ──
    163770,  -- "Healthy" Chips
    169451,  -- Abyssal Healing Potion
    152494,  -- Coastal Healing Potion
    163082,  -- Coastal Rejuvenation Potion
    166799,  -- Emerald of Vigor
    167016,  -- Jade Brinestone Shard
    167797,  -- Jolt Jerky
    172494,  -- Baruk Idol
    166973,  -- Emergency Repair Kit
    -- ── Warlords of Draenor ──
    136569,  -- Aged Health Potion
    127834,  -- Ancient Healing Potion
    127836,  -- Ancient Rejuvenation Potion
    152615,  -- Astral Healing Potion
    132511,  -- Pump-Action Bandage Gun
    140351,  -- Sunfruit
    129196,  -- Legion Healthstone
    138486,  -- "Third Wind" Potion
    -- ── Mists of Pandaria ──
    115498,  -- Ashran Healing Tonic
    109226,  -- Draenic Rejuvenation Potion
    109223,  -- Healing Tonic
    113585,  -- Iron Horde Rejuvenation Potion
    -- ── Cataclysm ──
    88416,  -- Adrenaline Shot
    76094,  -- Alchemist's Rejuvenation
    93742,  -- Healing Potion
    76097,  -- Master Healing Potion
    217905,  -- Timerunner's Draught of Health
    -- ── Wrath ──
    63144,  -- Baradin's Wardens Healing Potion
    64994,  -- Hellscream's Reach Healing Potion
    57099,  -- Mysterious Potion
    57193,  -- Mighty Rejuvenation Potion
    67415,  -- Draught of War
    57191,  -- Mythical Healing Potion
    -- ── Burning Crusade ──
    33447,  -- Runic Healing Potion
    40077,  -- Crazy Alchemist's Potion
    43569,  -- Endless Healing Potion
    40081,  -- Potion of Nightmares
    40087,  -- Powerful Rejuvenation Potion
    39671,  -- Resurgent Healing Potion
    -- ── Classic ──
    22829,  -- Super Healing Potion
    34440,  -- Mad Alchemist's Potion
    22850,  -- Super Rejuvenation Potion
    29531,  -- Drums of Restoration
    31676,  -- Fel Regeneration Potion
    22836,  -- Major Dreamless Sleep Potion
    32947,  -- Auchenai Healing Potion
    32905,  -- Bottled Nethergon Vapor
    32904,  -- Cenarion Healing Salve
    33092,  -- Healing Potion Injector
    33934,  -- Crystal Healing Potion
    28100,  -- Volatile Healing Potion
    -- ── Classic / timeless ──
    156634,  -- Silas' Vial of Continuous Curing
    144396,  -- Valorous Healing Potion
    115466,  -- Elemental Fragment
    117415,  -- Smuggled Tonic
    80040,  -- Endless Master Healing Potion
    89640,  -- Life Spirit
    92979,  -- Mega-Potent Healing Potion
    63300,  -- Rogue's Draught
    41166,  -- Runic Healing Injector
    31838,  -- Major Combat Healing Potion
    31839,  -- Major Combat Healing Potion
    31852,  -- Major Combat Healing Potion
    31853,  -- Major Combat Healing Potion
    32784,  -- Red Ogre Brew
    32910,  -- Red Ogre Brew Special
    43531,  -- Argent Healing Potion
    23822,  -- Healing Potion Injector
    45277,  -- Jillian's Savior Sauce
    39327,  -- Noth's Special Brew
    32763,  -- Rulkster's Secret Sauce
    20002,  -- Greater Dreamless Sleep Potion
    18253,  -- Major Rejuvenation Potion
    15723,  -- Tea with Sugar
    17348,  -- Major Healing Draught
    11952,  -- Night Dragon's Breath
    14894,  -- Lily Root
    18839,  -- Combat Healing Potion
    12190,  -- Dreamless Sleep Potion
    17349,  -- Superior Healing Draught
    3928,  -- Superior Healing Potion
    9144,  -- Wildvine Potion
    17747,  -- Razorlash Root
    118,  -- Minor Healing Potion
    1710,  -- Greater Healing Potion
    1970,  -- Restoring Balm
    4596,  -- Discolored Healing Potion
    929,  -- Healing Potion
    858,  -- Lesser Healing Potion
    2456,  -- Minor Rejuvenation Potion
    224464,  -- Demonic Healthstone
    5512,  -- Healthstone
    23329,  -- Enriched Lasher Root
    168099,  -- Deepcoral Pod
    144262,  -- Fungal Lifestalk
    124661,  -- Gladiator's Healing Potion
    144276,  -- Sack of Healing Spores
    -- ── exp -3 ──
    13446,  -- Major Healing Potion
    124660,  -- Darkmoon Healing Tonic
    128647,  -- Fizzy Apple Cider
    258138,  -- Potent Healing Potion
    224021,  -- Survivalist's Healing Potion
})
