-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Pre-combat buff consumables (flasks, food, augment runes, weapon enchants).
--
-- GENERATED by tools/gen_precombat_buffs.py from wago.tools DB2 dumps - do not hand-edit
-- the generated categories. Re-run each major patch (see the script header). Items are
-- discovered by item class/subclass and their persistent buff aura is resolved from the
-- effect chain; `buff` is the aura spellID the addon checks for, `stat` is what it grants.
--
-- Source-aware: generated entries are bag items (source defaults to "item"). Toys
-- (source = "toy") and class self-buffs (source = "spell") are hand-added below the
-- HAND-CURATED marker and are preserved across regeneration only if you keep them there.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterPrecombatBuffs then return end

SpellDB.RegisterPrecombatBuffs({
    flask = {
        -- Midnight / current
        { id = 241320, buff = 1235057, stat = "versatility" },  -- Flask of Thalassian Resistance
        { id = 241324, buff = 1235110, stat = "haste" },  -- Flask of the Blood Knights
        { id = 241322, buff = 1235108, stat = "mastery" },  -- Flask of the Magisters
        { id = 241326, buff = 1235111, stat = "crit" },  -- Flask of the Shattered Sun
        { id = 245926, buff = 1235057, stat = "versatility" },  -- Fleeting Flask of Thalassian Resistance
        { id = 245931, buff = 1235110, stat = "haste" },  -- Fleeting Flask of the Blood Knights
        { id = 245933, buff = 1235108, stat = "mastery" },  -- Fleeting Flask of the Magisters
        { id = 245929, buff = 1235111, stat = "crit" },  -- Fleeting Flask of the Shattered Sun
        { id = 241310, buff = 1236767, stat = "primary" },  -- Haranir Phial of Finesse
        { id = 241312, buff = 1239755, stat = "primary" },  -- Haranir Phial of Ingenuity
        { id = 241316, buff = 1236763, stat = "primary" },  -- Haranir Phial of Perception
        { id = 241321, buff = 1235057, stat = "versatility" },  -- Flask of Thalassian Resistance
        { id = 241325, buff = 1235110, stat = "haste" },  -- Flask of the Blood Knights
        { id = 241323, buff = 1235108, stat = "mastery" },  -- Flask of the Magisters
        { id = 241327, buff = 1235111, stat = "crit" },  -- Flask of the Shattered Sun
        { id = 245927, buff = 1235057, stat = "versatility" },  -- Fleeting Flask of Thalassian Resistance
        { id = 245930, buff = 1235110, stat = "haste" },  -- Fleeting Flask of the Blood Knights
        { id = 245932, buff = 1235108, stat = "mastery" },  -- Fleeting Flask of the Magisters
        { id = 245928, buff = 1235111, stat = "crit" },  -- Fleeting Flask of the Shattered Sun
        { id = 241311, buff = 1236767, stat = "primary" },  -- Haranir Phial of Finesse
        { id = 241313, buff = 1239755, stat = "primary" },  -- Haranir Phial of Ingenuity
        { id = 241317, buff = 1236763, stat = "primary" },  -- Haranir Phial of Perception
        -- Dragonflight / TWW
        { id = 212283, buff = 432021, stat = "crit" },  -- Flask of Alchemical Chaos
        { id = 212271, buff = 431971, stat = "crit" },  -- Flask of Tempered Aggression
        { id = 212280, buff = 431974, stat = "mastery" },  -- Flask of Tempered Mastery
        { id = 212274, buff = 431972, stat = "haste" },  -- Flask of Tempered Swiftness
        { id = 212277, buff = 431973, stat = "versatility" },  -- Flask of Tempered Versatility
        { id = 212741, buff = 432021, stat = "crit" },  -- Fleeting Flask of Alchemical Chaos
        { id = 212728, buff = 431971, stat = "crit" },  -- Fleeting Flask of Tempered Aggression
        { id = 212738, buff = 431974, stat = "mastery" },  -- Fleeting Flask of Tempered Mastery
        { id = 212731, buff = 431972, stat = "haste" },  -- Fleeting Flask of Tempered Swiftness
        { id = 212734, buff = 431973, stat = "versatility" },  -- Fleeting Flask of Tempered Versatility
        { id = 212316, buff = 432286, stat = "primary" },  -- Phial of Bountiful Seasons
        { id = 212307, buff = 432306, stat = "primary" },  -- Phial of Concentrated Ingenuity
        { id = 212313, buff = 432304, stat = "primary" },  -- Phial of Enhanced Ambidexterity
        { id = 212310, buff = 432265, stat = "primary" },  -- Phial of Truesight
        { id = 212777, buff = 431971, stat = "crit" },  -- zzOldFleeting Flask of Tempered Aggression
        { id = 212282, buff = 432021, stat = "crit" },  -- Flask of Alchemical Chaos
        { id = 212270, buff = 431971, stat = "crit" },  -- Flask of Tempered Aggression
        { id = 212279, buff = 431974, stat = "mastery" },  -- Flask of Tempered Mastery
        { id = 212273, buff = 431972, stat = "haste" },  -- Flask of Tempered Swiftness
        { id = 212276, buff = 431973, stat = "versatility" },  -- Flask of Tempered Versatility
        { id = 212740, buff = 432021, stat = "crit" },  -- Fleeting Flask of Alchemical Chaos
        { id = 212727, buff = 431971, stat = "crit" },  -- Fleeting Flask of Tempered Aggression
        { id = 212736, buff = 431974, stat = "mastery" },  -- Fleeting Flask of Tempered Mastery
        { id = 212730, buff = 431972, stat = "haste" },  -- Fleeting Flask of Tempered Swiftness
        { id = 212733, buff = 431973, stat = "versatility" },  -- Fleeting Flask of Tempered Versatility
        { id = 212315, buff = 432286, stat = "primary" },  -- Phial of Bountiful Seasons
        { id = 212306, buff = 432306, stat = "primary" },  -- Phial of Concentrated Ingenuity
        { id = 212312, buff = 432304, stat = "primary" },  -- Phial of Enhanced Ambidexterity
        { id = 212309, buff = 432265, stat = "primary" },  -- Phial of Truesight
        { id = 212776, buff = 431971, stat = "crit" },  -- zzOldFleeting Flask of Tempered Aggression
        { id = 212281, buff = 432021, stat = "crit" },  -- Flask of Alchemical Chaos
        { id = 212269, buff = 431971, stat = "crit" },  -- Flask of Tempered Aggression
        { id = 212278, buff = 431974, stat = "mastery" },  -- Flask of Tempered Mastery
        { id = 212272, buff = 431972, stat = "haste" },  -- Flask of Tempered Swiftness
        { id = 212275, buff = 431973, stat = "versatility" },  -- Flask of Tempered Versatility
        { id = 212739, buff = 432021, stat = "crit" },  -- Fleeting Flask of Alchemical Chaos
        { id = 212725, buff = 431971, stat = "crit" },  -- Fleeting Flask of Tempered Aggression
        { id = 212735, buff = 431974, stat = "mastery" },  -- Fleeting Flask of Tempered Mastery
        { id = 212729, buff = 431972, stat = "haste" },  -- Fleeting Flask of Tempered Swiftness
        { id = 212732, buff = 431973, stat = "versatility" },  -- Fleeting Flask of Tempered Versatility
        { id = 212314, buff = 432286, stat = "primary" },  -- Phial of Bountiful Seasons
        { id = 212305, buff = 432306, stat = "primary" },  -- Phial of Concentrated Ingenuity
        { id = 212311, buff = 432304, stat = "primary" },  -- Phial of Enhanced Ambidexterity
        { id = 212308, buff = 432265, stat = "primary" },  -- Phial of Truesight
        { id = 212775, buff = 431971, stat = "crit" },  -- zzOldFleeting Flask of Tempered Aggression
        -- Shadowlands
        { id = 191344, buff = 395803, stat = "primary" },  -- Aerated Phial of Deftness
        { id = 197722, buff = 395802, stat = "primary" },  -- Aerated Phial of Quick Hands
        { id = 191350, buff = 371186, stat = "speed" },  -- Charged Phial of Alacrity
        { id = 191356, buff = 395804, stat = "primary" },  -- Crystalline Phial of Perception
        { id = 204669, buff = 371186, stat = "speed" },  -- Fleeting Charged Phial of Alacrity
        { id = 204666, buff = 371172, stat = "versatility" },  -- Fleeting Phial of Tepid Versatility
        { id = 191341, buff = 371172, stat = "versatility" },  -- Phial of Tepid Versatility
        { id = 191347, buff = 395805, stat = "primary" },  -- Steaming Phial of Finesse
        { id = 191343, buff = 395803, stat = "primary" },  -- Aerated Phial of Deftness
        { id = 197721, buff = 395802, stat = "primary" },  -- Aerated Phial of Quick Hands
        { id = 191349, buff = 371186, stat = "speed" },  -- Charged Phial of Alacrity
        { id = 191355, buff = 395804, stat = "primary" },  -- Crystalline Phial of Perception
        { id = 204668, buff = 371186, stat = "speed" },  -- Fleeting Charged Phial of Alacrity
        { id = 204665, buff = 371172, stat = "versatility" },  -- Fleeting Phial of Tepid Versatility
        { id = 191340, buff = 371172, stat = "versatility" },  -- Phial of Tepid Versatility
        { id = 191346, buff = 395805, stat = "primary" },  -- Steaming Phial of Finesse
        { id = 191342, buff = 395803, stat = "primary" },  -- Aerated Phial of Deftness
        { id = 197720, buff = 395802, stat = "primary" },  -- Aerated Phial of Quick Hands
        { id = 191348, buff = 371186, stat = "speed" },  -- Charged Phial of Alacrity
        { id = 191354, buff = 395804, stat = "primary" },  -- Crystalline Phial of Perception
        { id = 204667, buff = 371186, stat = "speed" },  -- Fleeting Charged Phial of Alacrity
        { id = 204664, buff = 371172, stat = "versatility" },  -- Fleeting Phial of Tepid Versatility
        { id = 191339, buff = 371172, stat = "versatility" },  -- Phial of Tepid Versatility
        { id = 191345, buff = 395805, stat = "primary" },  -- Steaming Phial of Finesse
        { id = 195580, buff = 379076, stat = "crit" },  -- Suspicious Bottle
        -- Battle for Azeroth
        { id = 171280, buff = 307166, stat = "primary" },  -- Eternal Flask
        { id = 171276, buff = 307185, stat = "primary" },  -- Spectral Flask of Power
        { id = 171278, buff = 307187, stat = "stamina" },  -- Spectral Flask of Stamina
        -- Legion
        { id = 152639, buff = 251837, stat = "intellect" },  -- Flask of Endless Fathoms
        { id = 152638, buff = 251836, stat = "agility" },  -- Flask of the Currents
        { id = 152641, buff = 251839, stat = "strength" },  -- Flask of the Undertow
        { id = 152640, buff = 251838, stat = "stamina" },  -- Flask of the Vast Horizon
        { id = 168652, buff = 298837, stat = "intellect" },  -- Greater Flask of Endless Fathoms
        { id = 168651, buff = 298836, stat = "agility" },  -- Greater Flask of the Currents
        { id = 168654, buff = 298841, stat = "strength" },  -- Greater Flask of the Undertow
        { id = 168653, buff = 298839, stat = "stamina" },  -- Greater Flask of the Vast Horizon
        -- Warlords of Draenor
        { id = 127850, buff = 188035, stat = "stamina" },  -- Flask of Ten Thousand Scars
        { id = 127849, buff = 188034, stat = "strength" },  -- Flask of the Countless Armies
        { id = 127848, buff = 188033, stat = "agility" },  -- Flask of the Seventh Demon
        { id = 127847, buff = 188031, stat = "intellect" },  -- Flask of the Whispered Pact
        -- Mists of Pandaria
        { id = 109145, buff = 156073, stat = "agility" },  -- Draenic Agility Flask
        { id = 109147, buff = 156070, stat = "intellect" },  -- Draenic Intellect Flask
        { id = 109152, buff = 156077, stat = "stamina" },  -- Draenic Stamina Flask
        { id = 109148, buff = 156071, stat = "strength" },  -- Draenic Strength Flask
        { id = 109153, buff = 156064, stat = "agility" },  -- Greater Draenic Agility Flask
        { id = 109155, buff = 156079, stat = "intellect" },  -- Greater Draenic Intellect Flask
        { id = 109160, buff = 156084, stat = "stamina" },  -- Greater Draenic Stamina Flask
        { id = 109156, buff = 156080, stat = "strength" },  -- Greater Draenic Strength Flask
        -- Cataclysm
        { id = 76086, buff = 105693, stat = "versatility" },  -- Flask of Falling Leaves
        { id = 76084, buff = 105689, stat = "agility" },  -- Flask of Spring Blossoms
        { id = 76088, buff = 105696, stat = "strength" },  -- Flask of Winter's Bite
        { id = 76087, buff = 105694, stat = "stamina" },  -- Flask of the Earth
        { id = 76085, buff = 105691, stat = "intellect" },  -- Flask of the Warm Sun
        -- Wrath
        { id = 67438, buff = 94160, stat = "versatility" },  -- Flask of Flowing Water
        { id = 58085, buff = 79469, stat = "stamina" },  -- Flask of Steelskin
        { id = 58088, buff = 79472, stat = "strength" },  -- Flask of Titanic Strength
        { id = 58086, buff = 79470, stat = "intellect" },  -- Flask of the Draconic Mind
        { id = 58087, buff = 79471, stat = "agility" },  -- Flask of the Winds
        -- Burning Crusade
        { id = 46377, buff = 53760 },  -- Flask of Endless Rage
        { id = 46378, buff = 54212, stat = "versatility" },  -- Flask of Pure Mojo
        -- Classic
        { id = 22851, buff = 28518 },  -- Flask of Fortification
        { id = 22853, buff = 28519, stat = "versatility" },  -- Flask of Mighty Versatility
        { id = 22854, buff = 28520 },  -- Flask of Relentless Assault
        { id = 32898, buff = 41607 },  -- Shattrath Flask of Fortification
        { id = 32899, buff = 41605, stat = "versatility" },  -- Shattrath Flask of Mighty Restoration
        { id = 32901, buff = 41606 },  -- Shattrath Flask of Relentless Assault
        { id = 32599, buff = 40577, stat = "agility" },  -- Unstable Flask of the Bandit
        { id = 32598, buff = 40580, stat = "agility" },  -- Unstable Flask of the Beast
        { id = 32596, buff = 40582, stat = "intellect" },  -- Unstable Flask of the Elder
        { id = 32600, buff = 40586, stat = "intellect" },  -- Unstable Flask of the Physician
        { id = 32597, buff = 40587, stat = "crit" },  -- Unstable Flask of the Soldier
        { id = 32601, buff = 40588, stat = "intellect" },  -- Unstable Flask of the Sorcerer
        -- Classic
        { id = 45006, buff = 53760 },  -- Jillian's Tonic of Endless Rage
        { id = 45007, buff = 54212, stat = "versatility" },  -- Jillian's Tonic of Pure Mojo
        { id = 32764, buff = 28518 },  -- Flaskataur's Celestial Brew
        { id = 32766, buff = 28519, stat = "versatility" },  -- Flaskataur's Flask of Flaskocity
        { id = 32765, buff = 28520 },  -- Flaskataur's Tears
        { id = 13511, buff = 17627, stat = "intellect" },  -- Flask of Distilled Wisdom
    },
    food = {
        -- Midnight / current
        { id = 242287, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Arcano Cutlets
        { id = 242296, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Bloodthistle-Wrapped Cutlets
        { id = 242276, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Braised Blood Hunter
        { id = 242280, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Buttered Root Crab
        { id = 242274, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Champion's Bento
        { id = 242277, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Crimson Calamari
        { id = 242292, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Eversong Pudding
        { id = 242286, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Fel-Kissed Filet
        { id = 242294, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Felberry Figs
        { id = 255848, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Flora Frenzy
        { id = 242291, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Fried Bloomtail
        { id = 242281, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Glitter Skewers
        { id = 242295, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearthflame Supper
        { id = 242759, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Arcano Cutlets
        { id = 242768, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Bloodthistle-Wrapped Cutlets
        { id = 242769, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Bloom Skewers
        { id = 242748, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Braised Blood Hunter
        { id = 242752, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Buttered Root Crab
        { id = 242746, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Champion's Bento
        { id = 242749, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Crimson Calamari
        { id = 242764, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Eversong Pudding
        { id = 242776, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Farstrider Rations
        { id = 242758, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Fel-Kissed Filet
        { id = 242766, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Felberry Figs
        { id = 268680, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Flora Frenzy
        { id = 242773, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Forager's Medley
        { id = 242763, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Fried Bloomtail
        { id = 242753, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Glitter Skewers
        { id = 242767, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Hearthflame Supper
        { id = 268679, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Impossibly Royal Roast
        { id = 242770, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Mana-Infused Stew
        { id = 242754, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Null and Void Plate
        { id = 242775, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Portable Snack
        { id = 275262, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Puffer Plate
        { id = 242774, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Quick Sandwich
        { id = 242747, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Royal Roast
        { id = 242772, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Silvermoon Standard
        { id = 242761, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Spellfire Filet
        { id = 242771, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Spiced Biscuits
        { id = 242755, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Sun-Seared Lumifin
        { id = 242765, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Sunwell Delight
        { id = 275263, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Sweet-And-Sour Skewers
        { id = 242750, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Tasty Smoked Tetra
        { id = 242760, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Twilight Angler's Medley
        { id = 275259, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Venom-Spiced Cutlets
        { id = 242756, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Void-Kissed Fish Rolls
        { id = 242757, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Warped Wise Wings
        { id = 242762, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Hearty Wise Tails
        { id = 255847, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Impossibly Royal Roast
        { id = 242282, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Null and Void Plate
        { id = 275260, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Puffer Plate
        { id = 242275, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Royal Roast
        { id = 242289, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Spellfire Filet
        { id = 242283, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Sun-Seared Lumifin
        { id = 242293, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Sunwell Delight
        { id = 275261, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Sweet-And-Sour Skewers
        { id = 242278, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Tasty Smoked Tetra
        { id = 242288, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Twilight Angler's Medley
        { id = 275258, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Venom-Spiced Cutlets
        { id = 242284, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Void-Kissed Fish Rolls
        { id = 242285, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Warped Wise Wings
        { id = 242290, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Wise Tails
        { id = 242298, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Argentleaf Tea
        { id = 242301, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Azeroot Tea
        { id = 242302, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Bloom Skewers
        { id = 242309, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Farstrider Rations
        { id = 242306, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Forager's Medley
        { id = 242297, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Mana Lily Tea
        { id = 242303, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Mana-Infused Stew
        { id = 242308, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Portable Snack
        { id = 242307, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Quick Sandwich
        { id = 242299, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Sanguithorn Tea
        { id = 242305, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Silvermoon Standard
        { id = 242304, buff = 1219179, stat = "crit+haste+mastery+versatility" },  -- Spiced Biscuits
        { id = 245573, buff = 1239149, stat = "versatility" },  -- Salmon
        -- Dragonflight / TWW
        { id = 225592, buff = 455369, stat = "speed" },  -- Exquisitely Eviscerated Muscle
        { id = 225855, buff = 456406, stat = "primary" },  -- Ghoulfish Delight
        { id = 222740, buff = 382235, stat = "stamina" },  -- Hearty Meals
        -- Shadowlands
        { id = 197783, buff = 382153, stat = "haste+versatility" },  -- Aromatic Seafood Platter
        { id = 197788, buff = 382234, stat = "stamina" },  -- Braised Bruffalon Brisket
        { id = 197774, buff = 382230, stat = "stamina" },  -- Charred Hornswog Steaks
        { id = 204072, buff = 396092, stat = "primary" },  -- Deviously Deviled Eggs
        { id = 197792, buff = 396092, stat = "primary" },  -- Fated Fortune Cookie
        { id = 197782, buff = 382152, stat = "crit+haste" },  -- Feisty Fish Sticks
        { id = 197779, buff = 382146, stat = "crit" },  -- Filet of Fangs
        { id = 202290, buff = 398458, stat = "crit+haste+mastery+versatility" },  -- Firewater Sorbet
        { id = 205684, buff = 410276, stat = "crit+haste+mastery+versatility" },  -- Forbidden Flounder
        { id = 197787, buff = 382157, stat = "mastery+versatility" },  -- Great Cerulean Sea
        { id = 197777, buff = 382246, stat = "stamina" },  -- Hopefully Healthy
        { id = 197785, buff = 382155, stat = "crit+versatility" },  -- Revenge, Served Cold
        { id = 197789, buff = 382235, stat = "stamina" },  -- Riverside Picnic
        { id = 197790, buff = 382236, stat = "stamina" },  -- Roast Duck Delight
        { id = 197781, buff = 382150, stat = "mastery" },  -- Salt-Baked Fishcake
        { id = 197791, buff = 382247, stat = "stamina" },  -- Salted Meat Mash
        { id = 197775, buff = 382231, stat = "stamina" },  -- Scrambled Basilisk Eggs
        { id = 197780, buff = 382149, stat = "versatility" },  -- Seamoth Surprise
        { id = 197784, buff = 382154, stat = "haste+mastery" },  -- Sizzling Seafood Medley
        { id = 197786, buff = 382156, stat = "crit+mastery" },  -- Thousandbone Tongueslicer
        { id = 197776, buff = 382232, stat = "stamina" },  -- Thrice-Spiced Mammoth Kabob
        { id = 197778, buff = 382145, stat = "haste" },  -- Timely Demise
        -- Battle for Azeroth
        { id = 182592, buff = 308434, stat = "crit" },  -- Infused Endmire Fruit
        { id = 190953, buff = 327707, stat = "stamina" },  -- Protofruit Flesh
        { id = 172069, buff = 308525, stat = "stamina" },  -- Banana Beef Pudding
        { id = 172040, buff = 308430, stat = "crit" },  -- Butterscotch Marinated Ribs
        { id = 172044, buff = 308474, stat = "haste" },  -- Cinnamon Bonefish Stew
        { id = 172049, buff = 308506, stat = "mastery" },  -- Iridescent Ravioli with Apple Sauce
        { id = 172048, buff = 308504, stat = "mastery" },  -- Meaty Apple Dumplings
        { id = 172068, buff = 308520, stat = "stamina" },  -- Pickled Meat Smoothie
        { id = 172041, buff = 308434, stat = "crit" },  -- Spinefin Souffle and Fries
        { id = 172051, buff = 308514, stat = "versatility" },  -- Steak a la Mode
        { id = 172050, buff = 308509, stat = "versatility" },  -- Sweet Silvergill Sausages
        { id = 172045, buff = 308488, stat = "haste" },  -- Tenebrous Crown Roast Aspic
        -- Legion
        { id = 154882, buff = 257410, stat = "crit" },  -- Honey-Glazed Haunches
        { id = 168232, buff = 296455, stat = "primary" },  -- Murloco's "Fish" Tacos
        { id = 154888, buff = 257420, stat = "mastery" },  -- Sailor's Pie
        { id = 166344, buff = 288075, stat = "stamina" },  -- Seasoned Steak and Potatoes
        { id = 154886, buff = 257424, stat = "versatility" },  -- Spiced Snapper
        { id = 163081, buff = 257422, stat = "versatility" },  -- Spicy Barbecued Buzzard Wing
        { id = 154884, buff = 257415, stat = "haste" },  -- Swamp Fish 'n Chips
        { id = 168311, buff = 297035, stat = "mastery" },  -- Abyssal-Fried Rissole
        { id = 168313, buff = 297034, stat = "haste" },  -- Baked Port Tato
        { id = 168314, buff = 297037, stat = "versatility" },  -- Bil'Tong
        { id = 168312, buff = 297040, stat = "stamina" },  -- Fragrant Kakavia
        { id = 154881, buff = 257408, stat = "crit" },  -- Kul Tiramisu
        { id = 154887, buff = 257418, stat = "mastery" },  -- Loa Loaf
        { id = 168310, buff = 297039, stat = "crit" },  -- Mech-Dowel's "Big Mech"
        { id = 154885, buff = 257422, stat = "versatility" },  -- Mon'Dazi
        { id = 154883, buff = 257413, stat = "haste" },  -- Ravenberry Tarts
        { id = 166343, buff = 288074, stat = "stamina" },  -- Wild Berry Bread
        { id = 167832, buff = 294365, stat = "speed" },  -- Canned Minnows
        -- Warlords of Draenor
        { id = 133571, buff = 225603, stat = "haste" },  -- Azshari Salad
        { id = 133567, buff = 225599, stat = "mastery" },  -- Barracuda Mrglgagh
        { id = 143635, buff = 225598, stat = "haste" },  -- Hasty Hummus
        { id = 133568, buff = 225600, stat = "versatility" },  -- Koi-Scented Stormray
        { id = 133565, buff = 225597, stat = "crit" },  -- Leybeque Ribs
        { id = 133572, buff = 225604, stat = "mastery" },  -- Nightborne Delicacy Platter
        { id = 133573, buff = 225605, stat = "versatility" },  -- Seed-Battered Fish Plate
        { id = 133566, buff = 225598, stat = "haste" },  -- Suramar Surf and Turf
        { id = 133570, buff = 225602, stat = "crit" },  -- The Hungry Magister
        { id = 133561, buff = 201330, stat = "haste" },  -- Deep-Fried Mossgill
        { id = 133563, buff = 201334, stat = "versatility" },  -- Faronaar Fizz
        { id = 133562, buff = 201332, stat = "mastery" },  -- Pickled Stormray
        { id = 133557, buff = 201223, stat = "crit" },  -- Salt and Pepper Shank
        -- Mists of Pandaria
        { id = 111433, buff = 160724, stat = "crit" },  -- Blackrock Ham
        { id = 111436, buff = 160793, stat = "mastery" },  -- Braised Riverbeast
        { id = 111438, buff = 160839, stat = "versatility" },  -- Clefthoof Sausages
        { id = 111444, buff = 160793, stat = "mastery" },  -- Fat Sleeper Cakes
        { id = 111445, buff = 160832, stat = "crit" },  -- Fiery Calamari
        { id = 111441, buff = 160724, stat = "crit" },  -- Grilled Gulper
        { id = 111431, buff = 160600, stat = "stamina" },  -- Hearty Elekk Steak
        { id = 111434, buff = 160726, stat = "haste" },  -- Pan-Seared Talbuk
        { id = 111437, buff = 160832, stat = "crit" },  -- Rylak Crepes
        { id = 111446, buff = 160839, stat = "versatility" },  -- Skulker Chowder
        { id = 111439, buff = 160600, stat = "stamina" },  -- Steamed Scorpion
        { id = 111442, buff = 160726, stat = "haste" },  -- Sturgeon Stew
        -- Cataclysm
        { id = 74646, buff = 104272, stat = "strength" },  -- Black Pepper Ribs and Shrimp
        { id = 74656, buff = 104283, stat = "stamina" },  -- Chun Tian Spring Rolls
        { id = 75038, buff = 105226, stat = "strength" },  -- Mad Brewer's Breakfast
        { id = 74650, buff = 104277, stat = "intellect" },  -- Mogu Fish Stew
        { id = 74648, buff = 104275, stat = "agility" },  -- Sea Mist Rice Noodles
        { id = 74653, buff = 104280, stat = "versatility" },  -- Steamed Crab Surprise
        { id = 74649, buff = 104276, stat = "intellect" },  -- Braised Turtle
        { id = 74642, buff = 104267, stat = "strength" },  -- Charbroiled Tiger Steak
        { id = 74645, buff = 104271, stat = "strength" },  -- Eternal Blossom Fish
        { id = 74652, buff = 104279, stat = "versatility" },  -- Fire Spirit Salmon
        { id = 86069, buff = 125108, stat = "haste" },  -- Rice Pudding
        { id = 74643, buff = 104273, stat = "agility" },  -- Sauteed Carrots
        { id = 74651, buff = 104278, stat = "versatility" },  -- Shrimp Dumplings
        { id = 74644, buff = 104264, stat = "intellect" },  -- Swirling Mist Soup
        { id = 74655, buff = 104282, stat = "stamina" },  -- Twin Fish Platter
        { id = 74647, buff = 104274, stat = "agility" },  -- Valley Stir Fry
        { id = 74654, buff = 104281, stat = "stamina" },  -- Wildfowl Roast
        -- Wrath
        { id = 62654, buff = 87634, stat = "haste" },  -- Lavascale Fillet
        -- Classic
        { id = 143634, buff = 225597, stat = "crit" },  -- Critical Catfish
        { id = 143633, buff = 225599, stat = "mastery" },  -- Masterful Mana Buns
        { id = 111449, buff = 160889, stat = "crit" },  -- Blackrock Barbecue
        { id = 122348, buff = 180748, stat = "haste" },  -- Buttered Sturgeon
        { id = 111453, buff = 160900, stat = "crit" },  -- Calamari Crepes
        { id = 111435, buff = 160778, stat = "versatility" },  -- Clefhoof Pot Roast
        { id = 111450, buff = 160893, stat = "haste" },  -- Frosty Stew
        { id = 118268, buff = 160793, stat = "mastery" },  -- Fuzzy Pear
        { id = 118272, buff = 160724, stat = "crit" },  -- Giant Nagrand Cherry
        { id = 111454, buff = 160902, stat = "versatility" },  -- Gorgrond Chowder
        { id = 118269, buff = 160832, stat = "crit" },  -- Greenskin Apple
        { id = 118271, buff = 160839, stat = "versatility" },  -- Ironpeel Plantain
        { id = 122346, buff = 180746, stat = "versatility" },  -- Jumbo Sea Dog
        { id = 118270, buff = 160726, stat = "haste" },  -- O'ruk Orange
        { id = 118274, buff = 174077, stat = "mastery" },  -- Perfect Fuzzy Pear
        { id = 118276, buff = 174080, stat = "crit" },  -- Perfect Greenskin Apple
        { id = 118277, buff = 174078, stat = "versatility" },  -- Perfect Ironpeel Plantain
        { id = 118275, buff = 174062, stat = "crit" },  -- Perfect Nagrand Cherry
        { id = 118273, buff = 174079, stat = "haste" },  -- Perfect O'ruk Orange
        { id = 122345, buff = 180745, stat = "crit" },  -- Pickled Eel
        { id = 120168, buff = 177931, stat = "versatility" },  -- Pre-Mixed Pot of Noodles
        { id = 111443, buff = 160778, stat = "versatility" },  -- Salted Skulker
        { id = 122344, buff = 180749, stat = "crit" },  -- Salty Squid Roll
        { id = 111452, buff = 160897, stat = "mastery" },  -- Sleeper Surprise
        { id = 122343, buff = 180750, stat = "mastery" },  -- Sleeper Sushi
        { id = 114982, buff = 169356 },  -- Song Flower
        { id = 114238, buff = 168349, stat = "versatility" },  -- Spiced Barbed Trout
        { id = 111451, buff = 160895, stat = "versatility" },  -- Starflower Sandwich
        { id = 111447, buff = 160883, stat = "stamina" },  -- Talador Surf and Turf
        { id = 122347, buff = 180747, stat = "stamina" },  -- Whiptail Fillet
        { id = 104340, buff = 124220 },  -- Crazy Snake Noodles
        { id = 98127, buff = 124219, stat = "mastery" },  -- Dented Can of Kaja'Cola
        { id = 101747, buff = 146807, stat = "versatility" },  -- Farmer's Delight
        { id = 101750, buff = 146804, stat = "strength" },  -- Fluffy Silkfeather Omelet
        { id = 104343, buff = 124216, stat = "haste" },  -- Golden Dragon Noodles
        { id = 94535, buff = 124219, stat = "mastery" },  -- Grilled Dinosaur Haunch
        { id = 79320, buff = 111840, stat = "stamina" },  -- Half a Lovely Apple
        { id = 104339, buff = 125071 },  -- Harmonious River Noodles
        { id = 105721, buff = 124219, stat = "mastery" },  -- Hot Papaya Milk
        { id = 104344, buff = 124218, stat = "crit" },  -- Lucky Mushroom Noodles
        { id = 101745, buff = 146809, stat = "mastery" },  -- Mango Ice
        { id = 81414, buff = 124219, stat = "mastery" },  -- Pearl Milk Tea
        { id = 101746, buff = 146805, stat = "agility" },  -- Seasoned Pomfruit Slices
        { id = 101748, buff = 146806, stat = "intellect" },  -- Spiced Blossom Soup
        { id = 104342, buff = 124218, stat = "crit" },  -- Spicy Mushan Noodles
        { id = 86073, buff = 125113 },  -- Spicy Salmon
        { id = 86074, buff = 125115, stat = "haste" },  -- Spicy Vegetable Chips
        { id = 104341, buff = 124217, stat = "haste" },  -- Steaming Goat Noodles
        { id = 101749, buff = 146808, stat = "stamina" },  -- Stuffed Lushrooms
        { id = 81406, buff = 124213, stat = "mastery" },  -- Roasted Barley Tea
        { id = 86070, buff = 125106, stat = "crit" },  -- Wildfowl Ginseng Soup
        { id = 70924, buff = 100368, stat = "intellect" },  -- Eternal Eye of Elune
        { id = 70925, buff = 100373, stat = "agility" },  -- Eternal Lunar Pear
        { id = 70926, buff = 100375, stat = "versatility" },  -- Eternal Moonberry
        { id = 70927, buff = 100377, stat = "strength" },  -- Eternal Sunfruit
        { id = 90457, buff = 131828, stat = "mastery" },  -- Mah's Warm Yak-Tail Stew
        { id = 89594, buff = 130356, stat = "intellect" },  -- Serpent Brew of Serenity
        { id = 89601, buff = 130348, stat = "agility" },  -- Tiger Brew of Serenity
        { id = 62661, buff = 87551, stat = "crit" },  -- Baked Rockfish
        { id = 62665, buff = 87552, stat = "haste" },  -- Basilisk Liverdog
        { id = 62670, buff = 87545, stat = "strength" },  -- Beer-Basted Crocolisk
        { id = 62668, buff = 87555 },  -- Blackbelly Sushi
        { id = 62655, buff = 87563, stat = "haste" },  -- Broiled Mountain Trout
        { id = 62664, buff = 87635, stat = "haste" },  -- Crocolisk Au Gratin
        { id = 62666, buff = 87548, stat = "versatility" },  -- Delicious Sagefish Tail
        { id = 62662, buff = 87550, stat = "crit" },  -- Grilled Dragon
        { id = 62659, buff = 87556, stat = "strength" },  -- Hearty Seafood Soup
        { id = 62663, buff = 87549, stat = "mastery" },  -- Lavascale Minestrone
        { id = 62651, buff = 87562, stat = "crit" },  -- Lightly Fried Lurker
        { id = 62657, buff = 87564 },  -- Lurker Lunch
        { id = 62667, buff = 87554 },  -- Mushroom Sauce Mudfish
        { id = 62660, buff = 87558, stat = "intellect" },  -- Pickled Guppy
        { id = 62653, buff = 87560, stat = "mastery" },  -- Salted Eye
        { id = 62652, buff = 87561, stat = "haste" },  -- Seasoned Crab
        { id = 89593, buff = 130355, stat = "intellect" },  -- Serpent Brew of Fallen Blossoms
        { id = 62671, buff = 87547, stat = "intellect" },  -- Severed Sagefish Head
        { id = 62669, buff = 87546, stat = "agility" },  -- Skewered Eel
        { id = 62658, buff = 87557, stat = "agility" },  -- Tender Baked Turtle
        { id = 89600, buff = 130347, stat = "agility" },  -- Tiger Brew of Fallen Blossoms
        { id = 62656, buff = 87559, stat = "versatility" },  -- Whitecrest Gumbo
        { id = 89592, buff = 130354, stat = "intellect" },  -- Serpent Brew of Meditation
        { id = 42779, buff = 53284, stat = "stamina" },  -- Steaming Chicken Soup
        { id = 89599, buff = 130346, stat = "agility" },  -- Tiger Brew of Meditation
        { id = 42942, buff = 57102, stat = "haste" },  -- Baked Manta Ray
        { id = 42999, buff = 57367, stat = "agility" },  -- Blackened Dragonfin
        { id = 42998, buff = 57365, stat = "versatility" },  -- Cuttlesteak
        { id = 43268, buff = 57294 },  -- Dalaran Clam Chowder
        { id = 43000, buff = 57371, stat = "strength" },  -- Dragonfin Filet
        { id = 34767, buff = 57327, stat = "stamina" },  -- Firecracker Salmon
        { id = 34762, buff = 57079 },  -- Grilled Sculpin
        { id = 42995, buff = 57358, stat = "crit" },  -- Hearty Rhino
        { id = 34769, buff = 57332, stat = "haste" },  -- Imperial Manta Steak
        { id = 34748, buff = 57111 },  -- Mammoth Meal
        { id = 34754, buff = 57325 },  -- Mega Mammoth Meal
        { id = 34758, buff = 57334, stat = "versatility" },  -- Mighty Rhino Dogs
        { id = 34765, buff = 57107, stat = "versatility" },  -- Pickled Fangtooth
        { id = 34764, buff = 57100, stat = "crit" },  -- Poached Nettlefish
        { id = 34766, buff = 57325 },  -- Poached Northern Sculpin
        { id = 34752, buff = 57291, stat = "versatility" },  -- Rhino Dogs
        { id = 42994, buff = 57356, stat = "haste" },  -- Rhinolicious Wormsteak
        { id = 34751, buff = 57288, stat = "haste" },  -- Roasted Worg
        { id = 34125, buff = 57288, stat = "haste" },  -- Shoveltusk Soup
        { id = 34749, buff = 57139, stat = "stamina" },  -- Shoveltusk Steak
        { id = 34763, buff = 57097, stat = "stamina" },  -- Smoked Salmon
        { id = 42996, buff = 57360, stat = "haste" },  -- Snapper Extreme
        { id = 34756, buff = 57329, stat = "crit" },  -- Spiced Worm Burger
        { id = 34768, buff = 57329, stat = "crit" },  -- Spicy Blue Nettlefish
        { id = 42993, buff = 57334, stat = "versatility" },  -- Spicy Fried Herring
        { id = 39691, buff = 57286, stat = "crit" },  -- Succulent Orca Stew
        { id = 34755, buff = 57327, stat = "stamina" },  -- Tender Shoveltusk Steak
        { id = 34757, buff = 57332, stat = "haste" },  -- Very Burnt Worg
        { id = 44953, buff = 57360, stat = "haste" },  -- Worg Tartare
        { id = 34750, buff = 57286, stat = "crit" },  -- Worm Delight
        { id = 33052, buff = 33257, stat = "stamina" },  -- Fisherman's Feast
        { id = 30358, buff = 33261, stat = "agility" },  -- Oronok's Tuber of Agility
        { id = 30357, buff = 33268, stat = "versatility" },  -- Oronok's Tuber of Healing
        { id = 30361, buff = 33263, stat = "versatility" },  -- Oronok's Tuber of Spell Power
        { id = 30359, buff = 33256, stat = "strength" },  -- Oronok's Tuber of Strength
        { id = 89591, buff = 130353, stat = "intellect" },  -- Serpent Brew of Pilgrimage
        { id = 33825, buff = 43722, stat = "crit" },  -- Skullfish Soup
        { id = 33872, buff = 43764, stat = "haste" },  -- Spicy Hot Talbuk
        { id = 89598, buff = 130345, stat = "agility" },  -- Tiger Brew of Pilgrimage
        { id = 27657, buff = 33263, stat = "versatility" },  -- Blackened Basilisk
        { id = 27663, buff = 33265, stat = "stamina" },  -- Blackened Sporefish
        { id = 33867, buff = 33254, stat = "stamina" },  -- Broiled Bloodfin
        { id = 27651, buff = 33254, stat = "stamina" },  -- Buzzard Bites
        { id = 30155, buff = 33254, stat = "stamina" },  -- Clam Bar
        { id = 31673, buff = 33263, stat = "versatility" },  -- Crunchy Serpent
        { id = 27662, buff = 33254, stat = "stamina" },  -- Feltail Delight
        { id = 27666, buff = 33268, stat = "versatility" },  -- Golden Fish Sticks
        { id = 27664, buff = 33261, stat = "agility" },  -- Grilled Mudfish
        { id = 140342, buff = 35272, stat = "stamina" },  -- Lean - Mok'Nathal Shortribs
        { id = 31672, buff = 35272, stat = "stamina" },  -- Mok'Nathal Shortribs
        { id = 27665, buff = 33263, stat = "versatility" },  -- Poached Bluefish
        { id = 27655, buff = 33259 },  -- Ravager Dog
        { id = 27658, buff = 33256, stat = "strength" },  -- Roasted Clefthoof
        { id = 89590, buff = 130352, stat = "intellect" },  -- Serpent Brew of Adversity
        { id = 27667, buff = 33257, stat = "stamina" },  -- Spicy Crawdad
        { id = 27660, buff = 35272, stat = "stamina" },  -- Talbuk Steak
        { id = 89597, buff = 130344, stat = "agility" },  -- Tiger Brew of Adversity
        { id = 27659, buff = 33261, stat = "agility" },  -- Warp Burger
        { id = 89589, buff = 130351, stat = "intellect" },  -- Initiate's Serpent Brew
        { id = 89596, buff = 130343, stat = "agility" },  -- Initiate's Tiger Brew
        { id = 33004, buff = 64057 },  -- Clamlette Magnifique
        { id = 89588, buff = 130350, stat = "intellect" },  -- Novice's Serpent Brew
        { id = 89595, buff = 130342, stat = "agility" },  -- Novice's Tiger Brew
        { id = 184682, buff = 347173, stat = "versatility" },  -- Extra Lemony Herb Filet
        { id = 126934, buff = 185736, stat = "versatility" },  -- Lemon Herb Filet
        -- exp -3
        { id = 34411, buff = 45245, stat = "stamina" },  -- Hot Apple Cider
        { id = 21254, buff = 110645, stat = "primary" },  -- Winter Veil Cookie
        { id = 210842, buff = 226807, stat = "versatility" },  -- Fresh Fig
        { id = 210841, buff = 226805, stat = "mastery" },  -- Buttered Oysters
        { id = 44839, buff = 65410, stat = "haste" },  -- Candied Sweet Potato
        { id = 116405, buff = 65412, stat = "stamina" },  -- Congealed Cranberry Chutney
        { id = 44840, buff = 226807, stat = "versatility" },  -- Cranberry Chutney
        { id = 116409, buff = 175785, stat = "crit" },  -- Gourmet Pumpkin Pie
        { id = 116408, buff = 175784, stat = "stamina" },  -- Herb-Infused Stuffing
        { id = 44836, buff = 175785, stat = "crit" },  -- Pumpkin Pie
        { id = 44838, buff = 226805, stat = "mastery" },  -- Slow-Roasted Turkey
        { id = 116407, buff = 65414 },  -- Slow-Smoked Turkey
        { id = 44837, buff = 175784, stat = "stamina" },  -- Spice Bread Stuffing
        { id = 116406, buff = 65410, stat = "haste" },  -- Twice-Baked Sweet Potato
    },
    augmentRune = {
        -- Midnight / current
        { id = 259085, buff = 1264426, stat = "primary" },  -- Void-Touched Augment Rune
        -- Dragonflight / TWW
        { id = 224572, buff = 453250, stat = "primary" },  -- Crystallized Augment Rune
        { id = 243191, buff = 1234969, stat = "primary" },  -- Ethereal Augment Rune
        { id = 246492, buff = 1242347, stat = "primary" },  -- Soulgorged Augment Rune
        -- Shadowlands
        { id = 201325, buff = 393438, stat = "agility" },  -- Draconic Augment Rune
        { id = 211495, buff = 393438, stat = "agility" },  -- Dreambound Augment Rune
        -- Battle for Azeroth
        { id = 181468, buff = 347901, stat = "agility" },  -- Veiled Augment Rune
        -- Legion
        { id = 190384, buff = 367405, stat = "agility" },  -- Eternal Augment Rune
        { id = 160053, buff = 270058, stat = "agility" },  -- Battle-Scarred Augment Rune
        { id = 174906, buff = 317065, stat = "agility" },  -- Lightning-Forged Augment Rune
        -- Warlords of Draenor
        { id = 153023, buff = 284307, stat = "agility" },  -- Lightforged Augment Rune
        -- Classic
        { id = 140587, buff = 224001, stat = "agility" },  -- Defiled Augment Rune
        { id = 118632, buff = 175457, stat = "intellect" },  -- Focus Augment Rune
        { id = 118630, buff = 175456, stat = "agility" },  -- Hyper Augment Rune
        { id = 118631, buff = 175439, stat = "strength" },  -- Stout Augment Rune
        -- exp -3
        { id = 274797, buff = 1295329, stat = "primary" },  -- Tidesworn Augment Rune
    },
    weaponEnchant = {
        -- Midnight / current
        { id = 243736, buff = 1237001, stat = "caster", wmask = 983039 },  -- Oil of Dawn
        { id = 237373, buff = 1224335, stat = "physical" },  -- Refulgent Razorstone
        { id = 237369, buff = 1224333, stat = "physical", wmask = 9264 },  -- Refulgent Weightstone
        { id = 237371, buff = 1224328, stat = "physical", wmask = 41923 },  -- Refulgent Whetstone
        { id = 243734, buff = 1237006, stat = "caster", wmask = 983039 },  -- Thalassian Phoenix Oil
        { id = 243735, buff = 1237002, stat = "caster", wmask = 983039 },  -- Oil of Dawn
        { id = 237372, buff = 1224334, stat = "physical" },  -- Refulgent Razorstone
        { id = 237367, buff = 1224332, stat = "physical", wmask = 9264 },  -- Refulgent Weightstone
        { id = 237370, buff = 1224331, stat = "physical", wmask = 41923 },  -- Refulgent Whetstone
        { id = 243733, buff = 1237008, stat = "caster", wmask = 983039 },  -- Thalassian Phoenix Oil
        -- Dragonflight / TWW
        { id = 220156, buff = 444755, stat = "caster", wmask = 720883 },  -- Bubbling Wax
        { id = 222507, buff = 458931, stat = "physical" },  -- Ironclaw Razorstone
        { id = 222510, buff = 458937, stat = "physical", wmask = 9264 },  -- Ironclaw Weightstone
        { id = 222504, buff = 458934, stat = "physical", wmask = 41923 },  -- Ironclaw Whetstone
        { id = 222506, buff = 458930, stat = "physical" },  -- Ironclaw Razorstone
        { id = 222509, buff = 458936, stat = "physical", wmask = 9264 },  -- Ironclaw Weightstone
        { id = 222503, buff = 458933, stat = "physical", wmask = 41923 },  -- Ironclaw Whetstone
        { id = 222505, buff = 458929, stat = "physical" },  -- Ironclaw Razorstone
        { id = 222508, buff = 458935, stat = "physical", wmask = 9264 },  -- Ironclaw Weightstone
        { id = 222502, buff = 458932, stat = "physical", wmask = 41923 },  -- Ironclaw Whetstone
        { id = 224105, buff = 451869, stat = "caster", wmask = 983039 },  -- Algari Mana Oil
        { id = 224106, buff = 451873, stat = "caster", wmask = 983039 },  -- Algari Mana Oil
        { id = 224107, buff = 451874, stat = "caster", wmask = 983039 },  -- Algari Mana Oil
        { id = 224108, buff = 451926, stat = "caster", wmask = 983039 },  -- Oil of Beledar's Grace
        { id = 224109, buff = 451925, stat = "caster", wmask = 983039 },  -- Oil of Beledar's Grace
        { id = 224110, buff = 451927, stat = "caster", wmask = 983039 },  -- Oil of Beledar's Grace
        { id = 224111, buff = 451882, stat = "caster", wmask = 983039 },  -- Oil of Deep Toxins
        { id = 224112, buff = 451901, stat = "caster", wmask = 983039 },  -- Oil of Deep Toxins
        { id = 224113, buff = 451902, stat = "caster", wmask = 983039 },  -- Oil of Deep Toxins
        -- Shadowlands
        { id = 191950, buff = 371681, stat = "physical" },  -- Primal Razorstone
        { id = 191944, buff = 371677, stat = "physical", wmask = 9264 },  -- Primal Weightstone
        { id = 191940, buff = 396157, stat = "physical", wmask = 41923 },  -- Primal Whetstone
        { id = 191949, buff = 371680, stat = "physical" },  -- Primal Razorstone
        { id = 191945, buff = 371678, stat = "physical", wmask = 9264 },  -- Primal Weightstone
        { id = 191933, buff = 396155, stat = "physical", wmask = 41923 },  -- Primal Whetstone
        { id = 191948, buff = 371641, stat = "physical" },  -- Primal Razorstone
        { id = 191943, buff = 371676, stat = "physical", wmask = 9264 },  -- Primal Weightstone
        { id = 191939, buff = 396156, stat = "physical", wmask = 41923 },  -- Primal Whetstone
        -- Battle for Azeroth
        { id = 171436, buff = 322749, stat = "physical", wmask = 41923 },  -- Porous Sharpening Stone
        { id = 171438, buff = 322761, stat = "physical", wmask = 9264 },  -- Porous Weightstone
        { id = 171437, buff = 322762, stat = "physical", wmask = 41923 },  -- Shaded Sharpening Stone
        { id = 171439, buff = 322763, stat = "physical", wmask = 9264 },  -- Shaded Weightstone
        -- Classic
        { id = 23529, buff = 29453, stat = "physical", wmask = 33731 },  -- Adamantite Sharpening Stone
        { id = 28421, buff = 34340, stat = "physical", wmask = 9264 },  -- Adamantite Weightstone
        { id = 22522, buff = 28017, stat = "caster" },  -- Superior Wizard Oil
        { id = 23528, buff = 29452, stat = "physical", wmask = 33731 },  -- Fel Sharpening Stone
        { id = 28420, buff = 34339, stat = "physical", wmask = 9264 },  -- Fel Weightstone
        { id = 22521, buff = 28013, stat = "caster" },  -- Superior Mana Oil
        -- Classic
        { id = 31535, buff = 38615, stat = "physical", wmask = 174067 },  -- Bloodboil Poison
        { id = 36899, buff = 47904, stat = "caster" },  -- Exceptional Mana Oil
        { id = 18262, buff = 22756, stat = "physical", wmask = 41923 },  -- Elemental Sharpening Stone
        { id = 23123, buff = 28898, stat = "caster" },  -- Blessed Wizard Oil
        { id = 203862, buff = 25123, stat = "caster" },  -- Brilliant Mana Oil
        { id = 203865, buff = 25122, stat = "caster" },  -- Brilliant Wizard Oil
        { id = 23122, buff = 28891, stat = "physical", wmask = 1097715 },  -- Consecrated Sharpening Stone
        { id = 20747, buff = 25120, stat = "caster" },  -- Lesser Mana Oil
        { id = 20750, buff = 25121, stat = "caster" },  -- Wizard Oil
        { id = 12404, buff = 16138, stat = "physical", wmask = 33731 },  -- Dense Sharpening Stone
        { id = 12643, buff = 16622, stat = "physical", wmask = 9264 },  -- Dense Weightstone
        { id = 3829, buff = 3595, stat = "caster", wmask = 174067 },  -- Frost Oil
        { id = 20746, buff = 25119, stat = "caster" },  -- Lesser Wizard Oil
        { id = 7964, buff = 9900, stat = "physical", wmask = 33731 },  -- Solid Sharpening Stone
        { id = 7965, buff = 9903, stat = "physical", wmask = 9264 },  -- Solid Weightstone
        { id = 3824, buff = 3594, stat = "caster", wmask = 174067 },  -- Shadow Oil
        { id = 20745, buff = 25118, stat = "caster" },  -- Minor Mana Oil
        { id = 34861, buff = 45731, stat = "physical" },  -- Sharpened Fish Hook
        { id = 2871, buff = 2830, stat = "physical", wmask = 33731 },  -- Heavy Sharpening Stone
        { id = 3241, buff = 3114, stat = "physical", wmask = 9264 },  -- Heavy Weightstone
        { id = 2863, buff = 2829, stat = "physical", wmask = 33731 },  -- Coarse Sharpening Stone
        { id = 3240, buff = 3113, stat = "physical", wmask = 9264 },  -- Coarse Weightstone
        { id = 20744, buff = 25117, stat = "caster" },  -- Minor Wizard Oil
        { id = 2862, buff = 2828, stat = "physical", wmask = 33731 },  -- Rough Sharpening Stone
        { id = 3239, buff = 3112, stat = "physical", wmask = 9264 },  -- Rough Weightstone
    },
})

-- ──────────────────────────── HAND-CURATED (not generated) ────────────────────────────
-- Curated extras the per-class generator above doesn't cover: aura-discovered utility
-- categories (xp foods, duration-filtered to 20m+) plus toys and class self-buffs. All flow
-- through the same detect+overlay pipeline via `source`. This block is part of the generator
-- template, so a re-run preserves it verbatim - edit it here.
if SpellDB.RegisterPrecombatBuffsExtra then
    SpellDB.RegisterPrecombatBuffsExtra({
        -- (Speed foods/flasks - the Speed *secondary stat*, rating bit 13 - are generated
        --  above tagged stat = "speed". Flat run-speed % foods, aura 31, are intentionally
        --  not tracked: they don't stack and can't be validated OOC.)

        -- XP (leveling): long XP buffs only (>= 20m). Off by default. Tome of Combat Training
        -- (10m) intentionally excluded by the duration floor.
        { category = "xp", id = 166750, buff = 289982 },      -- Draught of Ten Lands (60m)
        { category = "xp", id = 166751, buff = 289982 },      -- Draught of Ten Lands (60m)
        { category = "xp", id = 239142, buff = 1221184 },     -- Bottle of Mysterious Wisdom (120m)
        { category = "xp", id = 254693, buff = 1258529 },     -- Distilled Knowledge of Timeways (120m)
        { category = "xp", id = 209997, buff = 423860 },      -- Distilled Knowledge of Timeways (120m)

        -- XP / leveling toys (source = "toy": owned via PlayerHasToy, used via /usetoy)
        -- { category = "xp", id = <toyItemID>, buff = <auraSpellID>, source = "toy" },

        -- Class self-buffs (source = "spell": known via IsSpellKnown, cast via type=spell)
        -- { category = "classBuff", id = <spellID>, buff = <auraSpellID>, source = "spell" },
    })
end


-- ──────────────────────────── EATING AURAS (generated) ────────────────────────────
-- Every eat/drink regen aura ("Food"/"Refreshment" variants) reachable from a food
-- item's use-spell trigger chain. This is the aura visible on the player while eating;
-- SpellDB.GetActiveEatingAura tests set membership for the eat sweep and "wait" hint.
if SpellDB.RegisterEatingAuras then
    SpellDB.RegisterEatingAuras({
        430, 431, 432, 433, 434, 435, 833, 1127, 1129, 1131, 1133, 1135,
        1137, 2639, 5004, 5006, 5007, 6410, 7737, 10256, 10257, 18124, 18194, 18229,
        18230, 18232, 18233, 18234, 21149, 22731, 22734, 24005, 24355, 24707, 24800, 24869,
        25660, 25694, 25695, 25696, 25702, 25703, 25888, 25889, 25941, 25990, 26260, 26261,
        26401, 26402, 27089, 27094, 29008, 29055, 29073, 32112, 33253, 33255, 33258, 33260,
        33262, 33264, 33265, 33266, 33269, 33725, 33773, 33774, 34291, 35270, 35271, 40768,
        41030, 42207, 42311, 42312, 43180, 43182, 43183, 43763, 45020, 45548, 46683, 46755,
        46812, 46898, 52911, 53283, 61874, 64056, 65420, 65422, 66041, 72623, 80166, 80167,
        80168, 80169, 87544, 87566, 87567, 87568, 87570, 87571, 87572, 87573, 87577, 87584,
        87586, 87587, 87588, 87594, 87595, 87597, 87599, 87601, 87602, 87604, 87636, 87648,
        87958, 87959, 94468, 100365, 100367, 100374, 100376, 100379, 104235, 104262, 104269, 104270,
        104934, 105230, 105231, 105232, 105233, 108030, 111841, 111842, 118358, 125879, 127843, 148247,
        148922, 148984, 160598, 160599, 167152, 170908, 172786, 175780, 175787, 185703, 191876, 192000,
        192001, 192002, 192128, 195472, 201312, 203443, 215752, 223602, 225737, 225738, 227227, 227229,
        257427, 257428, 262265, 262568, 262569, 274910, 274911, 274913, 274914, 276030, 276041, 279739,
        281605, 281606, 297098, 303634, 303680, 305441, 308429, 308433, 314646, 314648, 318086, 329593,
        340109, 348436, 348439, 359070, 360640, 369156, 369159, 369161, 369162, 369166, 394350, 396381,
        396621, 396917, 396918, 396919, 396920, 396921, 397012, 398851, 405351, 410668, 450770, 452276,
        452319, 452382, 452384, 452389, 456574, 456575, 460938, 462174, 462179, 470480, 473490, 1232065,
        1250721, 1256686, 1269917, 1269920, 1269921, 1269922, 1286535, 1286537, 1290925, 1290926, 1290927, 1290928,
        1291822, 1291824, 1291825, 1291827, 1291838, 1291839, 1291840, 1291841, 1291842, 1291843, 1291844, 1291845,
        1291847, 1291848, 1291849, 1291850, 1291851, 1291853, 1291855, 1291857, 1291859, 1291944, 1291945, 1291946,
    })
end

if SpellDB.RegisterFoodWellFedBuffs then
    SpellDB.RegisterFoodWellFedBuffs({
        19706, 19708, 19709, 19710, 19711, 24870, 33254, 33256, 33257, 33259, 33261, 33263, 33268, 35272, 42293, 43764, 45245, 53284, 57100, 57102, 57107, 57286, 57288, 57291, 57329, 57332, 57334, 57356, 57358, 57360, 57365, 59230, 62349, 65410, 65415, 65416, 87548, 87549, 87550, 87551, 87552, 87554, 87555, 87559, 87560, 87561, 87562, 87563, 87564, 87565, 87634, 87635, 100375, 104278, 104279, 104280, 124151, 124210, 124211, 124212, 124213, 124214, 124215, 124216, 124217, 124218, 124219, 124220, 124221, 125070, 125071, 125102, 125104, 125106, 125108, 125113, 125115, 131828, 145304, 146807, 146809, 160724, 160726, 160778, 160793, 160832, 160839, 160889, 160893, 160895, 160897, 160900, 160902, 168349, 174062, 174077, 174078, 174079, 174080, 175218, 175219, 175220, 175222, 175223, 175785, 177931, 180745, 180746, 180748, 180749, 180750, 185736, 201223, 201330, 201332, 201334, 207076, 225597, 225598, 225599, 225600, 225602, 225603, 225604, 225605, 226805, 226807, 257408, 257410, 257413, 257415, 257418, 257420, 257422, 257424, 294365, 297034, 297035, 297037, 297039, 308430, 308434, 308474, 308488, 308504, 308506, 308509, 308514, 347173, 347520, 382145, 382146, 382149, 382150, 382152, 382153, 382154, 382155, 382156, 382157, 398458, 451916, 451917, 451918, 451920, 454137, 454177, 454178, 454179, 454180, 455369, 457284, 461845, 461853, 461854, 461855, 461856, 461857, 461858, 461859, 461860, 461861, 461922, 461924, 461925, 461927, 461937, 461938, 461939, 461940, 461942, 461943, 461944, 461945, 461946, 461947, 461948, 461949, 461957, 461958, 461959, 461960, 1219182, 1219183, 1219184, 1219185, 1232086, 1232087, 1232089, 1232091, 1232313, 1232316, 1232317, 1232318, 1232320, 1232321, 1232324, 1232325, 1232490, 1232491, 1232492, 1232493, 1232496, 1232498, 1232500, 1232501, 1232582, 1232584, 1232585, 1233400, 1233401, 1233402, 1233403, 1233404, 1233405, 1233406, 1233407, 1233408, 1283372, 1284616, 1284617, 1284618, 1284619, 1294727, 1305151, 1305152, 1305154, 1305156,
    })
end
