-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Maintained enemy DoT applicator cast spells -> debuff duration (s).
-- While the debuff is live on the current target, DotTracker sinks these to the
-- back of the queue, un-sinking ~30% before the duration estimate (pandemic
-- refresh window) or earlier if the live aura-removal bridge sees it drop.
-- 0 = unknown duration (no pandemic lead; rely on the removal bridge). Stacking
-- DoTs and channels are excluded (they must keep being suggested).
-- GENERATED by tools/gen_target_dots.py from client data build 12.1.0.69382.
-- Do not hand-edit (script-driven applicators go in the generator's CURATED list).
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterTargetDots then return end

SpellDB.RegisterTargetDots({
[172]=14,  -- Corruption
[339]=30,  -- Entangling Roots
[348]=18,  -- Immolate (script-applies its DoT)
[589]=16,  -- Shadow Word: Pain
[703]=18,  -- Garrote
[980]=18,  -- Agony (stacks ramp passively; recast is still a wasted refresh)
[1079]=24,  -- Rip
[1822]=15,  -- Rake
[1943]=24,  -- Rupture
[8921]=18,  -- Moonfire (base; covers talent variants via GetBaseSpell)
[14914]=7,  -- Holy Fire
[27243]=12,  -- Seed of Corruption
[34914]=21,  -- Vampiric Touch
[49184]=24,  -- Howling Blast (script-applies Frost Fever)
[50842]=24,  -- Blood Boil (script-applies Blood Plague)
[63106]=15,  -- Siphon Life
[77575]=24,  -- Outbreak
[93402]=18,  -- Sunfire (script-applies its DoT)
[102359]=10,  -- Mass Entanglement
[114923]=12,  -- Nether Tempest
[118297]=21,  -- Immolate
[122470]=6,  -- Touch of Karma (script-applies its reflect DoT)
[162487]=20,  -- Steel Trap
[164812]=18,  -- Moonfire
[164815]=18,  -- Sunfire
[195292]=24,  -- Death's Caress
[196607]=8,  -- Eye of the Tiger
[202347]=24,  -- Stellar Flare
[204066]=8,  -- Lunar Beam
[205023]=8,  -- Conflagration
[205179]=16,  -- Phantom Singularity
[205273]=6,  -- Wake of Ashes
[205545]=4,  -- Odyn's Fury
[205546]=4,  -- Odyn's Fury
[207407]=3,  -- Soul Carver
[210723]=6,  -- Ashamane's Frenzy
[212431]=3,  -- Explosive Shot
[215537]=6,  -- Trauma
[217200]=12,  -- Barbed Shot
[255937]=9,  -- Wake of Ashes
[271788]=18,  -- Serpent Sting
[285381]=24,  -- Primal Wrath (applies Rip via script)
[328547]=0,  -- Serrated Bone Spike
[360194]=16,  -- Deathmark
[376079]=6,  -- Champion's Spear
[376103]=12,  -- Radiant Spark
[383344]=9,  -- Expurgation
[383665]=2,  -- Incendiary Eruptions
[384318]=8,  -- Thunderous Roar
[385059]=4,  -- Odyn's Fury
[385408]=10,  -- Sepsis
[385424]=0,  -- Serrated Bone Spike
[385627]=14,  -- Kingsbane
[386997]=8,  -- Soul Rot
[391189]=15,  -- Burning Wound
[393400]=8,  -- Chi Surge
[394062]=15,  -- Rend
[426591]=14,  -- Goremaw's Bite
[444483]=12,  -- Controlled Instincts
[445468]=18,  -- Wither (stacking false positive)
[449624]=10,  -- Soul Anathema
[467741]=6,  -- Shadow Dagger
[470411]=18,  -- Flame Shock
[1237885]=12,  -- Thorn Bloom
[1252871]=8,  -- Red Moon
[1259790]=8,  -- Unstable Affliction (stacking false positive)
[1261060]=6,  -- Deep Wounds
})
