# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 wealdly
# Generates Data/SelfAuras.lua from client data CSV exports.
#
# Pure self-buff spells: every effect the spell has is a non-stacking aura
# applied to the caster, with a real duration. Re-casting one while its buff is
# active is redundant by construction (the pandemic window still allows
# refreshes near expiry), so these feed RedundancyFilter's unique-aura
# classification across all classes - closing hand-curation gaps like
# Slice and Dice being suggested while already active.
#
# Strict on purpose: any damage/heal/trigger/other effect excludes the spell
# (fail-open - a spell we're unsure about is never suppressed).
#
# Inputs (wago.tools CSV exports): SpellEffect, SpellAuraOptions, SpellMisc,
#   SpellDuration, SkillLineAbility, TraitDefinition
# Run: python tools/gen_self_auras.py [csv_dir] [build]

import csv
import re
import sys
from pathlib import Path

DEFAULT_CSV_DIR = Path(__file__).resolve().parent.parent / "Documentation" / "wow_spell_csv"
EFFECT_APPLY_AURA = 6
TARGET_UNIT_CASTER = 1


def read_csv(path):
    with open(path, encoding="utf-8-sig", newline="") as f:
        yield from csv.DictReader(f)


def main():
    csv_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV_DIR
    build = sys.argv[2] if len(sys.argv) > 2 else max(
        (m.group(1) for p in csv_dir.glob("*.csv") for m in [re.search(r"\.(\d+\.\d+\.\d+\.\d+)\.csv$", p.name)] if m),
        key=lambda b: [int(x) for x in b.split(".")], default="unknown")  # header stamp follows the folder

    def find(table):
        hits = sorted(csv_dir.glob(f"{table}.*.csv"))
        if not hits:
            sys.exit(f"missing {table} csv in {csv_dir}")
        return hits[-1]

    universe = set()
    for row in read_csv(find("SkillLineAbility")):
        universe.add(int(row["Spell"]))
    for row in read_csv(find("TraitDefinition")):
        for col in ("SpellID", "VisibleSpellID", "OverridesSpellID"):
            v = int(row[col] or 0)
            if v > 0:
                universe.add(v)

    # Every base-difficulty effect must be a self-applied aura
    has_effects = set()
    disqualified = set()
    for row in read_csv(find("SpellEffect")):
        sid = int(row["SpellID"])
        if sid not in universe or int(row["DifficultyID"] or 0) != 0:
            continue
        has_effects.add(sid)
        if (int(row["Effect"] or 0) != EFFECT_APPLY_AURA
                or int(row["ImplicitTarget_0"] or 0) != TARGET_UNIT_CASTER):
            disqualified.add(sid)
    candidates = has_effects - disqualified

    # Non-stacking only (stacking self-buffs must keep being suggested)
    for row in read_csv(find("SpellAuraOptions")):
        sid = int(row["SpellID"])
        if sid in candidates and int(row["DifficultyID"] or 0) == 0:
            if int(row["CumulativeAura"] or 0) > 1:
                candidates.discard(sid)

    # Must have a real duration (0 = instant/passive; -1 = infinite counts as a buff)
    durations = {}
    for row in read_csv(find("SpellDuration")):
        durations[int(row["ID"])] = int(row["Duration"] or 0)
    out = set()
    for row in read_csv(find("SpellMisc")):
        sid = int(row["SpellID"])
        if sid in candidates and int(row["DifficultyID"] or 0) == 0:
            if durations.get(int(row["DurationIndex"] or 0), 0) != 0:
                out.add(sid)

    names = {int(r["ID"]): r["Name_lang"] for r in read_csv(find("SpellName"))}

    def nm(sid):
        return (names.get(sid) or "?").replace("\r", "").replace("\n", " ")

    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Copyright (C) 2024-2026 wealdly",
        "-- JustAC: Pure self-buff spells (every effect is a non-stacking self-applied",
        "-- aura with a duration). Re-casting while active is redundant; feeds",
        "-- RedundancyFilter's unique-aura classification across all classes.",
        f"-- GENERATED by tools/gen_self_auras.py from client data build {build}.",
        "-- Do not hand-edit.",
        'local SpellDB = LibStub("JustAC-SpellDB", true)',
        "if not SpellDB or not SpellDB.RegisterSelfAuras then return end",
        "",
        "SpellDB.RegisterSelfAuras({",
    ]
    for sid in sorted(out):
        lines.append(f"[{sid}]=true,  -- {nm(sid)}")
    lines += ["})", ""]

    out_path = Path(__file__).parent.parent / "Data" / "SelfAuras.lua"
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{out_path}: {len(out)} pure self-buff spells, universe {len(universe)}, build {build}")


if __name__ == "__main__":
    main()
