# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 wealdly
# Generates Data/AuraDurations.lua from client data CSV exports.
#
# Static base aura durations (ms) for local buff-window tracking: runtime aura
# APIs are secret in combat, so we time our own buff windows from our own casts
# and read the window LENGTH from this table. Mirrors gen_spell_cooldowns.py.
#
# Inputs (Documentation/wow_spell_csv, wago.tools CSV exports):
#   SpellMisc.csv       - per-spell DurationIndex (base difficulty)
#   SpellDuration.csv   - per-index Duration (ms)
#   SkillLineAbility.csv / TraitDefinition.csv - player-learnable spell filter
#   SpellName.csv       - names for comments
#
# Run: python tools/gen_aura_durations.py [csv_dir] [build]

import csv
import re
import sys
from pathlib import Path

DEFAULT_CSV_DIR = Path(__file__).resolve().parent.parent / "Documentation" / "wow_spell_csv"


def read_csv(path):
    with open(path, encoding="utf-8-sig", newline="") as f:
        yield from csv.DictReader(f)


def main():
    csv_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV_DIR
    build = sys.argv[2] if len(sys.argv) > 2 else max(
        (m.group(1) for p in csv_dir.glob("*.csv") for m in [re.search(r"\.(\d+\.\d+\.\d+\.\d+)\.csv$", p.name)] if m),
        key=lambda b: [int(x) for x in b.split(".")], default="unknown")  # header stamp follows the folder

    def find(table):
        hits = sorted(csv_dir.glob(f"{table}.*.csv"))
        if not hits:
            sys.exit(f"missing {table} csv in {csv_dir}")
        return hits[-1]

    # Player-relevant spell universe: class/profession skill lines + talents.
    universe = set()
    for row in read_csv(find("SkillLineAbility")):
        universe.add(int(row["Spell"]))
    for row in read_csv(find("TraitDefinition")):
        for col in ("SpellID", "VisibleSpellID", "OverridesSpellID"):
            v = int(row[col] or 0)
            if v > 0:
                universe.add(v)

    # DurationIndex -> Duration (ms)
    dur_index = {}
    for row in read_csv(find("SpellDuration")):
        dur_index[int(row["ID"])] = int(row.get("Duration") or 0)

    # Per-spell base aura duration (base difficulty only), player universe, finite only.
    out = {}
    for row in read_csv(find("SpellMisc")):
        if int(row.get("DifficultyID") or 0) != 0:
            continue
        sid = int(row.get("SpellID") or 0)
        if sid not in universe:
            continue
        ms = dur_index.get(int(row.get("DurationIndex") or 0), 0)
        if ms and ms > 0:
            out[sid] = ms

    names = {int(r["ID"]): r["Name_lang"] for r in read_csv(find("SpellName"))}

    def nm(sid):
        return (names.get(sid) or "?").replace("\r", "").replace("\n", " ")

    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Copyright (C) 2024-2026 wealdly",
        "-- JustAC: Static base aura durations (ms) for local buff-window tracking.",
        "-- Runtime aura APIs are secret in combat, so buff windows are timed from our",
        "-- own casts and this table supplies the length (SpellMisc.DurationIndex ->",
        "-- SpellDuration.Duration).",
        f"-- GENERATED by tools/gen_aura_durations.py from client data build {build}.",
        "-- Do not hand-edit. Entry: [spellID] = durationMs.",
        'local lib = LibStub:NewLibrary("JustAC-AuraDurationData", 1)',
        "if not lib then return end",
        "",
        "local D = {",
    ]
    for sid in sorted(out):
        lines.append(f"[{sid}]={out[sid]},  -- {nm(sid)}")
    lines += [
        "}",
        "",
        "--- @return number|nil durationMs",
        "function lib.Get(spellID)",
        "    return D[spellID]",
        "end",
        "",
    ]

    out_path = Path(__file__).parent.parent / "Data" / "AuraDurations.lua"
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{out_path}: {len(out)} auras, universe {len(universe)}, build {build}")


if __name__ == "__main__":
    main()
