# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 wealdly
# Generates Data/AssistedCombatOrder.lua: Blizzard's own per-spec priority order, read from
# the client's assisted-combat tables. It is the tiebreaker for the "Match Blizzard's pick"
# ordering, whose context rank leaves most of the tail tied - and the only order those ties
# had was the rotation list's, which is sorted by spell id and means nothing.
#
# A spell usually has SEVERAL steps: conditional ones high up ("Whirlwind if the cleave buff
# is missing") and an unconditional one lower down. The rank is its LAST step - the position
# it holds when nothing special is true. Measured on Fury, Frost Mage, Assassination and
# Beast Mastery: first-step order put situational AoE steps at the very top (Thunder Clap and
# Whirlwind ahead of Rampage); last-step order reads cooldowns > spenders > builders > filler.
#
# Run: python tools/gen_assisted_combat_order.py

from pathlib import Path

import audit_assisted_combat as ac

OUT = Path(__file__).resolve().parent.parent / "Data" / "AssistedCombatOrder.lua"


def main():
    names = ac.spell_names()
    build = sorted(ac.CSV_DIR.glob("AssistedCombatStep.*.csv"))[-1].name.split(".", 1)[1].rsplit(".csv", 1)[0]
    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Copyright (C) 2024-2026 wealdly",
        "-- JustAC: Blizzard's assisted-combat priority order per spec (rank = a spell's LAST step,",
        "-- its unconditional position). Tiebreaker for the \"Match Blizzard's pick\" ordering.",
        f"-- GENERATED by tools/gen_assisted_combat_order.py from client data build {build}.",
        "-- Do not hand-edit.",
        'local RotationImport = LibStub("JustAC-RotationImport", true)',
        "if not RotationImport or not RotationImport.RegisterBlizzardOrder then return end",
        "",
        "RotationImport.RegisterBlizzardOrder({",
    ]
    for key, steps in sorted(ac.rotations().items()):
        last = {}
        for order, sid, _ in steps:
            last[sid] = order                      # steps arrive sorted: the last write wins
        ranked = sorted(last, key=lambda sid: last[sid])
        lines.append(f'  ["{key}"] = {{')
        for rank, sid in enumerate(ranked, 1):
            lines.append(f"    [{sid}]={rank},  -- {names.get(sid, '?')}")
        lines.append("  },")
    lines.append("})")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT}  ({len(ac.rotations())} specs)")


if __name__ == "__main__":
    ac.self_check()
    main()
