# Generate Data/HealingItems.lua from wago.tools DB2 dumps by EFFECT, not name - every
# consumable whose on-use spell restores health, so oddly-named health+mana pots and
# healthstones are caught automatically. Run each major patch after refreshing the CSVs.
#
#   python tools/gen_healing_items.py
#
# Ranking is done at runtime by SpellDB.GetBestHealingItem (reads the actual restored amount
# from the tooltip - fixed vs % of max health), so a long list is harmless: the owns-gate
# hides what you don't carry and weak/irrelevant pots never win. File order (newest->oldest)
# is only the fallback when a tooltip can't be read.
import csv, glob, os, re, sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CSV_DIR = os.path.join(ROOT, "Documentation", "wow_spell_csv")
OUT = os.path.join(ROOT, "Data", "HealingItems.lua")

# Consumable subclasses under item class 0 that can hold a heal-on-use: Generic, Potion,
# Elixir, Other (healthstones live here). Food(5)/Flask(3)/Scroll(4)/Bandage(7) excluded.
SUBCLASSES = {"0", "1", "2", "8"}
# On-use spell effects that restore health: 10 = direct heal, 136 = heal % of max health
# (healthstones, big % pots), 6+aura 8 = periodic heal.
HEAL_EFFECTS = {"10", "136"}
CRAFTING = ("Recipe", "Pattern", "Plan", "Formula", "Technique", "Design", "Enchant")
NOISE = re.compile(r"\bQA\b|\[|\bDNT\b|Deprecated|Brawler's", re.I)  # Brawler's = arena-only

EXPANSION = {11: "Midnight / current", 10: "Dragonflight / TWW", 9: "Shadowlands",
             8: "Battle for Azeroth", 7: "Legion", 6: "Warlords of Draenor",
             5: "Mists of Pandaria", 4: "Cataclysm", 3: "Wrath", 2: "Burning Crusade",
             1: "Classic", 0: "Classic / timeless"}


def newest(prefix):
    hits = sorted(glob.glob(os.path.join(CSV_DIR, prefix + ".*.csv")))
    if not hits:
        sys.exit(f"missing {prefix}.*.csv in {CSV_DIR}")
    return hits[-1]


def main():
    subclass = {}
    with open(newest("Item"), encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["ClassID"] == "0" and r["SubclassID"] in SUBCLASSES:
                subclass[r["ID"]] = r["SubclassID"]
    ie = {}  # effect id -> (spellID, triggerType)
    with open(newest("ItemEffect"), encoding="utf-8") as f:
        for r in csv.DictReader(f):
            ie[r["ID"]] = (r["SpellID"], r["TriggerType"])
    ix = defaultdict(list)
    with open(newest("ItemXItemEffect"), encoding="utf-8") as f:
        for r in csv.DictReader(f):
            ix[r["ItemID"]].append(r["ItemEffectID"])

    onuse = {}  # itemID -> on-use spellID (trigger 0)
    for iid in subclass:
        for e in ix.get(iid, []):
            sp, tt = ie.get(e, (None, None))
            if sp and tt == "0":
                onuse[iid] = sp
                break

    heal_spells = set()
    want = set(onuse.values())
    with open(newest("SpellEffect"), encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["SpellID"] in want and (
                    r["Effect"] in HEAL_EFFECTS
                    or (r["Effect"] == "6" and r["EffectAura"] == "8")):
                heal_spells.add(r["SpellID"])

    rows = []  # (exp, ilvl, id, name)
    with open(newest("ItemSparse"), encoding="utf-8") as f:
        for r in csv.DictReader(f):
            iid, name = r["ID"], r["Display_lang"]
            if onuse.get(iid) not in heal_spells:
                continue
            if r["InventoryType"] != "0":       # drop equippable rings/trinkets with heal procs
                continue
            if any(name.startswith(p + ":") for p in CRAFTING) or NOISE.search(name):
                continue
            rows.append((int(r["ExpansionID"] or 0), int(r["ItemLevel"] or 0), iid, name))
    rows.sort(key=lambda x: (-x[0], -x[1], x[3]))

    lines = [HEADER]
    cur = None
    for exp, ilvl, iid, name in rows:
        if exp != cur:
            lines.append(f"    -- ── {EXPANSION.get(exp, 'exp ' + str(exp))} ──")
            cur = exp
        lines.append(f"    {iid},  -- {name}")
    lines.append("})")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(rows)} healing items -> {OUT}", file=sys.stderr)


HEADER = """\
-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Health-restoring consumables (potions, healthstones, health+mana pots).
--
-- GENERATED by tools/gen_healing_items.py from wago.tools DB2 dumps - discovered by EFFECT
-- (on-use spell restores health: direct, % of max health, or periodic), so oddly-named pots
-- and healthstones are all caught. Do not hand-edit; re-run each major patch after refreshing
-- Documentation/wow_spell_csv/. Order is newest-first, but ranking is done at runtime by
-- SpellDB.GetBestHealingItem (reads the tooltip's restored amount), so the list can be broad:
-- the owns-gate hides what you don't carry and weak pots never win the pick.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterHealingItems then return end
-- Retail items, ids and durations: WoW Forever loads Data/ForeverConsumables.lua instead.
if SpellDB.IsForever and SpellDB.IsForever() then return end

SpellDB.RegisterHealingItems({"""


if __name__ == "__main__":
    main()
