# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 wealdly
# Generates Data/AuraStacks.lua from client data CSV exports.
#
# Max stack counts for stacking auras: RedundancyFilter's curated "unique aura"
# list can drift across patches; a spell whose aura stacks is never "unique
# already active", so this table acts as a client-data veto on that classification.
#
# Inputs (wago.tools CSV exports): SpellAuraOptions, SkillLineAbility, TraitDefinition
# Run: python tools/gen_aura_stacks.py [csv_dir] [build]

import csv
import re
import sys
from pathlib import Path

DEFAULT_CSV_DIR = Path(__file__).resolve().parent.parent / "Documentation" / "wow_spell_csv"


def read_csv(path):
    with open(path, encoding="utf-8-sig", newline="") as f:
        yield from csv.DictReader(f)


def main():
    csv_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV_DIR
    build = sys.argv[2] if len(sys.argv) > 2 else max(
        (m.group(1) for p in csv_dir.glob("*.csv") for m in [re.search(r"\.(\d+\.\d+\.\d+\.\d+)\.csv$", p.name)] if m),
        key=lambda b: [int(x) for x in b.split(".")], default="unknown")  # header stamp follows the folder

    def find(table):
        hits = sorted(csv_dir.glob(f"{table}.*.csv"))
        if not hits:
            sys.exit(f"missing {table} csv in {csv_dir}")
        return hits[-1]

    universe = set()
    for row in read_csv(find("SkillLineAbility")):
        universe.add(int(row["Spell"]))
    for row in read_csv(find("TraitDefinition")):
        for col in ("SpellID", "VisibleSpellID", "OverridesSpellID"):
            v = int(row[col] or 0)
            if v > 0:
                universe.add(v)

    out = {}
    for row in read_csv(find("SpellAuraOptions")):
        if int(row["DifficultyID"] or 0) != 0:
            continue
        stacks = int(row["CumulativeAura"] or 0)
        sid = int(row["SpellID"])
        if stacks > 1 and sid in universe:
            out[sid] = stacks

    names = {int(r["ID"]): r["Name_lang"] for r in read_csv(find("SpellName"))}

    def nm(sid):
        return (names.get(sid) or "?").replace("\r", "").replace("\n", " ")

    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Copyright (C) 2024-2026 wealdly",
        "-- JustAC: Aura max-stack data ([spellID] = maxStacks, stacking auras only).",
        "-- A stacking aura is never 'unique already active' - client-data veto for",
        "-- RedundancyFilter's unique-aura classification.",
        f"-- GENERATED by tools/gen_aura_stacks.py from client data build {build}.",
        "-- Do not hand-edit.",
        'local SpellDB = LibStub("JustAC-SpellDB", true)',
        "if not SpellDB or not SpellDB.RegisterAuraStacks then return end",
        "",
        "SpellDB.RegisterAuraStacks({",
    ]
    for sid in sorted(out):
        lines.append(f"[{sid}]={out[sid]},  -- {nm(sid)}")
    lines += ["})", ""]

    out_path = Path(__file__).parent.parent / "Data" / "AuraStacks.lua"
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{out_path}: {len(out)} stacking auras, universe {len(universe)}, build {build}")


if __name__ == "__main__":
    main()
