# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 wealdly
# Generates Data/SpellTransforms.lua: which action-bar buttons turn into which other
# abilities. Source: SpellEffect rows with the "override action bar spell" auras (332, 333),
# where EffectMiscValue_0 is the ORIGINAL button and EffectBasePointsF the form it becomes
# (Eviscerate -> Coup de Grace, Voidblade -> Hungering Slash).
#
# WHY. A form has its own spell id that the player never learns and that is not in the
# spellbook, so without this table the options search cannot find it and a list row cannot
# say what it covers. It also lets a form be its OWN custom-priority entry, live only while
# the button is showing it - which needs form -> original to know which button to watch.
#
# Only pairs whose ORIGINAL has a player acquisition route are kept (SkillLineAbility,
# SpecializationSpells, TraitDefinition); the rest are NPC, vehicle and encounter overrides.
# Same-name pairs are dropped: a rank or talent variant of one ability is not something a
# player would ever look for or order separately.
#
# Run: python tools/gen_spell_transforms.py

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_DIR = REPO / "Documentation" / "wow_spell_csv"
OUT = REPO / "Data" / "SpellTransforms.lua"
OVERRIDE_AURAS = {"332", "333"}


def load(table):
    path = sorted(CSV_DIR.glob(f"{table}.*.csv"))[-1]
    with open(path, encoding="utf-8-sig", newline="") as f:
        return path, list(csv.DictReader(f))


def main():
    path, names_rows = load("SpellName")
    build = path.name.split(".", 1)[1].rsplit(".csv", 1)[0]
    names = {int(r["ID"]): r["Name_lang"] for r in names_rows}

    learnable = set()
    for r in load("SkillLineAbility")[1]:
        learnable.add(int(r["Spell"]))
    for r in load("SpecializationSpells")[1]:
        learnable.add(int(r["SpellID"]))
    for r in load("TraitDefinition")[1]:
        for k in ("SpellID", "VisibleSpellID", "OverridesSpellID"):
            v = r.get(k) or ""
            if v.isdigit() and int(v) > 0:
                learnable.add(int(v))

    forms = {}   # form id -> set of original ids
    for r in load("SpellEffect")[1]:
        if r["EffectAura"] not in OVERRIDE_AURAS:
            continue
        try:
            form, orig = int(float(r["EffectBasePointsF"])), int(r["EffectMiscValue_0"])
        except ValueError:
            continue
        if form <= 0 or orig <= 0 or form == orig or orig not in learnable:
            continue
        if not names.get(form) or not names.get(orig) or names[form] == names[orig]:
            continue
        forms.setdefault(form, set()).add(orig)

    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Copyright (C) 2024-2026 wealdly",
        "-- JustAC: action-bar transforms - [form id] = { original button id, ... }. A form is",
        "-- what a button temporarily becomes (Eviscerate -> Coup de Grace); the player never",
        "-- learns its id and it is not in the spellbook. Feeds the options search and list",
        "-- rows, and lets a form be its own custom-priority entry (live only while shown).",
        f"-- GENERATED by tools/gen_spell_transforms.py from client data build {build}.",
        "-- Do not hand-edit.",
        'local SpellDB = LibStub("JustAC-SpellDB", true)',
        "if not SpellDB or not SpellDB.RegisterTransforms then return end",
        "",
        "SpellDB.RegisterTransforms({",
    ]
    for form in sorted(forms):
        origs = sorted(forms[form])
        lines.append("[%d]={%s},  -- %s <- %s" % (
            form, ",".join(map(str, origs)), names[form], ", ".join(names[o] for o in origs)))
    lines.append("})")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT}  ({len(forms)} forms)")

    # The two pairs this exists for; if either goes missing the aura ids or columns moved.
    assert 196819 in forms.get(441776, ()), "Eviscerate -> Coup de Grace missing"
    assert 1245412 in forms.get(1239123, ()), "Voidblade -> Hungering Slash missing"


if __name__ == "__main__":
    main()
